### ISSUE TITLE
bug: Lambda logs "Queue not available" when Lambda function is re-created

### ISSUE THREAD

**Issue by exoego** [localstack/localstack#10280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In Docker logs, Localstack continuously says, `Error while polling lambda events for function arn:aws:lambda:us-east-1:000000000000:function:my-lambda:$LATEST: Queue not available`, when the Lambda function is re-created.

### Expected Behavior

Lambda's internal queue should be available and no error log should be shown.

### How are you starting LocalStack?

With a docker-compose file

### 1. Clone the repro repo

```bash
git clone https://github.com/exoego/localstack-lambda-queue-repro

cd localstack-lambda-queue-repro
```

### 2. Run docker compose in a terminal with the following command:

```bash
docker-compose up
```

### 3. Open another terminal and run the following command:

```bash
npm ci

npm run test
npm run test
```

### 4. Go to the tab where the docker is running and you will see the following error in Docker logs:
    
```bash
localstack-1  | 2024-02-20T04:22:34.170 ERROR --- [functhread94] l.s.l.i.event_manager      : Error while polling lambda events for function arn:aws:lambda:us-east-1:000000000000:function:my-lambda:$LATEST: Queue not available
localstack-1  | 2024-02-20T04:22:35.171 ERROR --- [functhread94] l.s.l.i.event_manager      : Error while polling lambda events for function arn:aws:lambda:us-east-1:000000000000:function:my-lambda:$LATEST: Queue not available
localstack-1  | 2024-02-20T04:22:36.173 ERROR --- [functhread94] l.s.l.i.event_manager      : Error while polling lambda events for function arn:aws:lambda:us-east-1:000000000000:function:my-lambda:$LATEST: Queue not available
```

### Environment

```markdown
- OS: macOS 14.2.1
- LocalStack: 3.1.0
```

### Anything else?

Repro: https://github.com/exoego/localstack-lambda-queue-repro

**Comment by MarcelStranak** [comment]
Hello @exoego, the Repro: https://github.com/exoego/localstack-lambda-queue-repro, is inaccessible. Please set the proper permissions to access the repository.

**Comment by exoego** [comment]
@MarcelStranak Ah, sorry. Made it public

**Comment by joe4dev** [comment]
Thank you very much @exoego for sharing the clear reproducer 👏👏

I can confirm that this is a reproducible bug caused by a race condition in the event manager **when re-creating a Lambda function with the same ARN immediately after deleting it**. Asynchronous Lambda invokes will not work anymore for such re-created functions.

## Background

The problem is that the event manager (responsible for handling async invokes) shuts down asynchronously and deletes the event queue [here](https://github.com/localstack/localstack/blob/0d94fade08c963e0c96f863b4808b1359d467ca4/localstack/services/lambda_/invocation/event_manager.py#L554). Due to a race condition, the `delete_queue` operation can happen after re-creating the new Lambda function, essentially deleting the internal event queue, which causes these error messages in the Lambda poller.

I created a quick fix locally to resolve the issue (and confirm the root case) and will implement a proper fix. I will let you know here when the fix is released.

**Comment by joe4dev** [comment]
Hi @exoego 👋 

This issue upon re-creating a Lambda function with the same name has been resolved in https://github.com/localstack/localstack/pull/10831. Please pull the latest Docker image and try again.

**Comment by exoego** [comment]
Confirmed that
- The issue still appears in stable release `3.4` as of `8569dadc82ddf0627569775dde517297351691ddbe28e60edd1f515b46f7ef2e`
- but resolved in `latest` as of 260a9a5aeca3e4dacbec0e1cafaa53a66a16eb52612f6b251e1039b101e1532b
 
Thanks!
