### ISSUE TITLE
Secretsmanager getSecretValue for nonexistent version returns 500

### ISSUE THREAD

**Issue by gipeshka** [localstack/localstack#10621]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hey guys, I'm trying to use the Localstack SecretsManager to build some integration tests and see a behaviour that kinda puzzles me.

In my case the secret might be present, but might also be missing, thus when I call `getSecretValue` I actually check the response and handle the exceptions (tested against the real SecretsManager). I'm using the Java SDK.
When a secret is missing LocalStack shows interesting logs:

```
idres-localstack  | 2024-04-09T11:52:09.880 ERROR --- [   asgi_gw_0] l.aws.handlers.logging     : exception during call chain
idres-localstack  | Traceback (most recent call last):
// traceback here
idres-localstack  |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/secretsmanager/models.py", line 441, in get_secret_value
idres-localstack  |     raise SecretNotFoundException()
idres-localstack  | moto.secretsmanager.exceptions.SecretNotFoundException: 400 Bad Request: {"__type": "ResourceNotFoundException", "message": "Secrets Manager can't find the specified secret."}
idres-localstack  | 2024-04-09T11:52:09.883  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS secretsmanager.GetSecretValue => 500 (InternalError)
```

And then SDK reports:

```
 Exception: java.util.concurrent.CompletionException: software.amazon.awssdk.services.secretsmanager.model.SecretsManagerException: exception while calling secretsmanager.GetSecretValue: 400 Bad Request: {"__type": "ResourceNotFoundException", "message": "Secrets Manager can't find the specified secret."} (Service: SecretsManager, Status Code: 500, Request ID: d0ba1d8b-4001-4891-ba15-5d4324956c40)
```

So the problem is that in fact the status of the real response is 500, not 400. This leads to SDK incorrectly interpreting the error and showing generic `SecretsManagerException` instead of expected `ResourceNotFoundException`.

### Expected Behavior

LocalStack SecretsManager responds with the status it reports.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

It's part of docker-compose file.

```yaml
services:
  localstack:
    container_name: "service-localstack"
    image: localstack/localstack:3.3.0
    ports:
      - "4566:4566"
    environment:
      - LS_LOG=debug
      - SERVICES=kinesis,s3,secretsmanager
      - KINESIS_PROVIDER=kinesalite
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```scala
secretsManagerClient
  .getSecretValue(
    GetSecretValueRequest
      .builder()
      .secretId(configuration.secretId)
      .versionStage("AWSPREVIOUS")
      .build()
  )
  .asScala
  .recover {
    case exception: CompletionException if exception.getCause.isInstanceOf[ResourceNotFoundException] =>
      None
  }
```

### Environment

```markdown
- OS: MacOS 13.6
- LocalStack: 3.3.0
```

**Comment by macnev2013** [comment]
Hello, we are pleased to inform you that we have implemented changes that should resolve your reported issue. Kindly update to the latest LocalStack container image and let us know if your issue has been resolved. Thank you!

**Comment by steffyP** [comment]
Hi @gipeshka, the fix is available in the localstack-pro image `latest`, and in version `3.4`

**Comment by gipeshka** [comment]
hey @steffyP, yeah, I can confirm it works as expected, thank you!

**Comment by mherger** [comment]
I think I'm still seeing this, or a very close relative, using the JS SDK. I would get a 500 with

```json
{
    "__type": "ResourceNotFoundException",
    "message": "Secrets Manager can't find the specified secret value for VersionId: xyz"
}
```

Shall I open a new issue report for this or would you re-open this one?

**Comment by macnev2013** [comment]
Hello @mherger, Thanks for reporting the issue.

If it's possible, could you please provide a small sample or a few snippets of your code? That would be very helpful for us to replicate the scenario end-to-end. Thanks.

**Comment by mherger** [comment]
The code is pretty simple:

```typescript
  try {
    const secretData: GetSecretValueCommandOutput = await secretsManager.send(getSecretCommand);
    secret = JSON.parse(secretData.SecretString) as StoredSecret;
  }
  catch(e) {
    if (e instanceof Error && e.name !== 'ResourceNotFoundException')
      console.error(e);
  }
```

But that condition to catch the `ResourceNotFoundException` is failing. Here's the output:

```
      SecretsManagerServiceException [InternalError]: exception while calling secretsmanager.GetSecretValue: 404 Not Found: {"__type": "ResourceNotFoundException", "message": "Secrets Manager can't find the specified secret value for VersionId: abc-123"}
          at throwDefaultError (/home/runner/work/xxxxx/node_modules/@smithy/smithy-client/dist-cjs/index.js:839:20)
          at /home/runner/work/xxxxx/node_modules/@smithy/smithy-client/dist-cjs/index.js:848:5
          at de_CommandError (/home/runner/work/xxxxx/node_modules/@aws-sdk/client-secrets-manager/dist-cjs/index.js:997:14)
          at processTicksAndRejections (node:internal/process/task_queues:95:5)
          at /home/runner/work/xxxxx/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
          at /home/runner/work/xxxxx/node_modules/@smithy/core/dist-cjs/index.js:165:18
          at /home/runner/work/xxxxx/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
          at /home/runner/work/xxxxx/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:34:22
          at getSecret (/home/runner/work/xxxxx/src/libs/keys-helper.ts:48:53)
          at createSecret (/home/runner/work/xxxxx/src/functions/rotate-secrets/handler.ts:84:14)
          at Object.<anonymous> (/home/runner/work/xxxxx/src/functions/rotate-secrets/handler.test.ts:93:5) {
        '$fault': 'client',
        '$metadata': {
          httpStatusCode: 500,
          requestId: 'd6c165a0-5bdb-4bb7-8186-bf4db88741aa',
          extendedRequestId: undefined,
          cfId: undefined,
          attempts: 3,
          totalRetryDelay: 148
        },
        __type: 'InternalError'
      }
```

**Comment by macnev2013** [comment]
Hi @mherger, This issue should be fixed in the `latest` version of localstack. Can you please try once again after updating your localstack docker image to the latest version? Please let us know if the issue still persists.

**Comment by mherger** [comment]
Thanks for looking into this. It seems the issue reported here is indeed fixed. My tests continue - but now fail unexpectedly elsewhere (running a `UpdateSecretVersionStageCommand`). It's again a failure I don't see with localstack v2.2, but I haven't had the time to further look into what exactly is failing.

**Comment by mherger** [comment]
I'm struggling to come up with a simple example: at some point of the reducing my code to the max it would start to work!

Could my issue be related to my using of a KMSClient mock (using `aws-sdk-client-mock`)? I see that localstack v3 has major changes in this area?
