### ISSUE TITLE
bug: Create EventBridge Pipe for DynamoStream -> API Destination using Terraform

### ISSUE THREAD

**Issue by tonestrike** [localstack/localstack#11305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am trying to implement EventBridge Pipes. The Terraform module aws_pipes_pipe. This is what I am attempting to create:
```
resource "aws_pipes_pipe" "dynamo_streams_to_api_pipe" {
      + arn           = (known after apply)
      + description   = "Managed by Terraform"
      + desired_state = "RUNNING"
      + id            = (known after apply)
      + name          = "main-api-pipe"
      + name_prefix   = (known after apply)
      + role_arn      = "arn:aws:iam::000000000000:role/main-api-pipe-pipe-role"
      + source        = "arn:aws:dynamodb:us-east-1:000000000000:table/main/stream/2024-08-03T19:13:58.667"
      + tags_all      = (known after apply)
      + target        = "arn:aws:events:us-east-1:000000000000:api-destination/dynamo-streams-api-destination/18edaad6-82dd-415d-bea7-f5b68388e22e"

      + source_parameters (known after apply)
    }
```

This is the error that I am receiving:
`Error: creating AWS EventBridge Pipes Pipe (main-api-pipe): operation error Pipes: CreatePipe, https response error StatusCode: 403, RequestID: 783db9ad-c0f1-4c4e-8316-c2e6c06b2856, api error UnrecognizedClientException: The security token included in the request is invalid.`

I do not see any logs in LocalStack suggesting that it is attempting to be created. I am wondering if I need to override an endpoint for EventBridge pipes? I attempted the following and that did not work:
```
provider "aws" {
  region = "us-east-1"

  endpoints {
    pipes = "http://localhost:4566/"
  }
}
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

The [basic example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pipes_pipe#basic-usage) from the Terraform docs should work but does not.

### Environment

```markdown
- OS: MacOS
- LocalStack:
LocalStack version: 3.6.1.dev20240802032301
LocalStack build date: 2024-08-02
LocalStack build git hash: e43b348
```

**Comment by MarcelStranak** [comment]
I've tested the deployment of the [basic example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/pipes_pipe#basic-usage) from the terraform site, and the issue is with the missing implementation of operation `ListTagsForResource`.

Correctly mentioned in the LocalStack and Terraform logs:

```log
Error: listing tags for EventBridge Pipes Pipe (arn:aws:pipes:us-east-1:000000000000:pipe/example-pipe): operation error Pipes: ListTagsForResource, https response error StatusCode: 501, RequestID: c2c710e1-cea9-40cb-8d19-220d41ee024e, api error InternalFailure: API action 'ListTagsForResource' for service 'pipes' not yet implemented or pro feature - please check https://docs.localstack.cloud/references/coverage/coverage_pipes/ for further information
```
>Coverage info at https://docs.localstack.cloud/references/coverage/coverage_pipes/

**Comment by sannya-singal** [comment]
Hi @tonestrike 👋 Thanks for reporting the issue. We have implemented the tagging of resources and it should be available in the `latest` release. Please do not hesitate to reach out if you further encounter any issue. Thanks!

**Comment by tonestrike** [comment]
@tonestrike the basic example was for EventBridge -> SQS. I was trying to use an API target. I'm still facing the same issue. 

```
Unable to find EventBridge connection '28eacf2c-60a5-4c80-8246-ce580840430e' for API destination arn:aws:events:us-east-1:000000000000:api-destination/main-destination/7aea48bc-6035-470d-ab66-7777d33282c0
```
