### ISSUE TITLE
Lambda CloudWatch Logs not Working on Windows (Docker)

### ISSUE THREAD

**Issue by mattwcole** [localstack/localstack#1211]
Lambda logs are forwarded to CloudWatch automatically since #1161, however this doesn't seem to work on a Windows host with LocalStack in Docker. I have reproduced this in an example .NET Core Lambda triggered by a DynamoDB stream [here](https://github.com/mattwcole/local-dynamodb-stream). When I trigger the lambda from a Windows host, no log group is created:

```sh
$ aws --endpoint-url=http://localhost:4586 logs describe-log-groups
{
    "logGroups": []
}
```

From Ubuntu 18.04, I can access the logs from the created log group:

```sh
aws --endpoint-url=http://localhost:4586 logs filter-log-events \
    --log-group-name /aws/lambda/local-function
```

**Comment by svennergr** [comment]
I can approve this.

![grafik](https://user-images.githubusercontent.com/8092184/55626552-23e96300-57ac-11e9-898c-63ca69a87600.png)

Upper aws is: 
aws-cli/1.16.28 Python/2.7.15 Windows/10 botocore/1.12.18

Downer aws is:
aws-cli/1.16.139 Python/3.6.7 Linux/4.9.125-linuxkit botocore/1.12.129

**Comment by gsfataviva** [comment]
I'm seeing the same problem.

**Comment by donhenton** [comment]
seeing this on mac
awslocal logs describe-log-groups returns empty set

**Comment by whummer** [comment]
Thanks for reporting @mattwcole @svennergr @gsfataviva @donhenton . Can you please give it a try with the latest version? Thanks

Please ensure that the region defined in your CLI/SDK client matches the region defined for LocalStack (via `DEFAULT_REGION`, defaults to `us-east-1`).

**Comment by chrisfentiman** [comment]
I have the same issue on mac - when `DEFAULT_REGION=us-west-2` and I make a query using CLI with `--region us-west-2` the return is 

```json
{
    "events": [],
    "searchedLogStreams": []
}
```

However, changing the environment to use `us-east-1` the logs work as expected.

**Comment by macnev2013** [comment]
Hey @chrisfentiman thanks for reporting.
I checked it and looks like its fixed in the `latest` version. Can you give it a try with `latest` version?
Thanks.

**Comment by whummer** [comment]
Thanks for the update @chrisfentiman - this appears to be fixed in the `latest` version (please note that we have recently pushed some changes for the region setup). Closing this issue - please reopen or share more details here if the problem persists. Thanks!

**Comment by olmax99** [comment]
Problem still persists in community edition Docker localstack/localstack:10.2.0-0.12.4

Going back to image localstack/locastack:0.11.6 resolved the issue.
