### ISSUE TITLE
Lambda event does not get SQS MessageAttributes.

### ISSUE THREAD

**Issue by MathiasBojda** [localstack/localstack#1215]
Hi,
It seems like when you have an SQS Queue invoking an Lambda function, that it does get the SQS message, however it seems that the MessageAttributes is always an empty object, even though there is MessageAttributes sent a long.

**Comment by maccamlcQ** [comment]
I have this same problem, of an empty MessageAttributes object, but I am sending a SQS message and also receiving it using the Amazon SDK in my test code.

Using 0.10.4 localstack

**Comment by whummer** [comment]
Thanks for reporting @MathiasBojda @maccamlcQ . Has this by any chance been fixed in the PR #1239 ? If not, can you please provide a small, self-contained sample to reproduce this issue? Thanks

**Comment by rvigus** [comment]
@whummer I am having the same issue still - I have been checking the code inside localstack/localstack/services/sqs/sqs_listener.py and I think I can see why.

There is a helper function called _format_attributes() that is not applied to the req_data variable prior to it being passed into format_message_attributes()

There is a class method inside ProxyListenerSQS, called _process_sent_message() here you can see that the req_data variable will not be formatted according to _format_attributes(), and therefore format_message_attributes() will return an empty dictionary.
