### ISSUE TITLE
Lambda executor "docker-reuse" errors with "tcp :9001: bind: address already in use"

### ISSUE THREAD

**Issue by nuttamsingh** [localstack/localstack#1777]
Hi I'm using localstack 0.8.5 and was using lambda executor in "docker-reuse" mode. This was working all along but suddenly started to give these port bind errors during execution.  There don't seems to be any processes using this port however.  If i use "docker" as the lambda executor this issue goes away, but i end up with another problem a huge number of containers one for each execution of the lambda. My integration tests essentially send events to a kinesis stream and the lambda reads from this stream so for each execution i get a new container. This is not ideal as it hogs up all the memory on the machine and the tests end up timing out.

Has anyone come across this issue recently or know what changed. I don't see any changes to the 0.8.5 docker image.

localstack_1             | 2019-11-20T05:25:59:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function: Lambda process returned error status code: 1. Output:
localstack_1             | 2019/11/20 05:25:59 listen tcp :9001: bind: address already in use
localstack_1             |  Traceback (most recent call last):
localstack_1             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 250, in run_lambda
localstack_1             |     event, context=context, version=version, async=async)
localstack_1             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 129, in execute
localstack_1             |     result, log_output = self.run_lambda_executor(cmd, environment, async)
localstack_1             |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 66, in run_lambda_executor
localstack_1             |     (return_code, log_output))
localstack_1             | Exception: Lambda process returned error status code: 1. Output:
localstack_1             | 2019/11/20 05:25:59 listen tcp :9001: bind: address already in use
localstack_1             | 

These errors happen sporadically, but the result of these errors is nondeterministic test failures :(

Docker compose service:

 localstack:
    image: localstack/localstack:0.8.5
    ports:
      - "4567-4583:4567-4583"
    expose:
      - "4567-4583"
    environment:
      - SERVICES=sqs,kinesis,lambda,dynamodb
      - DEFAULT_REGION=us-east-1
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/private${TMPDIR}/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

**Comment by nuttamsingh** [comment]
Oh BTW i get this same error on newer images as well, 0.9.1, 0.10.5, latest..

**Comment by whummer** [comment]
Thanks for reporting @nuttamsingh . This has to do with the fact that the upstream images from https://github.com/lambci/docker-lambda have recently changed (see [this PR](lambci/docker-lambda#218)). This should have been fixed recently in #1771 - in this change we're [locking the Docker tag to a snapshot version](https://github.com/localstack/localstack/pull/1771/files#diff-ed18594c2e57d0eebca69c26c1c87986R688). Can you please give it a try with the latest version of the LocalStack Docker image?

**Comment by nuttamsingh** [comment]
@whummer Thanks for your comments, nope unfortunately still seeing the same issue :(

**Comment by deontaljaard** [comment]
@whummer, @nuttamsingh I can confirm that this issue has been resolved with the **latest** version of the LocalStack Docker image. 

I was experiencing the same issue although the execution context being different, i.e. parallel states using AWS step functions.

**Comment by whummer** [comment]
Thanks @deontaljaard !

@nuttamsingh Can you please also give it a try with the `latest` version - after doing a `docker pull localstack/localstack`. Please re-open if the problem still persists on latest. Thanks

**Comment by wapmesquita** [comment]
I created the PR https://github.com/localstack/localstack/pull/1861 to try to address this fix but I'd like to discuss more about it.

**Comment by VLitskevich** [comment]
Hi. I'm using the latest version of the image and have the same problem.
```
localstack_1          | 2020-05-09T10:46:25:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:handler: Lambda process returned error status code: 1. Result: . Output:
localstack_1          | 2020/05/09 10:46:25 listen tcp :9001: bind: address already in use Traceback (most recent call last):
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 488, in run_lambda
localstack_1          |     result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 133, in execute
localstack_1          |     return do_execute()
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 120, in do_execute
localstack_1          |     raise e
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 108, in do_execute
localstack_1          |     result = self._execute(func_arn, func_details, event, context, version)
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 257, in _execute
localstack_1          |     result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
localstack_1          |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 170, in run_lambda_executor
localstack_1          |     raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
localstack_1          | Exception: Lambda process returned error status code: 1. Result: . Output:
localstack_1          | 2020/05/09 10:46:25 listen tcp :9001: bind: address already in use
```

**Comment by shengwubin** [comment]
@VLitskevich I had the same issues, and what I did is removing all existing lambda docker containers. After removing all running lambda docker containers, I run the same lambda function in the local environment( with docker-network=host)

**Comment by doodlemoonch** [comment]
@shengwubin @VLitskevich might find `docker rm $(docker container ls -q --filter ancestor=lambci/lambda:nodejs10.x)` useful

**Comment by loganasherjones** [comment]
I'm having a similar problem. I tried to create a lambda that pushes to Kinesis and a different lambda that pushes to S3. Anytime I invoke either lambda, I get the stacktrace  @VLitskevich posted. I've deleted all the containers and restarted, and still no luck. You should be able to reproduce with the following:

**docker-compose.yml**

```
version: "2.1"

services:
  localstack:
    image: localstack/localstack:0.11.3
    ports:
      - "4566:4566"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,iam,lambda,kinesis,logs,sns,sqs,ssm
      - DEBUG=${DEBUG- }
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=docker-reuse
      - LOCALSTACK_HOSTNAME=localstack
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

**example.py**
```
import boto3

def handler(event, context):
    session = boto3.Session(aws_access_key_id="fake", aws_secret_access_key="fake", region_name="us-east-1")
    s3 = session.client("s3", endpoint_url="http://localstack:4566")
    return s3.put_object(
        Bucket="first-bucket",
        Key="Object_1",
        Body="Sample Text",
        ACL="public-read",
    )
```

**main.tf**
```
provider "aws" {
  profile = "local"
  region = "us-east-1"

  access_key = "fake"
  secret_key = "fake"

  s3_force_path_style = true

  skip_credentials_validation = true
  skip_metadata_api_check = true
  skip_requesting_account_id = true

  endpoints {
    s3 = "http://localhost:4566"
    lambda = "http://localhost:4566"
    iam = "http://localhost:4566"
  }
}

resource "aws_iam_role" "iam_for_lambda" {
  name = "iam_for_lambda"
  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "lambda.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

# This is the destination file for the zip.
variable "lambda_zip" {
  default="example.zip"
}

resource "aws_lambda_function" "example" {
  function_name = "example"
  filename = var.lambda_zip
  handler = "example.handler"
  runtime = "python3.8"
  source_code_hash = filebase64sha256(var.lambda_zip)
  role = aws_iam_role.iam_for_lambda.arn
}

resource "aws_s3_bucket" "first-bucket" {
  bucket="first-bucket"
}

```

Then you should be able to run the following:

```
$ zip example.py example.zip
$ docker-compose up -d
$ terraform init
$ terraform apply
$ awslocal lambda invoke --function-name example out.json
```

And you should get something along these lines:

```

localstack_1  | 2020-06-29T19:48:09:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: docker cp "/tmp/localstack/zipfile.20916a86/." "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_example:/var/task"; docker exec -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_example /var/rapid/init --bootstrap /var/runtime/bootstrap --enable-msg-logs example.handler
localstack_1  | 2020-06-29T19:48:09:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:example: Lambda process returned error status code: 1. Result: . Output:
localstack_1  | 2020/06/29 19:48:09 listen tcp :9001: bind: address already in use Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 528, in run_lambda
localstack_1  |     result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 153, in execute
localstack_1  |     return do_execute()
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 145, in do_execute
localstack_1  |     return _run(func_arn=func_arn)
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 143, in wrapped
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 139, in wrapped
localstack_1  |     result = func(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 138, in _run
localstack_1  |     raise e
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 126, in _run
localstack_1  |     result = self._execute(func_arn, func_details, event, context, version)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 281, in _execute
localstack_1  |     result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
localstack_1  |   File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 190, in run_lambda_executor
localstack_1  |     raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
localstack_1  | Exception: Lambda process returned error status code: 1. Result: . Output:
localstack_1  | 2020/06/29 19:48:09 listen tcp :9001: bind: address already in use
localstack_1  | 
```

**Comment by loganasherjones** [comment]
Hmm, I can actually get my example to work if I change the endpoint url from `http://localstack:4566` to `http://172.17.0.1:4566`

Interestingly, I tried to use `f"http://{os.environ['LOCALSTACK_HOSTNAME']}:4566"` but that didn't work either. It gave me the same address already in use error as before.

**Comment by JCFerrerG** [comment]
This is still an issue with the nodejs12.x runtime as confirmed in https://github.com/localstack/localstack/pull/1855#issuecomment-565044149. It seems the [snapshot locking fix](https://github.com/localstack/localstack/blob/v0.11.3/localstack/services/awslambda/lambda_executors.py#L764) described in https://github.com/localstack/localstack/issues/1777#issuecomment-555899654 does not work for nodejs12.x.

In my case, the following configuration pulls lambci/lambda:nodejs12.x and throws the error.
``` yaml
# docker-compose.yml
...
   localstack:
        image: localstack/localstack:0.11.2
        ports:
            - "4566-4599:4566-4599"
            - 8080:8080
        environment:
            - SERVICES=${SERVICES- }
            - DEBUG=${LOCALSTACK_DEBUG-false}
            - DATA_DIR=${DATA_DIR- }
            - PORT_WEB_UI=${PORT_WEB_UI- }
            - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-docker}
            - LAMBDA_DOCKER_NETWORK=mystack_default
            - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
            - DOCKER_HOST=unix:///var/run/docker.sock
            - HOST_TMP_FOLDER=${TMPDIR}
        volumes:
            - ./initaws:/docker-entrypoint-initaws.d
            - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"
...
```

@wapmesquita has offered a workaround (https://github.com/localstack/localstack/issues/1777#issuecomment-565067245) using DOCKER_LAMBDA_API_PORT, but I do not understand how to use it as intended.

**Questions**
* Why am I running into this error when LAMBDA_DOCKER_NETWORK != 'host'?  
* Can this workaround help me if LAMBDA_DOCKER_NETWORK != 'host'?
* Is there documentation or an example for this?

**Comment by wapmesquita** [comment]
@JCFerrerG I remember that these changes mentioned in [comment #1777](https://github.com/localstack/localstack/issues/1777#issuecomment-565067245) have had fixed this issue by that time. I don't know if the NodeJS image has changed since then, it'd be nice to check.

The variable `DOCKER_LAMBDA_API_PORT` would be used only internally to start the web API in the lambda container.

I ran millions of tests using Localstack with lambdas in NodeJS 12. So, I'd guess that it was something after Feb 2020.

**Comment by nhoughto** [comment]
Still seeing this on `0.12.2` on `provided` lambda, it is trivial to reproduce and appears to be a localstack->lambci race condition, if I run an invoke sequentially it is ok but fails everytime if I run 4 invokes in parallel as per following logs.

lambci `init` is called for each invocation, `init` starts the server on `9001` and since localstack isn't using `STAY_OPEN` mode it starts for every execution rather than just the first. My guess is that the localstack logic to ensure the `docker exec ..` runs sequentially isn't the same as how the `init` process is actually behaving, and it ends up running `init` multiple times concurrently leading to failure?

```
2020-11-23T01:13:26:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:test-lambda"
2020-11-23T01:13:26:DEBUG:localstack.services.awslambda.lambda_executors: Priming docker container with runtime "provided" and arn "arn:aws:lambda:us-east-1:000000000000:function:test-lambda".
2020-11-23T01:13:26:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" | cat
2020-11-23T01:13:26:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:test-lambda"
2020-11-23T01:13:26:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:test-lambda"
2020-11-23T01:13:26:DEBUG:localstack.services.awslambda.lambda_executors: Priming docker container (status "0"): localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda
2020-11-23T01:13:26:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" | cat
2020-11-23T01:13:26:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:test-lambda"
2020-11-23T01:13:26:DEBUG:localstack.services.awslambda.lambda_executors: Creating container: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda
2020-11-23T01:13:26:DEBUG:localstack.services.awslambda.lambda_executors: docker create --rm --name "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" --entrypoint /bin/bash  --interactive -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT"  -e AWS_LAMBDA_EVENT_BODY='{}' -e LOCALSTACK_HOSTNAME=172.17.0.1 -e EDGE_PORT=4566 -e _HANDLER=custom-handler -e AWS_LAMBDA_FUNCTION_TIMEOUT=900 -e AWS_LAMBDA_FUNCTION_NAME=test-lambda -e AWS_LAMBDA_FUNCTION_VERSION='$LATEST' -e AWS_LAMBDA_FUNCTION_INVOKED_ARN=arn:aws:lambda:us-east-1:000000000000:function:test-lambda -e AWS_LAMBDA_COGNITO_IDENTITY='{}' -e _LAMBDA_SERVER_PORT=5004     "lambci:provided"
2020-11-23T01:13:26:DEBUG:localstack.services.awslambda.lambda_executors: Copying files to container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" from "/tmp/localstack/zipfile.0961ad82".
2020-11-23T01:13:26:DEBUG:localstack.services.awslambda.lambda_executors: docker cp "/tmp/localstack/zipfile.0961ad82/." "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda:/var/task"
2020-11-23T01:13:26:DEBUG:localstack.services.awslambda.lambda_executors: Starting container: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda
2020-11-23T01:13:26:DEBUG:localstack.services.awslambda.lambda_executors: docker start localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting the entrypoint for image: "lambci:provided"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: docker image inspect --format="{{ .Config.Entrypoint }}" "lambci:provided"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" | cat
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting container network: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: docker inspect localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda --format "{{ .HostConfig.NetworkMode }}"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Using entrypoint "/var/runtime/init" for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" on network "default".
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Command for docker-reuse Lambda executor:  docker exec -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda /var/runtime/init custom-handler
2020-11-23T01:13:28:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd:  docker exec -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda /var/runtime/init custom-handler
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Priming docker container with runtime "provided" and arn "arn:aws:lambda:us-east-1:000000000000:function:test-lambda".
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" | cat
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Priming docker container (status "1"): localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting the entrypoint for image: "lambci:provided"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: docker image inspect --format="{{ .Config.Entrypoint }}" "lambci:provided"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" | cat
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting container network: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: docker inspect localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda --format "{{ .HostConfig.NetworkMode }}"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Using entrypoint "/var/runtime/init" for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" on network "default".
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Command for docker-reuse Lambda executor:  docker exec -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda /var/runtime/init custom-handler
2020-11-23T01:13:28:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd:  docker exec -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda /var/runtime/init custom-handler
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Priming docker container with runtime "provided" and arn "arn:aws:lambda:us-east-1:000000000000:function:test-lambda".
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" | cat
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Priming docker container (status "1"): localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting the entrypoint for image: "lambci:provided"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: docker image inspect --format="{{ .Config.Entrypoint }}" "lambci:provided"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" | cat
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting container network: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: docker inspect localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda --format "{{ .HostConfig.NetworkMode }}"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:test-lambda result / log output:

> 2020/11/23 01:13:28 listen tcp :9001: bind: address already in use
2020-11-23T01:13:28:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack-stub:4566", path "/", target header "", auth header "", data "b''"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Using entrypoint "/var/runtime/init" for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" on network "default".
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Command for docker-reuse Lambda executor:  docker exec -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda /var/runtime/init custom-handler
2020-11-23T01:13:28:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd:  docker exec -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda /var/runtime/init custom-handler
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Priming docker container with runtime "provided" and arn "arn:aws:lambda:us-east-1:000000000000:function:test-lambda".
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" | cat
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Priming docker container (status "1"): localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting the entrypoint for image: "lambci:provided"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: docker image inspect --format="{{ .Config.Entrypoint }}" "lambci:provided"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting status for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda": docker ps -a --filter name='localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda' --format "{{ .Status }} - {{ .Names }}" | grep -w "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" | cat
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Getting container network: localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: docker inspect localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda --format "{{ .HostConfig.NetworkMode }}"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:test-lambda result / log output:

> 2020/11/23 01:13:28 listen tcp :9001: bind: address already in use
2020-11-23T01:13:28:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack-stub:4566", path "/", target header "", auth header "", data "b''"
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Using entrypoint "/var/runtime/init" for container "localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda" on network "default".
2020-11-23T01:13:28:DEBUG:localstack.services.awslambda.lambda_executors: Command for docker-reuse Lambda executor:  docker exec -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda /var/runtime/init custom-handler
2020-11-23T01:13:28:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd:  docker exec -e AWS_LAMBDA_EVENT_BODY="$AWS_LAMBDA_EVENT_BODY" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e EDGE_PORT="$EDGE_PORT" -e _HANDLER="$_HANDLER" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN" -e AWS_LAMBDA_COGNITO_IDENTITY="$AWS_LAMBDA_COGNITO_IDENTITY" -e _LAMBDA_SERVER_PORT="$_LAMBDA_SERVER_PORT" localstack_lambda_arn_aws_lambda_us-east-1_000000000000_function_test-lambda /var/runtime/init custom-handler
2020-11-23T01:13:29:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:test-lambda result / log output:

> 2020/11/23 01:13:29 listen tcp :9001: bind: address already in use
2020-11-23T01:13:29:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test-lambda: Lambda process returned error status code: 1. Result: . Output:
2020/11/23 01:13:28 listen tcp :9001: bind: address already in use Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 541, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 173, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 165, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 158, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 146, in _run
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 303, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 210, in run_lambda_executor
    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
Exception: Lambda process returned error status code: 1. Result: . Output:
2020/11/23 01:13:28 listen tcp :9001: bind: address already in use

2020-11-23T01:13:29:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack-stub:4566", path "/", target header "", auth header "", data "b''"
2020-11-23T01:13:29:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test-lambda: Lambda process returned error status code: 1. Result: . Output:
2020/11/23 01:13:28 listen tcp :9001: bind: address already in use Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 541, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 173, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 165, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 158, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 146, in _run
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 303, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 210, in run_lambda_executor
    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
Exception: Lambda process returned error status code: 1. Result: . Output:
2020/11/23 01:13:28 listen tcp :9001: bind: address already in use

2020-11-23T01:13:29:INFO:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:test-lambda: Lambda process returned error status code: 1. Result: . Output:
2020/11/23 01:13:29 listen tcp :9001: bind: address already in use Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 541, in run_lambda
    result = LAMBDA_EXECUTOR.execute(func_arn, func_details, event, context=context,
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 173, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 165, in do_execute
    return _run(func_arn=func_arn)
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 149, in wrapped
    raise e
  File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 145, in wrapped
    result = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 158, in _run
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 146, in _run
    result = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 303, in _execute
    result = self.run_lambda_executor(cmd, stdin, env_vars=environment, func_details=func_details)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 210, in run_lambda_executor
    raise Exception('Lambda process returned error status code: %s. Result: %s. Output:\n%s' %
Exception: Lambda process returned error status code: 1. Result: . Output:
2020/11/23 01:13:29 listen tcp :9001: bind: address already in use

2020-11-23T01:13:30:DEBUG:localstack.services.awslambda.lambda_executors: Lambda arn:aws:lambda:us-east-1:000000000000:function:test-lambda result / log output:
test outpu
> 2020-11-23 01:13:29:186       main INFO  v.DefaultEnvironment -                           - Established active environments: [ec2, cloud, function, lambda]
> 2020-11-23 01:13:30:631 pGroup-1-1 DEBUG ty.DefaultHttpClient -                           - Sending HTTP Request: GET /2018-06-01/runtime/invocation/next
> 2020-11-23 01:13:30:632 pGroup-1-1 DEBUG ty.DefaultHttpClient -                           - Chosen Server: 127.0.0.1(9001)
> 2020-11-23 01:13:30:635 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - host: 127.0.0.1:9001
> 2020-11-23 01:13:30:635 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - connection: close
> START RequestId: 446ad7d1-dcdf-1eaf-fdf2-7a0172f8df5a Version: $LATEST
> 2020-11-23 01:13:30:674 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - HTTP Client Response Received for Request: GET http://127.0.0.1:9001/2018-06-01/runtime/invocation/next
> 2020-11-23 01:13:30:674 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - Status Code: 200 OK
> 2020-11-23 01:13:30:675 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - Content-Type: application/json
> 2020-11-23 01:13:30:676 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - Lambda-Runtime-Aws-Request-Id: 446ad7d1-dcdf-1eaf-fdf2-7a0172f8df5a
> 2020-11-23 01:13:30:676 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - Lambda-Runtime-Cognito-Identity: {}
> 2020-11-23 01:13:30:677 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - Lambda-Runtime-Deadline-Ms: 1606094908366
> 2020-11-23 01:13:30:677 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - Lambda-Runtime-Invoked-Function-Arn: arn:aws:lambda:us-east-1:000000000000:function:test-lambda
> 2020-11-23 01:13:30:677 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - Lambda-Runtime-Trace-Id: Root=1-dc99d00f-c079a84d433534434534ef0d;Parent=91ed514f1e5c03b2;Sampled=1
> 2020-11-23 01:13:30:677 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - Date: Mon, 23 Nov 2020 01:13:30 GMT
> 2020-11-23 01:13:30:678 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - Content-Length: 2
> 2020-11-23 01:13:30:678 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - Connection: close
> 2020-11-23 01:13:30:679 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - Response Body
> 2020-11-23 01:13:30:679 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - ----
> 2020-11-23 01:13:30:680 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - {}
> 2020-11-23 01:13:30:680 pGroup-1-1 TRACE ty.DefaultHttpClient -                           - ----
> 2020-11-23 01:13:30:724       main INFO  g.RunProcessFunction -                           - ffmpeg -version
> 2020-11-23 01:13:30:827 pGroup-1-2 DEBUG ty.DefaultHttpClient -                           - Sending HTTP Request: POST /2018-06-01/runtime/invocation/446ad7d1-dcdf-1eaf-fdf2-7a0172f8df5a/response
> 2020-11-23 01:13:30:828 pGroup-1-2 DEBUG ty.DefaultHttpClient -                           - Chosen Server: 127.0.0.1(9001)
> 2020-11-23 01:13:30:828 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - host: 127.0.0.1:9001
> 2020-11-23 01:13:30:828 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - connection: close
> 2020-11-23 01:13:30:828 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - content-type: application/json
> 2020-11-23 01:13:30:828 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - content-length: 176
> 2020-11-23 01:13:30:828 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - Request Body
> 2020-11-23 01:13:30:828 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - ----
> 2020-11-23 01:13:30:828 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - test outpu
> 2020-11-23 01:13:30:828 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - ----
> 2020-11-23 01:13:30:841 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - HTTP Client Response Received for Request: POST http://127.0.0.1:9001/2018-06-01/runtime/invocation/446ad7d1-dcdf-1eaf-fdf2-7a0172f8df5a/response
> 2020-11-23 01:13:30:841 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - Status Code: 202 Accepted
> 2020-11-23 01:13:30:841 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - Content-Type: application/json
> 2020-11-23 01:13:30:841 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - Date: Mon, 23 Nov 2020 01:13:30 GMT
> 2020-11-23 01:13:30:841 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - Connection: close
> 2020-11-23 01:13:30:842 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - content-length: 16
> 2020-11-23 01:13:30:842 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - Response Body
> 2020-11-23 01:13:30:842 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - ----
> 2020-11-23 01:13:30:842 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - {"status":"OK"}
> 
> 2020-11-23 01:13:30:842 pGroup-1-2 TRACE ty.DefaultHttpClient -                           - ----
> 2020-11-23 01:13:30:846 pGroup-1-3 DEBUG ty.DefaultHttpClient -                           - Sending HTTP Request: GET /2018-06-01/runtime/invocation/next
> 2020-11-23 01:13:30:846 pGroup-1-3 DEBUG ty.DefaultHttpClient -                           - Chosen Server: 127.0.0.1(9001)
> 2020-11-23 01:13:30:847 pGroup-1-3 TRACE ty.DefaultHttpClient -                           - host: 127.0.0.1:9001
> 2020-11-23 01:13:30:847 pGroup-1-3 TRACE ty.DefaultHttpClient -                           - connection: close
> END RequestId: 446ad7d1-dcdf-1eaf-fdf2-7a0172f8df5a
> REPORT RequestId: 446ad7d1-dcdf-1eaf-fdf2-7a0172f8df5a	Init Duration: 3517.75 ms	Duration: 200.95 ms	Billed Duration: 300 ms	Memory Size: 1536 MB	Max Memory Used: 216 MB	
2020-11-23T01:13:30:INFO:localstack.services.edge: Unable to find forwarding rule for host "localstack-stub:4566", path "/", target header "", auth header "", data "b''"
2020-11-23T01:14:14:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2020-11-23T01:15:14:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2020-11-23T01:16:14:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2020-11-23T01:17:14:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2020-11-23T01:18:14:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2020-11-23T01:19:14:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
2020-11-23T01:20:14:INFO:localstack.services.awslambda.lambda_executors: Checking if there are idle containers.
```

**Comment by nhoughto** [comment]
If I override the default `lambci` entrypoint to force only one init runs at a time, it all works (as you'd expect)

its not my favourite, my script is:
```
#!/bin/sh
set -euo pipefail

# loop and sleep until we can get lock
while ! mkdir /tmp/lambda-running 2>/dev/null; do
    sleep 0.1
done

# trigger normal init process once we have lock
/var/runtime/init

# clear lock
rm -rf /tmp/lambda-running
```

**Comment by bnewtongomoxie** [comment]
@nhoughto can you give more information about how and where you implemented this script?

**Comment by nhoughto** [comment]
build a custom `lambci:provided` container, and use that script as the entrypoint script

we ended up moving away from it as it doesn't really work the way we want, it only ever lets 1 concurrent execution of a given lambda, which isn't great.. it doesn't fail with the tcp binding error but it wasn't great either.

**Comment by whummer** [comment]
Thanks for the update @nhoughto @bnewtongomoxie @wapmesquita  . This should now be fixed in #3371 - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks
