### ISSUE TITLE
MD5 returned by SQS does not match the calculation on the original request

### ISSUE THREAD

**Issue by miron4dev** [localstack/localstack#1841]
It looks like a duplicate of old issue https://github.com/localstack/localstack/issues/78
But now it's reproducible for me with the latest version of LocalStack.

**Comment by whummer** [comment]
Thanks for reporting @miron4dev . Can you please share your configuration and the specific you're running?

We already have a Java test that should cover this particular functionality: https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/test/java/cloud/localstack/SQSMessagingTest.java#L102-L134. Can you please clone the repo, and check if this command works for you?
```
$ AWS_DEFAULT_REGION=us-east-1 DEBUG=1 MVN_ARGS='-Dtest=cloud.localstack.SQSMessagingTest' make test-java
Dec 08, 2019 11:31:46 AM cloud.localstack.docker.Container createLocalstackContainer
INFO: Started container: 39887578197fd62feebfaf811c52e97bf9ab957ab805303acd1f8973e2d288ed
Dec 08, 2019 11:31:46 AM cloud.localstack.Localstack startup
INFO: Waiting for LocalStack container to be ready...
Dec 08, 2019 11:32:46 AM cloud.localstack.docker.Container stop
INFO: Stopped container: 39887578197fd62feebfaf811c52e97bf9ab957ab805303acd1f8973e2d288ed
$ echo $?
0
```

**Comment by miron4dev** [comment]
@whummer 

I cloned the repo and tried to execute it locally.

First of all, the test is failing here https://github.com/localstack/localstack/blob/master/localstack/ext/java/src/main/java/cloud/localstack/Localstack.java#L98

Instead of LocalStack ports, I see 
```
cat: can't open '/opt/code/localstack/.venv/lib/python3.7/site-packages/localstack_client/config.py': No such file or directory
```

In debug mode, I filled this map to go further and got the next error

```
com.amazonaws.AmazonClientException: MD5 returned by SQS does not match the calculation on the original request. (MD5 calculated by the message attributes: "23bf3e5b587065b0cfbe95761641595a", MD5 checksum returned: "068b4cc7d27c322bde50451db1f3b838")
```

**Comment by whummer** [comment]
Thanks @miron4dev . Which version of the Docker image are you using?
```
$ docker images | grep localstack
localstack/localstack                latest                   37aa9f906c82        3 hours ago         885MB
```
Does it work if you pull the latest image via
```
$ docker pull localstack/localstack
```
?

**Comment by miron4dev** [comment]
Thanks @whummer 

Ok. The latest version fixes `SQSMessagingTest`, but doesn't fix my problem. 
I've created a repo https://github.com/miron4dev/localstack-issue-1841
So you can reproduce it locally.

**Comment by whummer** [comment]
Thanks for the detailed report and for providing the sample project @miron4dev ! The issue related to SQS message attributes MD5 hashes should be fixed in #1850 .

Please note that I'm still running into the error below, which potentially could be related to #865
```
Exception in thread "main" java.lang.ClassNotFoundException: io.quarkus.amazon.lambda.runtime.QuarkusStreamHandler::handleRequest
```
Looks like the handler is not extracted properly when using the `class::method` syntax. Are you seeing the same error with the latest version?

**Comment by miron4dev** [comment]
Thank you @whummer 

The problem has been resolved! 
But I don't have `java.lang.ClassNotFoundException` that you provided. The lambda works fine and I received a `pong` message from it. `QuarkusStreamHandler` is included in `quarkus-amazon-lambda` dependency which is declared in pom.xml. So, if you followed the steps which I provided in README, it should work without errors. 

Anyway, the issue can be closed!

**Comment by Anja05** [comment]
@whummer I. m still facing the same issue even though using the latest local stack version. Caused by: com.amazonaws.AmazonClientException: MD5 returned by SQS does not match the calculation on the original request. (MD5 calculated by the message attributes: "cdf6c9c1634a92880297ec78aebe7d63", MD5 checksum returned: "e2932d64df403e342b12484e2075f31b")

Please suggest!

**Comment by mknutty** [comment]
@Anja05 I started to use localstack today and ran into the same issue. So i  "solved" it by a Java classpath hack. 
in your code, create a java class MessageMD5ChecksumHandler in the same package it is in the aws code. Then copy all the code from the AWS class to yours. Then comment out the offending lines. I suggest not going to prod like this. You can solve that with conditional if logic. If you are using spring you can use the profiles for this.

**Comment by rahulpopuri** [comment]
Also had the same issue with `localstack:latest`, I reverted to `0.11.2` and I don't see it any longer.

**Comment by mknutty** [comment]
> 0.11.2
Works for me! Thx @rahulpopuri !!!

**Comment by Anja05** [comment]
> Also had the same issue with `localstack:latest`, I reverted to `0.11.2` and I don't see it any longer.

It worked for me too:)

**Comment by mjeffrey** [comment]
Reverting to 0.11.2 works for me but unfortunately I need to use the latest for kms. 0.11.5. 
Similar case to the above, using queues to subscribe to sns.

**Comment by vivekkothari** [comment]
Something broke between this diff
https://github.com/localstack/localstack/compare/v0.14.2...v0.14.3
Tried a lot of versions finally found that it worked for me in 0.14.2, but started erroring out in 0.14.3

**Comment by nabedge** [comment]
+1
It is still bug in  `image: localstack/localstack:2.1.0`
