### ISSUE TITLE
States.ReferencePathConflict when appending to ResultPath in Step Function

### ISSUE THREAD

**Issue by ciaranevans** [localstack/localstack#1854]
### Summary
I've got a situation where I pass a JSON body containing a value to a Step Function, this is then passed to a Lambda Function which takes that value, then returns another value. I've got my Step Function setup so that the output of the State is a two value JSON object. This works in AWS with my Step Function definition but falls over when using LocalStack.

### Example for reproducing
Step Function definition:

```
{
  "StartAt": "my-function",
  "States": {
    "my-function": {
      "Type": "Task",
      "Resource": "<arn:of-my-function>",
      "ResultPath": "$.value_two",
      "End": true
    }
  }
}
```

JSON body _in_:

```
{
  "value_one": "hello"
}
```

Lambda (Python):

```
def handler(event, context):
  body = json.loads(event)
  # Do something
  return "world"
```

Expected output:

```
{
  "value_one": "hello",
  "value_two": "world"
}
```

### Actual output
```
{'events': [{'timestamp': datetime.datetime(2019, 12, 11, 13, 43, 54, 360000, tzinfo=tzlocal()),
   'type': 'ExecutionStarted',
   'id': 1,
   'previousEventId': 0,
   'executionStartedEventDetails': {'input': '{"value_one": "hello"}',
    'roleArn': 'arn:aws:iam::000000000000:role/a-role'}},
  {'timestamp': datetime.datetime(2019, 12, 11, 13, 43, 54, 360000, tzinfo=tzlocal()),
   'type': 'TaskStateEntered',
   'id': 2,
   'previousEventId': 0,
   'stateEnteredEventDetails': {'name': 'my-function',
    'input': '{"value_one": "hello"}'}},
  {'timestamp': datetime.datetime(2019, 12, 11, 13, 43, 54, 361000, tzinfo=tzlocal()),
   'type': 'LambdaFunctionScheduled',
   'id': 3,
   'previousEventId': 2,
   'lambdaFunctionScheduledEventDetails': {'resource': 'arn:aws:lambda:us-east-1:000000000000:function:my-function',
    'input': '{"value_one": "hello"}'}},
  {'timestamp': datetime.datetime(2019, 12, 11, 13, 43, 54, 361000, tzinfo=tzlocal()),
   'type': 'LambdaFunctionStarted',
   'id': 4,
   'previousEventId': 3},
  {'timestamp': datetime.datetime(2019, 12, 11, 13, 43, 55, 980000, tzinfo=tzlocal()),
   'type': 'LambdaFunctionSucceeded',
   'id': 5,
   'previousEventId': 4,
   'lambdaFunctionSucceededEventDetails': {'output': 'world'}},
  {'timestamp': datetime.datetime(2019, 12, 11, 13, 43, 55, 980000, tzinfo=tzlocal()),
   'type': 'ExecutionFailed',
   'id': 6,
   'previousEventId': 2,
   'executionFailedEventDetails': {'error': 'States.ReferencePathConflict',
    'cause': 'Can\'t parse input, message=Unrecognized token \'world\': was expecting (\'true\', \'false\' or \'null\')\n at [Source: (String)"world"; line: 1, column: 11] input=World'}}],
 'ResponseMetadata': {'HTTPStatusCode': 200,
  'HTTPHeaders': {'server': 'BaseHTTP/0.6 Python/3.7.5',
   'date': 'Wed, 11 Dec 2019 13:44:09 GMT',
   'connection': 'close',
   'content-length': '8199',
   'access-control-allow-origin': '*',
   'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH',
   'access-control-allow-headers': 'authorization,content-type,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging',
   'access-control-expose-headers': 'x-amz-version-id'},
  'RetryAttempts': 0}}
```

Any help is hugely appreciated! - As I said, this works fine on AWS but breaks on LocalStack :cry:

┆Issue is synchronized with this [Jira Bug](https://localstack.atlassian.net/browse/LOC-140) by [Unito](https://www.unito.io/learn-more)

**Comment by ciaranevans** [comment]
Bit of a guess but maybe: https://github.com/localstack/localstack/blob/dd0a9742da83dd05e110d35f5159fa656c4871c4/localstack/constants.py#L89 is out of date? 

The container is https://hub.docker.com/layers/amazon/aws-stepfunctions-local/1.4.0/images/sha256-13d87c66738dd54d10c00bbd2ac4a5765939c280a949245fbf23c8b6340e5326

**Comment by ciaranevans** [comment]
Going to the URL and checking the version of the jar:
```
java -jar StepFunctionsLocal.jar -v
Step Functions Local
Version: 1.4.0
Build: 2019-09-18
Step Functions Local
Version: 1.4.0
Build: 2019-09-18
```

Looks like it's up-to-date

**Comment by whummer** [comment]
Thanks for the detailed report @ciaranevans .  

The StepFunctions tests have been extended in #1856. Using `ResultPath` does seem to work well if the Lambda result is a JSON document (i.e., Python `dict`), but if a string is returned, I'm getting this with the latest version:
```
"executionFailedEventDetails":{"error":"States.ReferencePathConflict","cause":"Unable to apply step \"result_value\" to input \"testresult1\""}
```
Apparently StepFunctions local is trying to apply the path expression `$.result_value` to the Lambda output, which is counter-intuitive - in fact, it should be the other way around (the Lambda result should be returned from StepFunctions under the path `$.result_value` instead).

Please keep us posted about the outcome of the ticket you've posted with AWS. Thanks!

**Comment by ciaranevans** [comment]
> Thanks for the detailed report @ciaranevans .
> 
> The StepFunctions tests have been extended in #1856. Using `ResultPath` does seem to work well if the Lambda result is a JSON document (i.e., Python `dict`), but if a string is returned, I'm getting this with the latest version:
> 
> ```
> "executionFailedEventDetails":{"error":"States.ReferencePathConflict","cause":"Unable to apply step \"result_value\" to input \"testresult1\""}
> ```
> 
> Apparently StepFunctions local is trying to apply the path expression `$.result_value` to the Lambda output, which is counter-intuitive - in fact, it should be the other way around (the Lambda result should be returned from StepFunctions under the path `$.result_value` instead).
> 
> Please keep us posted about the outcome of the ticket you've posted with AWS. Thanks!

Thanks for the investigating @whummer really appreciate the help!

Will of course keep you posted on the ticket, hopefully it's something they can turn around in good time!

**Comment by ciaranevans** [comment]
@whummer 

```
Hello Ciaran,

Shane here from the AWS Premium Support team.

Thanks a lot for reaching out with this issue and also for providing the detailed steps on the git issue to reproduce.

I have passed this directly to our StepFunctions team, as soon as they get back to me I will update you via this case.

If you need anything in the meantime, please don't hesitate in reaching out.

Best regards,

Shane O.
Amazon Web Services
```

Will let you know when the team gets back to me!

**Comment by ciaranevans** [comment]
@whummer 
```
Hello Ciaran,

Thanks a lot for your patience, the team have come back to me.

The team have indeed confirmed this as a bug and have added it to the backlog. Right now the Step Functions team do not have an ETA for when the bug will be fixed however please do rest assured that thanks to you the team are now aware of the bug and will deploy a fix.

Again thank you very much for bringing this to our attention and if you have any additional questions, please don't hesitate in getting back to me

Best regards,

Shane O.
Amazon Web Services

```

**Comment by dnlopes** [comment]
Any news on this issue?

**Comment by ciaranevans** [comment]
@dnlopes I don't work at the company where I had access to that email/support ticket any longer unfortunately, though it very well could have been implemented.

**Comment by whummer** [comment]
Thanks again @ciaranevans @dnlopes - we have just tested this functionality manually, and the behavior of `ResultPath` is now fixed and available in the `latest` version of the Docker image. Please report here if there are any other issues related to this functionality. Thanks for your help.

**Comment by ciaranevans** [comment]
@whummer appreciate the update!

**Comment by bradseiler** [comment]
I'm still seeing this issue in the jar StepFunctionLocal:
`Step Functions Local
Version: 1.10.0
Build: 2022-04-05`
