### ISSUE TITLE
Error Invoking Lambda with Docker

### ISSUE THREAD

**Issue by miles-po** [localstack/localstack#1962]
Latest version of the Docker image (also failed with previous couple of versions).

Lambda loaded. `awslocal lambda list-functions` returns
```
{
    "Functions": [
        {
            "TracingConfig": {
                "Mode": "PassThrough"
            }, 
            "Version": "$LATEST", 
            "CodeSha256": "FpWGJCFmeoDOa4hgE9nBdoFeMM6pYwwNa4MFFSyxQt4=", 
            "FunctionName": "Hello", 
            "MemorySize": 128, 
            "CodeSize": 746, 
            "FunctionArn": "arn:aws:lambda:us-east-1:000000000000:function:Hello", 
            "Handler": "index.handler", 
            "Role": "arn:aws:iam::000000000000:role/dp-garage-dev-data-platform-api-user-role-to-assume", 
            "Timeout": 5, 
            "LastModified": "2020-01-17T19:06:43.534+0000", 
            "Runtime": "nodejs10.x", 
            "Description": ""
        }
    ]
}
```
Lambda code (`index.js`)
```js
exports.handler = (event, context, cb) => cb('hello world');
```
Calling with
```
awslocal lambda invoke --function-name Hello lambda.out
```
Error log (repeating message)
```
2020-01-17T19:07:46.326516000Z 
2020-01-17T19:07:47:WARNING:localstack.services.awslambda.lambda_executors: Empty event body specified for invocation of Lambda "arn:aws:lambda:us-east-1:000000000000:function:Hello"
2020-01-17T19:07:49:INFO:localstack.services.awslambda.lambda_executors: Running lambda cmd: CONTAINER_ID="$(docker create --user=root --entrypoint=/tmp/939fa309.sh -v /tmp/localstack/python27.bin:/usr/bin/python -v /tmp/localstack/gosu.bin:/usr/bin/gosu --dns 127.0.0.1 -i   -e DOCKER_LAMBDA_USE_STDIN="$DOCKER_LAMBDA_USE_STDIN" -e HOSTNAME="$HOSTNAME" -e LOCALSTACK_HOSTNAME="$LOCALSTACK_HOSTNAME" -e AWS_LAMBDA_FUNCTION_TIMEOUT="$AWS_LAMBDA_FUNCTION_TIMEOUT" -e AWS_LAMBDA_FUNCTION_NAME="$AWS_LAMBDA_FUNCTION_NAME" -e AWS_LAMBDA_FUNCTION_VERSION="$AWS_LAMBDA_FUNCTION_VERSION" -e AWS_LAMBDA_FUNCTION_INVOKED_ARN="$AWS_LAMBDA_FUNCTION_INVOKED_ARN"  --rm "lambci/lambda:nodejs10.x" "index.handler")";docker cp "/tmp/localstack/zipfile.89592b7a/." "$CONTAINER_ID:/var/task"; docker cp /tmp/939fa309.sh $CONTAINER_ID:/tmp/939fa309.sh; docker start -ai "$CONTAINER_ID";
2020-01-17T19:07:54:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:Hello: Lambda process returned error status code: 127. Result: nohup: failed to run command ‘python’: Permission denied. Output:
/tmp/939fa309.sh: line 229: gosu: command not found
Starting daemons... Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 384, in run_lambda
    event, context=context, version=version, asynchronous=asynchronous)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 90, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 75, in do_execute
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 71, in do_execute
    result, log_output = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 209, in _execute
    result, log_output = self.run_lambda_executor(cmd, stdin, environment)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 127, in run_lambda_executor
    (return_code, result, log_output))
Exception: Lambda process returned error status code: 127. Result: nohup: failed to run command ‘python’: Permission denied. Output:
/tmp/939fa309.sh: line 229: gosu: command not found
Starting daemons...
2020-01-17T19:07:54.332802200Z 
```

**Comment by whummer** [comment]
Thanks for reporting @miles-po . This should be fixed in the latest version - can you please do another `docker pull localstack/localstack` and try again? The latest version now ships with custom Lambda Docker images that contain the required utility programs (e.g., `gosu`) out of the box.

Closing this issue - please report here if the problem persists. Thanks!

**Comment by miles-po** [comment]
Problem persists, but has changed forms. Same command line. At first was a bug in my lambda where the "hello world" message was the first parameter of the callback. (PEBKAC error.) I fixed the bug, re-bundled the zip file, stopped the stack, cleared the Docker cache (`docker system prune -f`), and re-ran. Localstack seems to ignore the initial null (error) parameter.
```
$ awslocal lambda invoke --function-name Hello lambda.out
```
Output is as follows:
```
An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function arn:aws:lambda:us-east-1:000000000000:function:Hello: Lambda process returned error status code: 1. Result: {"errorType":"string","errorMessage":"hello world"}. Output:
START RequestId: 43c380f3-e459-1367-2b23-ec29ba8c6f90 Version: $LATEST
2020-01-20T17:58:09.674Z        43c380f3-e459-1367-2b23-ec29ba8c6f90    ERROR   Invoke Error    {"errorType":"Error","errorMessage":"hello world","stack":["Error: hello world","    at _homogeneousError (/var/runtime/CallbackContext.js:13:12)","    at postError (/var/runtime/CallbackContext.js:30:51)","    at callback (/var/runtime/CallbackContext.js:42:7)","    at /var/runtime/CallbackContext.js:105:16","    at Runtime.exports.handler (/var/task/index.js:1:43)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
END RequestId: 43c380f3-e459-1367-2b23-ec29ba8c6f90
REPORT RequestId: 43c380f3-e459-1367-2b23-ec29ba8c6f90  Init Duration: 2206.09 ms       Duration: 10.89 ms      Billed Duration: 100 ms Memory Size: 1536 MB    Max Memory Used: 0 MB
Starting daemons...
Starting server loop on UDP port 2000
Starting DNS server loop on UDP port 53
 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 385, in run_lambda
    event, context=context, version=version, asynchronous=asynchronous)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 95, in execute
    return do_execute()
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 80, in do_execute
    raise e
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 76, in do_execute
    result, log_output = self._execute(func_arn, func_details, event, context, version)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 214, in _execute
    result, log_output = self.run_lambda_executor(cmd, stdin, environment)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_executors.py", line 132, in run_lambda_executor
    (return_code, result, log_output))
Exception: Lambda process returned error status code: 1. Result: {"errorType":"string","errorMessage":"hello world"}. Output:
START RequestId: 43c380f3-e459-1367-2b23-ec29ba8c6f90 Version: $LATEST
2020-01-20T17:58:09.674Z        43c380f3-e459-1367-2b23-ec29ba8c6f90    ERROR   Invoke Error    {"errorType":"Error","errorMessage":"hello world","stack":["Error: hello world","    at _homogeneousError (/var/runtime/CallbackContext.js:13:12)","    at postError (/var/runtime/CallbackContext.js:30:51)","    at callback (/var/runtime/CallbackContext.js:42:7)","    at /var/runtime/CallbackContext.js:105:16","    at Runtime.exports.handler (/var/task/index.js:1:43)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
END RequestId: 43c380f3-e459-1367-2b23-ec29ba8c6f90
REPORT RequestId: 43c380f3-e459-1367-2b23-ec29ba8c6f90  Init Duration: 2206.09 ms       Duration: 10.89 ms      Billed Duration: 100 ms Memory Size: 1536 MB    Max Memory Used: 0 MB
Starting daemons...
Starting server loop on UDP port 2000
Starting DNS server loop on UDP port 53
```

**Comment by miles-po** [comment]
Confirmed contents of zip file.
`unzip -p hello.zip index.js` returns
```js
exports.handler = (event, context, cb) => cb(null, 'hello world');

```

**Comment by whummer** [comment]
Thanks for the follow-up @miles-po . I was able to reproduce this issue, but only if I change your handler to this:
```
const handle = (event, context, cb) => cb('hello world');
```
If I use this handler:
```
exports.handler = (event, context, cb) => cb(null, 'hello world');
```
... then I'm getting a successful invocation:
```
$ awslocal lambda invoke --function-name Hello lambda.out
{
    "StatusCode": 200
}
```
Can you please try tearing down and restarting the LocalStack container, and deploy again?

If it still doesn't work, please post the `docker run ...` command that gets printed in the LocalStack process when invoking the lambda. Thanks

**Comment by miles-po** [comment]
Don't know what I messed up before, but it's working now. Probably PEBKAC error again. Thanks.
