### ISSUE TITLE
java.lang.IllegalArgumentException: Duplicated keys (RedrivePolicy) are provided, when retrieving SQS attributes

### ISSUE THREAD

**Issue by razorree** [localstack/localstack#1992]
It happens on 0.10.5-7 localstack (run in docker) run with (docker-compose.yml):
```
 localstack:
    image: localstack/localstack:0.10.7
    ports:
    - "4567-4583:4567-4583" # The ports for AWS Services
    - "9999:8080"
    environment:
    - SERVICES=s3,dynamodb,sns,sqs,kinesis,ses,lambda
    - DEBUG=${DEBUG- } #...
    - DATA_DIR=${DATA_DIR- } # Local directory for saving persistent data: disabled by default
    - LAMBDA_EXECUTOR=docker
    - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- } # Not relevant
    - DOCKER_HOST=unix:///var/run/docker.sock # Where localstack can find Docker daemon
    - HOSTNAME_EXTERNAL=localstack
    - DATA_DIR=/tmp/localstack/data
    volumes:
    - ./localstack-persistence:/tmp/localstack/data
    - /var/run/docker.sock:/var/run/docker.sock
```

and a simple code that creates queue and dead letter queue and asks for attributes
```
    public static void main(String[] args)
    {
        String src_queue_name = "dev-adapterqueue";
        String dl_queue_name = "dev-adapterqueue-dlq";

        final AmazonSQS sqs = AmazonSQSClientBuilder.standard()
        .withEndpointConfiguration(new EndpointConfiguration("http://localstack:4576", "us-east-1"))
        .build();

        try {
            sqs.createQueue(src_queue_name);
        } catch (AmazonSQSException e) {
            if (!e.getErrorCode().equals("QueueAlreadyExists")) {
                throw e;
            }
        }
        System.out.println("q created: " + src_queue_name);

        // Create dead-letter queue
        try {
            sqs.createQueue(dl_queue_name);
        } catch (AmazonSQSException e) {
            if (!e.getErrorCode().equals("QueueAlreadyExists")) {
                throw e;
            }
        }
        System.out.println("q created: " + dl_queue_name);

        // Get dead-letter queue ARN
        String dl_queue_url = sqs.getQueueUrl(dl_queue_name)
                                 .getQueueUrl();

        GetQueueAttributesResult queue_attrs = sqs.getQueueAttributes(
                new GetQueueAttributesRequest(dl_queue_url)
                    .withAttributeNames("QueueArn"));

        System.out.println("dl qrn: " + queue_attrs.toString());
        String dl_queue_arn = queue_attrs.getAttributes().get("QueueArn");

        // Set dead letter queue with redrive policy on source queue.
        String src_queue_url = sqs.getQueueUrl(src_queue_name).getQueueUrl();
        System.out.println("q url: " + src_queue_url);

        SetQueueAttributesRequest request = new SetQueueAttributesRequest()
                .withQueueUrl(src_queue_url)
                .addAttributesEntry("RedrivePolicy",
                        "{\"maxReceiveCount\":\"5\", \"deadLetterTargetArn\":\""
                        + dl_queue_arn + "\"}")
                .addAttributesEntry("MessageRetentionPeriod", "345600")
                .addAttributesEntry("VisibilityTimeout", "30");

        sqs.setQueueAttributes(request);
        System.out.println("q url: " + src_queue_url + "  attributes set");

        GetQueueAttributesResult result = sqs
            .getQueueAttributes(new GetQueueAttributesRequest(dl_queue_url).withAttributeNames("RedrivePolicy"));
        System.out.printf(dl_queue_url + " redrivePolicy: " + result.toString());


        src_queue_url = sqs.getQueueUrl(src_queue_name).getQueueUrl();
        System.out.printf("queueUrl: " + src_queue_url);

        result = sqs
            .getQueueAttributes(new GetQueueAttributesRequest(src_queue_url).withAttributeNames("RedrivePolicy"));
        System.out.printf(src_queue_url + " redrivePolicy: " + result.toString());

    }

```

and at the last call, localstack returns
```

<GetQueueAttributesResponse xmlns="http://queue.amazonaws.com/doc/2012-11-05/">
            <GetQueueAttributesResult>
              <Attribute>
          <Name>RedrivePolicy</Name>
          <Value>{&quot;deadLetterTargetArn&quot;:&quot;arn:aws:sqs:elasticmq:000000000000:dev-adapterqueue-dlq&quot;,&quot;maxReceiveCount&quot;:5}</Value>
        </Attribute>
            <Attribute><Name>RedrivePolicy</Name><Value>{"maxReceiveCount":"5", "deadLetterTargetArn":"arn:aws:sqs:us-east-1:000000000000:dev-adapterqueue-dlq"}</Value></Attribute><Attribute><Name>MessageRetentionPeriod</Name><Value>345600</Value></Attribute></GetQueueAttributesResult>
            <ResponseMetadata>
              <RequestId>00000000-0000-0000-0000-000000000000</RequestId>
            </ResponseMetadata>
          </GetQueueAttributesResponse>

```
message is strangely formatted and we have 2 RedrivePolicy attributes, that crashes AmazonSQSClient.
```
Caused by: java.lang.IllegalArgumentException: Duplicated keys (RedrivePolicy) are provided.
	at com.amazonaws.services.sqs.model.GetQueueAttributesResult.addAttributesEntry(GetQueueAttributesResult.java:84)

```
 what's that arn:aws:sqs:**elasticmq**:000000000000:dev-adapterqueue-dlq  ?

**Comment by mac9416** [comment]
Also seeing this with 0.10.7 but not 0.10.4.

**Comment by kamilwrobel** [comment]
Also I'm facing this problem.

**Comment by romanpena** [comment]
Facing the same problem too

**Comment by wee4** [comment]
Same problem here.

**Comment by duberton** [comment]
Facing the same issue

**Comment by whummer** [comment]
Thanks for reporting @razorree  @mac9416 @kamilwrobel @romanpena @wee4 @duberton . It seems that this issue should be fixed in the `latest` version on the master branch - a simple integration test has been added here: https://github.com/localstack/localstack-java-utils/pull/8 Can you please do a `docker pull localstack/localstack` and double-check whether this exact issue persists? Thanks

**Comment by andreacomo** [comment]
Still facing same issue: I tried `latest` and `0.11.2`. I'm back to `0.10.4` to make it works

**Comment by ryanskow** [comment]
It appears the problem still exists when the attributes are set on the CreateQueueRequest itself.  The following test based of the one added above exposes the issue:
`    @Test
    public void testGetQueueRedrivePolicyWhenSetOnCreateQueueRequest() {
        String srcQueueName = "adapter-queue2";
        String dlQueueName = "adapter-queue-dlq2";

        final AmazonSQS clientSQS = sqs;
        final String dlQueueUrl = clientSQS.createQueue(dlQueueName).getQueueUrl();
        GetQueueAttributesResult dlQueueAttrs = clientSQS.getQueueAttributes(
                new GetQueueAttributesRequest(dlQueueUrl).withAttributeNames("QueueArn")
        );
        String dlQueueArn = dlQueueAttrs.getAttributes().get("QueueArn");

        final String redrivePolicy = "{\"maxReceiveCount\": 5, \"deadLetterTargetArn\": \"" + dlQueueArn + "\"}";

        CreateQueueRequest request = new CreateQueueRequest(srcQueueName);
        request.addAttributesEntry("RedrivePolicy", redrivePolicy);
        request.addAttributesEntry("MessageRetentionPeriod", "345600");
        request.addAttributesEntry("VisibilityTimeout", "30");
        request.addAttributesEntry(QueueAttributeName.DelaySeconds.toString(), "10");
        final String srcQueueUrl = clientSQS.createQueue(request).getQueueUrl();

        GetQueueAttributesResult result = clientSQS.getQueueAttributes(new GetQueueAttributesRequest(dlQueueUrl).withAttributeNames("RedrivePolicy"));
        assertTrue(result.getAttributes().isEmpty());

        result = clientSQS.getQueueAttributes(new GetQueueAttributesRequest(srcQueueUrl).withAttributeNames("RedrivePolicy"));
        assertEquals(result.getAttributes().size(), 1);
        assertEquals(result.getAttributes().get("RedrivePolicy"), redrivePolicy);
    }`
