### ISSUE TITLE
1st time localstack start error

### ISSUE THREAD

**Issue by hutualive** [localstack/localstack#213]
Hi, anyone has similiar error for the 1st time "localstack start" after installation ?

I'm on Mac 10.12.5. all the dependencies installed and pip install localstack also successfully.

but seems some zip files missing from the installation...

below is the error message from the terminal ->

$localstack start
Starting local dev environment. CTRL-C to quit.
ERROR: 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip': [es.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of es.zip or
        es.zip.zip, and cannot find es.zip.ZIP, period.

Error starting infrastructure: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/localstack", line 79, in <module>
    infra.start_infra()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/infra.py", line 362, in start_infra
    raise e
subprocess32.CalledProcessError: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9 

thanks.

**Comment by nogamincho** [comment]
I faced the same problem.

If you don't need to use elasticsearch, can you try the way as below?

I commented out 5 lines of plugins.py.
In your environment, probably you can find the file in a directory of "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/".

```python
def register_localstack_plugins():
    try:
#        register_plugin(Plugin('es',
#            start=start_elasticsearch_service))
#        register_plugin(Plugin('elasticsearch',
#            start=es_starter.start_elasticsearch,
#            check=es_starter.check_elasticsearch))                                                                                          
```

Then, I started LocalStack without elasticsearch successfully.
```
$ localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
Starting mock SQS (http port 4576)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock Lambda service (http port 4574)...
Ready.
```

**Comment by whummer** [comment]
Thanks for reporting @hutualive @nogamincho . I'd be keen to understand why the installation/startup failed. If this problem is reproducible and affects multiple users, it needs to be fixed asap.

Can you please post the output of the following:
```
ls -la /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
```
To fix the problem, can you please try to do:
```
mv /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.old.zip
localstack start
```
Thanks

**Comment by hutualive** [comment]
@nogamincho after commented the 5 lines in pugins.py for elasticsearch and localstack start, still report the same error message as before.

@whummer the out of "ls -la /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip" is as below:

-->

-rw-r--r--  1 bd  staff  1159168  7 31 13:07 /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip

after "mv /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.old.zip" and 
localstack start

the terminal stucked and showing:

-->

Starting local dev environment. CTRL-C to quit.

I can't quit through "CTRL-C" and need close the terminal to kill.

re-open the terminal and "localstack start", report the error message as below:

-->

Starting local dev environment. CTRL-C to quit.
ERROR: 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip': [es.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of es.zip or
        es.zip.zip, and cannot find es.zip.ZIP, period.

Error starting infrastructure: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/localstack", line 79, in <module>
    infra.start_infra()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/infra.py", line 362, in start_infra
    raise e
subprocess32.CalledProcessError: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9

btw: I already un-comment the 5 lines regarding elasticsearch as suggested by @nogamincho, tested event it's commented of those 5 lines, it's not working.

**Comment by whummer** [comment]
@vfangellation also ran into this issue on a fresh install of version 0.7.3: #221

**Comment by whummer** [comment]
@hutualive A new version has been released recently, can you please try the following:
```
mv /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.old.zip
pip install --no-cache --upgrade localstack
localstack start
```

Please note that the initialization might take a relatively long amount of time on the first run (up to 1-2 minutes, depending on your Internet connectivity).

Once it is done downloading/installing, you should see a bunch of output lines starting with `Starting mock ...`. Can you please give that a try and report back. Thanks for your patience

**Comment by hutualive** [comment]
@whummer 
upgrade to 0.7.3 as your comments successfully but still the same error.
localstack start will stuck and need kill the terminal.
re-open the terminal and localstack start again, the error message as below:
-->
Starting local dev environment. CTRL-C to quit.
ERROR: 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip': [es.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of es.zip or
        es.zip.zip, and cannot find es.zip.ZIP, period.

Error starting infrastructure: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/localstack", line 86, in <module>
    infra.start_infra()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/infra.py", line 366, in start_infra
    raise e
subprocess32.CalledProcessError: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9

**Comment by whummer** [comment]
@hutualive This error is hard to debug (because it cannot be reproduced on all machines), but the current suspicion is that it may be related to an issue with file downloading and buffering in the python `requests` library. A new version has been released which forces flushing to the disk when the file is downloaded. This may (hopefully) fix the problem. Can you please give it another try with version `0.7.4`:
```
mv /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.old.zip
pip install --no-cache --upgrade localstack
localstack start
```

**Comment by hutualive** [comment]
@whummer tried, still the same error message. very strange errors. 

using docker it's working properly...

thanks a lot for your help anyway. 

-->
ERROR: 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip': [es.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of es.zip or
        es.zip.zip, and cannot find es.zip.ZIP, period.

Error starting infrastructure: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9 Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/infra.py", line 434, in start_infra
    install.install_components(apis)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/install.py", line 124, in install_components
    parallelize(install_component, names)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/utils/common.py", line 646, in parallelize
    result = pool.map(func, list)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
CalledProcessError: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9

ERROR: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9

**Comment by whummer** [comment]
@hutualive  Thanks for your patience in debugging this. We have released another change and believe that this should be fixed now. Can you please give it one more try with the same three commands as posted in my previous message. Thanks

**Comment by hutualive** [comment]
@whummer tried again, still the same error:

-->
Starting local dev environment. CTRL-C to quit.
ERROR: 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip': [es.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of es.zip or
        es.zip.zip, and cannot find es.zip.ZIP, period.

Error starting infrastructure: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9 Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/infra.py", line 434, in start_infra
    install.install_components(apis)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/install.py", line 124, in install_components
    parallelize(install_component, names)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/utils/common.py", line 650, in parallelize
    result = pool.map(func, list)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
CalledProcessError: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9

ERROR: Command 'cd /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra && cp /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip es.zip && unzip -q es.zip && mv elasticsearch* elasticsearch && rm es.zip' returned non-zero exit status 9

**Comment by whummer** [comment]
Thanks @hutualive . What's the output of this:
```
localstack --version
ls -la /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
ls -la /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.old.zip
ls -la /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra 
```

**Comment by hutualive** [comment]
@whummer 

$localstack --version  --> 0.7.4.1

$ls -la /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip  --> -rw-r--r--  1 bd  staff  1355776  8 15 10:31 /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip

$ls -la /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.old.zip --> -rw-r--r--  1 bd  staff  28651520  8 14 23:55 /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.old.zip

$ls -la /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra --> total 2648
drwxr-xr-x   4 bd  admin      136  7 28 21:43 .
drwxr-xr-x  17 bd  admin      578  8 15 10:24 ..
drwxr-xr-x   2 bd  admin       68  7 28 21:31 dynamodb
-rw-r--r--   1 bd  admin  1355776  8 15 10:32 es.zip

**Comment by whummer** [comment]
Thanks again @hutualive . We've made some more updates and added more verbose debug logging.
Can you please try again using the following commands. That will hopefully help us nail down this issue!
```
mv /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.old.zip
pip install --no-cache --upgrade localstack
DEBUG=1 localstack start
```

**Comment by hutualive** [comment]
@whummer 
approaching...a big step ahead
now stucked here : ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a1e3190>: Failed to establish a new connection: [Errno 61] Connection refused',))

-->
DEBUG=1 localstack start
Starting local dev environment. CTRL-C to quit.
2017-08-16T11:12:26:INFO:localstack.services.install: Downloading and installing local Elasticsearch server. This may take some time.
2017-08-16T11:12:29:DEBUG:localstack.utils.common: Starting download from https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.0.zip to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip (33715860 bytes)
2017-08-16T11:12:48:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 1048576) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:13:06:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 2097152) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:13:20:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 3145728) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:13:36:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 4194304) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:13:45:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 5242880) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:13:55:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 6291456) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:14:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 7340032) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:14:14:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 8388608) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:14:24:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 9437184) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:14:35:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 10485760) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:14:44:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 11534336) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:14:51:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 12582912) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:15:13:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 13631488) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:15:45:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 14680064) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:16:03:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 15728640) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:16:18:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 16777216) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:16:35:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 17825792) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:17:09:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 18874368) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:17:27:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 19922944) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:17:37:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 20971520) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:17:44:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 22020096) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:18:00:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 23068672) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:18:21:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 24117248) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:18:31:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 25165824) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:18:43:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 26214400) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:18:51:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 27262976) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:19:07:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 28311552) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:19:27:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 29360128) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:19:50:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 30408704) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:20:20:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 31457280) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:20:42:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 32505856) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:20:51:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 33554432) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:20:52:DEBUG:localstack.utils.common: Writing 161428 bytes (total 33715860) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.es.zip
2017-08-16T11:20:52:DEBUG:localstack.utils.common: Done downloading https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.3.0.zip, response code 200
2017-08-16T11:20:54:DEBUG:localstack.utils.common: Starting download from http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-sts/1.11.14/aws-java-sdk-sts-1.11.14.jar to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/aws-java-sdk-sts.jar (170611 bytes)
2017-08-16T11:20:56:DEBUG:localstack.utils.common: Writing 170611 bytes (total 170611) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/aws-java-sdk-sts.jar
2017-08-16T11:20:56:DEBUG:localstack.utils.common: Done downloading http://central.maven.org/maven2/com/amazonaws/aws-java-sdk-sts/1.11.14/aws-java-sdk-sts-1.11.14.jar, response code 200
2017-08-16T11:24:55:DEBUG:localstack.utils.common: Starting download from http://central.maven.org/maven2/cloud/localstack/localstack-utils/0.1.3/localstack-utils-0.1.3-fat.jar to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra/localstack-utils-fat.jar (5389268 bytes)
2017-08-16T11:25:01:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 1048576) to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra/localstack-utils-fat.jar
2017-08-16T11:25:07:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 2097152) to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra/localstack-utils-fat.jar
2017-08-16T11:25:14:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 3145728) to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra/localstack-utils-fat.jar
2017-08-16T11:25:21:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 4194304) to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra/localstack-utils-fat.jar
2017-08-16T11:25:27:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 5242880) to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra/localstack-utils-fat.jar
2017-08-16T11:25:30:DEBUG:localstack.utils.common: Writing 146388 bytes (total 5389268) to /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra/localstack-utils-fat.jar
2017-08-16T11:25:30:DEBUG:localstack.utils.common: Done downloading http://central.maven.org/maven2/cloud/localstack/localstack-utils/0.1.3/localstack-utils-0.1.3-fat.jar, response code 200
Starting mock API Gateway (http port 4567)...
Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Error: Unable to access jarfile DynamoDBLocal.jar
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
* Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4561/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4577/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
Listening at http://:::4565
* Running on http://0.0.0.0:4580/ (Press CTRL+C to quit)
[2017-08-16T11:25:32,326][INFO ][o.e.n.Node               ] [] initializing ...
[2017-08-16T11:25:32,406][INFO ][o.e.e.NodeEnvironment    ] [eZU7SFK] using [1] data paths, mounts [[/ (/dev/disk0s2)]], net usable_space [21.7gb], net total_space [116.5gb], spins? [unknown], types [hfs]
[2017-08-16T11:25:32,406][INFO ][o.e.e.NodeEnvironment    ] [eZU7SFK] heap size [483.3mb], compressed ordinary object pointers [true]
[2017-08-16T11:25:32,408][INFO ][o.e.n.Node               ] node name [eZU7SFK] derived from node ID [eZU7SFKMQWW4Pq4J6DP30g]; set [node.name] to override
[2017-08-16T11:25:32,408][INFO ][o.e.n.Node               ] version[5.3.0], pid[25134], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Mac OS X/10.12.5/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-08-16T11:25:33,189][INFO ][o.e.p.PluginsService     ] [eZU7SFK] loaded module [aggs-matrix-stats]
[2017-08-16T11:25:33,190][INFO ][o.e.p.PluginsService     ] [eZU7SFK] loaded module [ingest-common]
[2017-08-16T11:25:33,190][INFO ][o.e.p.PluginsService     ] [eZU7SFK] loaded module [lang-expression]
[2017-08-16T11:25:33,190][INFO ][o.e.p.PluginsService     ] [eZU7SFK] loaded module [lang-groovy]
[2017-08-16T11:25:33,190][INFO ][o.e.p.PluginsService     ] [eZU7SFK] loaded module [lang-mustache]
[2017-08-16T11:25:33,190][INFO ][o.e.p.PluginsService     ] [eZU7SFK] loaded module [lang-painless]
[2017-08-16T11:25:33,190][INFO ][o.e.p.PluginsService     ] [eZU7SFK] loaded module [percolator]
[2017-08-16T11:25:33,191][INFO ][o.e.p.PluginsService     ] [eZU7SFK] loaded module [reindex]
[2017-08-16T11:25:33,191][INFO ][o.e.p.PluginsService     ] [eZU7SFK] loaded module [transport-netty3]
[2017-08-16T11:25:33,191][INFO ][o.e.p.PluginsService     ] [eZU7SFK] loaded module [transport-netty4]
[2017-08-16T11:25:33,192][INFO ][o.e.p.PluginsService     ] [eZU7SFK] no plugins loaded
[2017-08-16T11:25:34,887][INFO ][o.e.n.Node               ] initialized
[2017-08-16T11:25:34,888][INFO ][o.e.n.Node               ] [eZU7SFK] starting ...
[2017-08-16T11:25:35,039][INFO ][o.e.t.TransportService   ] [eZU7SFK] publish_address {127.0.0.1:9300}, bound_addresses {[fe80::1]:9300}, {[::1]:9300}, {127.0.0.1:9300}
[2017-08-16T11:25:35,045][WARN ][o.e.b.BootstrapChecks    ] [eZU7SFK] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2017-08-16T11:25:38,095][INFO ][o.e.c.s.ClusterService   ] [eZU7SFK] new_master {eZU7SFK}{eZU7SFKMQWW4Pq4J6DP30g}{Y_s9IjuLQjCrT1uzSv9VCA}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-08-16T11:25:38,115][INFO ][o.e.h.n.Netty4HttpServerTransport] [eZU7SFK] publish_address {127.0.0.1:4560}, bound_addresses {[fe80::1]:4560}, {[::1]:4560}, {127.0.0.1:4560}
[2017-08-16T11:25:38,118][INFO ][o.e.n.Node               ] [eZU7SFK] started
[2017-08-16T11:25:38,120][INFO ][o.e.g.GatewayService     ] [eZU7SFK] recovered [0] indices into cluster_state
127.0.0.1 - - [16/Aug/2017 11:25:38] "GET / HTTP/1.1" 200 -
2017-08-16T11:25:38:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a295590>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a295590>: Failed to establish a new connection: [Errno 61] Connection refused',))

2017-08-16T11:26:38:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3acc10>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3acc10>: Failed to establish a new connection: [Errno 61] Connection refused',))

2017-08-16T11:27:39:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3ace10>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3ace10>: Failed to establish a new connection: [Errno 61] Connection refused',))

2017-08-16T11:28:39:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3be050>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3be050>: Failed to establish a new connection: [Errno 61] Connection refused',))

2017-08-16T11:29:39:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3be250>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3be250>: Failed to establish a new connection: [Errno 61] Connection refused',))

2017-08-16T11:30:40:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3be450>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3be450>: Failed to establish a new connection: [Errno 61] Connection refused',))

2017-08-16T11:31:42:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3be650>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3be650>: Failed to establish a new connection: [Errno 61] Connection refused',))

2017-08-16T11:32:45:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3be850>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3be850>: Failed to establish a new connection: [Errno 61] Connection refused',))

2017-08-16T11:33:51:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3ace50>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a3ace50>: Failed to establish a new connection: [Errno 61] Connection refused',))

2017-08-16T11:35:04:ERROR:localstack.services.generic_proxy: Error forwarding request: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a1e3190>: Failed to establish a new connection: [Errno 61] Connection refused',)) Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 185, in forward
    headers=forward_headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=4564): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10a1e3190>: Failed to establish a new connection: [Errno 61] Connection refused',))

^C[2017-08-16T11:35:23,568][INFO ][o.e.n.Node               ] [eZU7SFK] stopping ...
[2017-08-16T11:35:23,643][INFO ][o.e.n.Node               ] [eZU7SFK] stopped
[2017-08-16T11:35:23,643][INFO ][o.e.n.Node               ] [eZU7SFK] closing ...
[2017-08-16T11:35:23,652][INFO ][o.e.n.Node               ] [eZU7SFK] closed

**Comment by whummer** [comment]
Awesome. That new error might actually be a left over from a previous error. Try this please:
```
rm -f /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
rm -rf /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/localstack/infra/dynamodb/
DEBUG=1 localstack start
```

**Comment by hutualive** [comment]
@whummer 👍 🥇 
it's working : 
--> 
localstack start
Starting local dev environment. CTRL-C to quit.
Starting mock API Gateway (http port 4567)...
Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Ready.

-->
DEBUG=1 localstack start
Starting local dev environment. CTRL-C to quit.
2017-08-16T19:04:52:INFO:localstack.services.install: Downloading and installing local DynamoDB server. This may take some time.
2017-08-16T19:04:56:DEBUG:localstack.utils.common: Starting download from https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip (17041572 bytes)
2017-08-16T19:05:03:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 1048576) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:05:18:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 2097152) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:05:47:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 3145728) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:06:03:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 4194304) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:06:32:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 5242880) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:06:43:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 6291456) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:06:58:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 7340032) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:07:08:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 8388608) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:07:18:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 9437184) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:07:33:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 10485760) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:07:39:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 11534336) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:07:41:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 12582912) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:07:44:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 13631488) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:07:48:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 14680064) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:07:53:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 15728640) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:08:03:DEBUG:localstack.utils.common: Writing 1048576 bytes (total 16777216) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:08:09:DEBUG:localstack.utils.common: Writing 264356 bytes (total 17041572) to /var/folders/5n/67lx6b_564910qvcxxs9_pyh0000gn/T/localstack.ddb.zip
2017-08-16T19:08:09:DEBUG:localstack.utils.common: Done downloading https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.zip, response code 200
Starting mock API Gateway (http port 4567)...
Starting mock CloudWatch (http port 4582)...
Starting mock SES (http port 4579)...
Starting mock Kinesis (http port 4568)...
Starting mock Redshift (http port 4577)...
Starting mock S3 (http port 4572)...
Starting mock CloudFormation (http port 4581)...
Starting mock DynamoDB (http port 4569)...
Starting mock SQS (http port 4576)...
Starting local Elasticsearch (http port 4571)...
Starting mock SNS (http port 4575)...
Starting mock DynamoDB Streams service (http port 4570)...
Starting mock Firehose service (http port 4573)...
Starting mock Route53 (http port 4580)...
Starting mock ES service (http port 4578)...
Starting mock Lambda service (http port 4574)...
Initializing DynamoDB Local with the following configuration:
Port:   4564
InMemory:       true
DbPath: null
SharedDb:       true
shouldDelayTransientStatuses:   false
CorsParams:     *

Listening at http://:::4565
* Running on http://0.0.0.0:4582/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4563/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4559/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4577/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4566/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4561/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4562/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4580/ (Press CTRL+C to quit)
* Running on http://0.0.0.0:4579/ (Press CTRL+C to quit)
[2017-08-16T19:08:12,374][INFO ][o.e.n.Node               ] [] initializing ...
[2017-08-16T19:08:12,466][INFO ][o.e.e.NodeEnvironment    ] [5BWZdSC] using [1] data paths, mounts [[/ (/dev/disk0s2)]], net usable_space [37gb], net total_space [116.5gb], spins? [unknown], types [hfs]
[2017-08-16T19:08:12,467][INFO ][o.e.e.NodeEnvironment    ] [5BWZdSC] heap size [483.3mb], compressed ordinary object pointers [true]
[2017-08-16T19:08:12,469][INFO ][o.e.n.Node               ] node name [5BWZdSC] derived from node ID [5BWZdSC4Tzahip2M71ohbA]; set [node.name] to override
[2017-08-16T19:08:12,469][INFO ][o.e.n.Node               ] version[5.3.0], pid[28630], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Mac OS X/10.12.5/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_131/25.131-b11]
[2017-08-16T19:08:13,355][INFO ][o.e.p.PluginsService     ] [5BWZdSC] loaded module [aggs-matrix-stats]
[2017-08-16T19:08:13,355][INFO ][o.e.p.PluginsService     ] [5BWZdSC] loaded module [ingest-common]
[2017-08-16T19:08:13,355][INFO ][o.e.p.PluginsService     ] [5BWZdSC] loaded module [lang-expression]
[2017-08-16T19:08:13,355][INFO ][o.e.p.PluginsService     ] [5BWZdSC] loaded module [lang-groovy]
[2017-08-16T19:08:13,355][INFO ][o.e.p.PluginsService     ] [5BWZdSC] loaded module [lang-mustache]
[2017-08-16T19:08:13,355][INFO ][o.e.p.PluginsService     ] [5BWZdSC] loaded module [lang-painless]
[2017-08-16T19:08:13,355][INFO ][o.e.p.PluginsService     ] [5BWZdSC] loaded module [percolator]
[2017-08-16T19:08:13,356][INFO ][o.e.p.PluginsService     ] [5BWZdSC] loaded module [reindex]
[2017-08-16T19:08:13,356][INFO ][o.e.p.PluginsService     ] [5BWZdSC] loaded module [transport-netty3]
[2017-08-16T19:08:13,356][INFO ][o.e.p.PluginsService     ] [5BWZdSC] loaded module [transport-netty4]
[2017-08-16T19:08:13,356][INFO ][o.e.p.PluginsService     ] [5BWZdSC] no plugins loaded
[2017-08-16T19:08:15,441][INFO ][o.e.n.Node               ] initialized
[2017-08-16T19:08:15,441][INFO ][o.e.n.Node               ] [5BWZdSC] starting ...
[2017-08-16T19:08:15,647][INFO ][o.e.t.TransportService   ] [5BWZdSC] publish_address {127.0.0.1:9300}, bound_addresses {[fe80::1]:9300}, {[::1]:9300}, {127.0.0.1:9300}
[2017-08-16T19:08:15,654][WARN ][o.e.b.BootstrapChecks    ] [5BWZdSC] initial heap size [209715200] not equal to maximum heap size [524288000]; this can cause resize pauses and prevents mlockall from locking the entire heap
[2017-08-16T19:08:18,702][INFO ][o.e.c.s.ClusterService   ] [5BWZdSC] new_master {5BWZdSC}{5BWZdSC4Tzahip2M71ohbA}{fSB93ojDTBG6WhAMMnAcUw}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-08-16T19:08:18,722][INFO ][o.e.h.n.Netty4HttpServerTransport] [5BWZdSC] publish_address {127.0.0.1:4560}, bound_addresses {[fe80::1]:4560}, {[::1]:4560}, {127.0.0.1:4560}
[2017-08-16T19:08:18,725][INFO ][o.e.n.Node               ] [5BWZdSC] started
[2017-08-16T19:08:18,727][INFO ][o.e.g.GatewayService     ] [5BWZdSC] recovered [0] indices into cluster_state
127.0.0.1 - - [16/Aug/2017 19:08:18] "GET / HTTP/1.1" 200 -
Ready.
