### ISSUE TITLE
Edge Router doesn't handle S3 Presigned URL POSTs properly

### ISSUE THREAD

**Issue by matthewarmand** [localstack/localstack#2464]
# Bug Report

# Detailed description
This is a similar issue to #2329, specific to [S3 Presigned URLs](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-presigned-urls.html). Using the edge router port (`:4566`), it is possible to use `generate_presigned_post`, but attempting to use the resultant URL to upload a file to localstack's S3 fails with a 404.

## Expected behavior
Localstack's edge router port should accept POST requests with an S3 Presigned URL (generated from that same Localstack instance) in the same way that the old S3 port (`:4572`) does.

## Actual behavior
While the old S3 port (`:4572`) handles this fine, the edge router responds with a 404 and a message similar to the following:

```
2020-05-24T15:36:54:INFO:localstack.services.edge: Unable to find forwarding rule for host "localhost:4566", path "/local-job-documents", target header "", auth header ""
```

(borrowed from @philippmalkov's comment on #2329 )

```
aws_1  | 2020-05-27T16:24:38:INFO:localstack.services.edge: Unable to find forwarding rule for host "aws:4566", path "/test-bucket", target header "", auth header ""
```

(our observed case with the below setup)

# Steps to reproduce

## Command used to start LocalStack
```
# Used in docker-compose.yml as:
  aws:
    image: localstack/localstack-light
    environment:
      - SERVICES=dynamodb,s3
      - HOSTNAME_EXTERNAL=aws
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    expose:
      - 4566
      - 4572
    volumes:
      - ./.localstack:/tmp/localstack
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Client code is a Django app using `boto3` to generate a Presigned URL and then upload a file to it using `requests`, effectively identical to the examples in [the boto3 docs](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/s3-presigned-urls.html)

**Comment by mcintyre94** [comment]
@matthewarmand I think the fix for https://github.com/localstack/localstack/issues/2442 should have fixed this - in my testing presigned URLs work correctly on `localhost:4566` now. This now works for me:

```
$ echo "hello" > test.txt
$ alias awslocal="aws --endpoint-url http://localhost:4566"
$ awslocal s3 mb s3://testbucket
$ url=$(awslocal s3 presign s3://testbucket/test.txt)
$ curl --upload-file test.txt $url
$ awslocal s3 ls s3://testbucket
2020-06-01 10:38:58          6 test.txt
```

It'd be worth re-testing your app with the newest version :)

**Comment by matthewarmand** [comment]
@mcintyre94 Thanks for the response and the fix, I noticed that did fix some things, in particular the `PUT` case. However I'm still noticing a bit of weirdness with the `POST` on the edge router.

I've put together a [small Django app](https://github.com/matthewarmand/localstack-2464-example) which illustrates the issue I'm seeing. Anyone should be able to clone that repo and use `docker-compose` to run it locally pretty easily using the instructions in the `README.md`.

It's entirely possible some piece of config is incorrect or I'm missing a parameter or setting, so please let me know if that's the case. But it seems to be that the `POST` functionality is still not quite right on the edge router... Using pretty much the same test case I get successful results POSTing to `4572` and live S3, but still not `4566`.

I've done my best to document that test app so its easy to use and reproduce, let me know if further explanation or context is needed, or if any improvement could be made to make the debugging process easier.

**Comment by matthewarmand** [comment]
Also out of curiosity, is there an issue or some documentation you can point me to on the rationalization for building the edge router functionality rather than using dedicated ports for each service? For a container whose purpose is to mock AWS services as faithfully as possible, it feels a bit like it adds more complexity and/or room for error than it might be worth, considering AWS services in the wild all live at different URLs / ports anyway.

**Comment by mcintyre94** [comment]
@matthewarmand Nice repro, I get the same issue - fails on post 4566 only and everything else works. Apologies - I assumed it was fixed because the minimal CLI repro started working, think you've shown that put is fixed but post isn't yet.

To clarify I'm not a maintainer and don't have any special insight, I only commented here because it looked like a dupe of an issue I thought was fixed and I was hoping your issue had been fixed :) I will say that I like the edge port because I do a lot of my experimenting/prototyping in the AWS CLI and being able to just do `alias awslocal="aws --endpoint-url=http://localhost:4566"` and then use any service by just swapping `aws` for `awslocal` is much easier than having to look up the ports for every individual service. It's also nice when I need to talk to multiple AWS services to just use the same endpoint URL for all of them.

FWIW there's this issue where it was initially proposed - https://github.com/localstack/localstack/issues/151

**Comment by matthewarmand** [comment]
>I only commented here because it looked like a dupe of an issue I thought was fixed and I was hoping your issue had been fixed

I agree that it was definitely related, and was completely reasonable to think it would be fixed, so I appreciate the input. Looks like there's still an issue on the `POST` side (or potentially how I'm trying to use it), so hopefully that can be resolved.

Thanks for the extra context on the edge port too, seeing the original issue is helpful as well. It still seems to me like it should be treated more as convenience than the main workflow, ie the service-specific ports should still be kept around if possible, since its such a divergence from what the container is trying to replicate; but that's just my $0.02 :)

**Comment by mcintyre94** [comment]
Hey @matthewarmand I think I now have a fix for this - tested your repro locally and it passes now. If you have some time it'd be helpful if you could double check it :)

Steps:
- Clone my fork: https://github.com/mcintyre94/localstack/tree/fix-s3-post-edge-port
- Check out branch `fix-s3-post-edge-port`
- Edit the Dockerfile, comment out everything from "# run tests (to verify the build before pushing the image)" (just to save you some time!)
- Build + tag: `docker build . -t localstack/localstack-light` (same tag your repro used)

Then run your PoC and if possible your real app with that version of localstack just to verify everything works for you there.
