### ISSUE TITLE
S3 universal port 4566 does not allow to download file with SDK

### ISSUE THREAD

**Issue by bmitmanski** [localstack/localstack#2582]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description

Using node.js AWS SDK function `getObject` returns object with `0` bytes using 4566 port. 
On port 4572 it works fine.

# Steps to reproduce

## Command used to start LocalStack

```
  localstack:
    image: localstack/localstack
    networks:
      - localstack-network
    ports:
      - 4566:4566
      - 4572:4572
      - 8080:8080
    environment:
      - DEBUG=1
      - HOSTNAME_EXTERNAL=localstack
      - SERVICES=sqs,lambda,cloudwatch,s3,iam,ec2,stepfunctions,cloudwatchlogs
      - LAMBDA_REMOTE_DOCKER=false
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_DOCKER_NETWORK=localstack-network
      - AWS_ACCESS_KEY_ID=123
      - AWS_SECRET_ACCESS_KEY=xyz
      - DEFAULT_REGION=us-east-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/localstack:/tmp/localstack
```

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
export const s3 = new AWS.S3({
  endpoint: `http://localhost:4566`,
  s3ForcePathStyle: true,
  sslEnabled: false
});

const { Body } = await s3.getObject({
 Bucket: 'bucket',
 Key: 'file.json'
}).promise();
```

**Comment by whummer** [comment]
Thanks for reporting @bmitmanski - haven't been able to reproduce this issue, unfortunately. 
```
$ awslocal s3 mb s3://bucket
$ awslocal s3 cp test.json s3://bucket/file.json
$ node index.js
<Buffer 7b 0a 20 20 22 6e 61 ... >
```
Can you please share your version of LocalStack, `node`, the npm packages, etc?
```
$ node -v
v8.16.2
$ cat package.json | grep aws-sdk
    "aws-sdk": "2.700.0"
$ docker images | grep localstack
...
```
Also, can you please post the full logs from the LocalStack container here, to help with debugging this issue. Thanks

**Comment by bmitmanski** [comment]
Node version: 12.18.0
aws-sdk: 2.701.0
I can see an error in the localstack logs:
```
localstack_1        | Error in ASGI Framework
localstack_1        | Traceback (most recent call last):
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/context.py", line 28, in _handle
localstack_1        |     await invoke_asgi(app, scope, receive, send)
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/utils.py", line 219, in invoke_asgi
localstack_1        |     await app(scope, receive, send)
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/app.py", line 2069, in __call__
localstack_1        |     await self.asgi_app(scope, receive, send)
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/app.py", line 2092, in asgi_app
localstack_1        |     await asgi_handler(receive, send)
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/asgi.py", line 31, in __call__
localstack_1        |     _raise_exceptions(done)
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/asgi.py", line 234, in _raise_exceptions
localstack_1        |     raise task.exception()
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/asgi.py", line 79, in handle_request
localstack_1        |     await asyncio.wait_for(self._send_response(send, response), timeout=timeout)
localstack_1        |   File "/usr/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
localstack_1        |     return fut.result()
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/quart/asgi.py", line 94, in _send_response
localstack_1        |     await send({"type": "http.response.body", "body": data, "more_body": True})
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/protocol/http_stream.py", line 147, in app_send
localstack_1        |     await self.send(
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/protocol/h11.py", line 131, in stream_send
localstack_1        |     await self._send_h11_event(h11.Data(data=event.data))
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/protocol/h11.py", line 227, in _send_h11_event
localstack_1        |     data = self.connection.send(event)
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/h11/_connection.py", line 469, in send
localstack_1        |     data_list = self.send_with_data_passthrough(event)
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/h11/_connection.py", line 502, in send_with_data_passthrough
localstack_1        |     writer(event, data_list.append)
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/h11/_writers.py", line 77, in __call__
localstack_1        |     self.send_data(event.data, write)
localstack_1        |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/h11/_writers.py", line 97, in send_data
localstack_1        |     raise LocalProtocolError("Too much data for declared Content-Length")
localstack_1        | h11._util.LocalProtocolError: Too much data for declared Content-Length
```

Using port 4572 there's no such error.

**Comment by whummer** [comment]
Thanks for the update @bmitmanski . Another S3 related fix has been pushed recently (#2600 ) - may I ask you to do another `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? With latest, I've been able to upload and download a very large file (100MB) with the exact JS code snippet you provided.

**Comment by bmitmanski** [comment]
Unfortunately still no luck. The file size is only 632 Bytes. Maybe the headers matter: 
```
CacheControl: 'no-cache',
ContentEncoding: 'gzip',
ContentLanguage: 'en-US',
ContentType: 'application/json; charset=UTF-8'
```

**Comment by whummer** [comment]
Thanks for the follow-up @bmitmanski . May I ask you to provide a small, isolated sample script with the entire end-to-end logic in a single script? This would greatly help us reproduce and fix the isse. Many thanks, really appreciated.

**Comment by bmitmanski** [comment]
The problem is when I provide `ContentEncoding` param to upload:
```
const file = fs.readFileSync('./export.json.gz');

    await s3.putObject({
        Bucket: jetscanLoaderBucket,
        Body: file,
        Key: exportFileName,
        ContentEncoding: 'gzip',
        ContentType: 'application/json; charset=UTF-8'
    }).promise();

    const { Body } = await s3.getObject({
        Bucket: jetscanLoaderBucket,
        Key: exportFileName
    }).promise();
```

I hope that helps.

**Comment by whummer** [comment]
Thanks for the update @bmitmanski , I was able to reproduce this issue with the example you've provided. This should be fixed in #2667 - can you please give it another try with the `latest` version? Hope it should be fixed now - otherwise please let us know. Thanks
