### ISSUE TITLE
[Bug Report] Dashboard Pro does not show resources

### ISSUE THREAD

**Issue by Vaunorage** [localstack/localstack#2676]
## Detailed description
The pro version of the dashboard always shows that there is no resources found... After looking in the requests I see that it does a POST request to 0.0.0.0:4566/graph but without parameters ..

# Normal Darshboard
![image](https://user-images.githubusercontent.com/10731763/86540395-fa4d4900-bed2-11ea-8ea9-855181574318.png)

# Pro Dashboard
![image](https://user-images.githubusercontent.com/10731763/86540408-210b7f80-bed3-11ea-89f1-73c50101edd3.png)

# Steps to reproduce

## Command used to start LocalStack

docker run -it -e LOCALSTACK_HOSTNAME="localhost" -e DEFAULT_REGION="us-east-1" -e TEST_AWS_ACCOUNT_ID="000000000000" -p 4566:4566 --rm --privileged --name localstack_main -p 4567-4620:4567-4620 -p 12121:12121 -p 8080-8081:8080-8081  -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" -e SERVICES="edge,dynamodb,cognito"

**Comment by themandoug** [comment]
I'm having this issue as well on macOS 10.15.5.

It appears to start up fine:

```localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2020-07-06 09:41:08,631 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2020-07-06 09:41:08,635 INFO supervisord started with pid 13
localstack_1  | 2020-07-06 09:41:09,640 INFO spawned: 'dashboard' with pid 19
localstack_1  | 2020-07-06 09:41:09,647 INFO spawned: 'infra' with pid 20
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | 2020-07-06 09:41:09,657 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | 2020-07-06T09:41:10:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7f98a54b24c0>
localstack_1  | LocalStack version: 0.11.3
localstack_1  | 2020-07-06T09:41:10:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f98a5864f70>
localstack_1  | 2020-07-06T09:41:10:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f98a5864d30>
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1  | LocalStack version: 0.11.3
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | 2020-07-06T09:41:10:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7f42a30c84c0>
localstack_1  | 2020-07-06T09:41:10:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f42a347bf70>
localstack_1  | 2020-07-06 09:41:11,312 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | Running on 0.0.0.0:8081 over https (CTRL + C to quit)
localstack_1  | 2020-07-06T09:41:13:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2020-07-06T09:41:17:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f42a347bd30>
localstack_1  | 2020-07-06T09:41:17:DEBUG:bootstrap.py: Plugin loading took 7.517029047012329 sec
localstack_1  | Starting mock Cognito Identity Provider (IdP) service on http ports 443 (recommended) and 4590 (deprecated)...
localstack_1  | Starting mock Cognito Identity service on http ports 443 (recommended) and 4591 (deprecated)...
localstack_1  | Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
localstack_1  | Starting edge router (http port 4566)...
localstack_1  | Starting edge router (https port 443)...
localstack_1  | Starting mock CloudFormation service in http ports 443 (recommended) and 4581 (deprecated)...
localstack_1  | Starting mock Lambda service on http ports 443 (recommended) and 4574 (deprecated)...
localstack_1  | Starting mock CloudWatch Logs service on http ports 443 (recommended) and 4586 (deprecated)...
localstack_1  | 2020-07-06T09:41:19:INFO:localstack.multiserver: Starting multi API server process on port 51657
localstack_1  | Running on 0.0.0.0:4590 over http (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:51657 over http (CTRL + C to quit)
localstack_1  | 2020-07-06 09:41:19,943:API:  * Running on http://0.0.0.0:57681/ (Press CTRL+C to quit)
localstack_1  | 2020-07-06 09:41:19,943:API:  * Running on http://0.0.0.0:57681/ (Press CTRL+C to quit)
localstack_1  | 2020-07-06 09:41:19,943:API:  * Running on http://0.0.0.0:57681/ (Press CTRL+C to quit)
localstack_1  | Running on 0.0.0.0:4591 over http (CTRL + C to quit)
localstack_1  | 2020-07-06 09:41:19,966:API:  * Running on http://0.0.0.0:60399/ (Press CTRL+C to quit)
localstack_1  | 2020-07-06 09:41:19,966:API:  * Running on http://0.0.0.0:60399/ (Press CTRL+C to quit)
localstack_1  | 2020-07-06 09:41:19,966:API:  * Running on http://0.0.0.0:60399/ (Press CTRL+C to quit)
localstack_1  | Running on 0.0.0.0:4566 over https (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:4581 over http (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:443 over https (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:4586 over http (CTRL + C to quit)
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Ready.```

If I go to the portal, I get the same message as above:

![Screenshot 2020-07-06 at 10 43 43](https://user-images.githubusercontent.com/5686125/86579760-a5164380-bf75-11ea-8e75-7da0debb72e3.png)

I then get this in the log:

```localstack_1  | 2020-07-06T09:43:04:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | 2020-07-06T09:43:13:ERROR:asyncio: Task exception was never retrieved
localstack_1  | future: <Task finished name='Task-144' coro=<worker_serve.<locals>._server_callback() done, defined at /opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py:88> exception=SSLError(1, '[SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2730)')>
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 89, in _server_callback
localstack_1  |     await TCPServer(app, loop, config, reader, writer)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 84, in run
localstack_1  |     await self._close()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 129, in _close
localstack_1  |     await self.writer.wait_closed()
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
localstack_1  |     await self._protocol._get_close_waiter(self)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 104, in _read_data
localstack_1  |     data = await self.reader.read(MAX_RECV)
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 684, in read
localstack_1  |     await self._wait_for_data('read')
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
localstack_1  |     await self._waiter
localstack_1  |   File "/usr/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
localstack_1  |     ssldata, appdata = self._sslpipe.feed_ssldata(data)
localstack_1  |   File "/usr/lib/python3.8/asyncio/sslproto.py", line 207, in feed_ssldata
localstack_1  |     self._sslobj.unwrap()
localstack_1  |   File "/usr/lib/python3.8/ssl.py", line 948, in unwrap
localstack_1  |     return self._sslobj.shutdown()
localstack_1  | ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2730)```

If I access the health endpoint from a browser it returns what appears to be a valid response but writes the same log messages as above to the log again:

![Screenshot 2020-07-06 at 10 45 17](https://user-images.githubusercontent.com/5686125/86579938-e73f8500-bf75-11ea-92bd-ce80ea077ca1.png)

I get this using both the `localstack` command and running using `docker-compose`. Here is the compose file:

```version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - "53:53"
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=edge,cognito,lambda,cloudformation
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"```

Here is the Docker info:

```Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:21:11 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683```

**Comment by whummer** [comment]
Thanks for reporting @themandoug @Vaunorage . Can you please try pulling the `latest` version of the Docker image and verify if the problem still persists? It seems that the health check endpoint is up and running properly - can you please also double-check that the correct region is selected in the UI? Thanks for your help in resolving this issue.

**Comment by themandoug** [comment]
Hi @whummer,

If I get the latest version of the image I get the same log messages when I access the endpoint https://localhost.localstack.cloud/health

```
localstack_1  | 2020-07-14T09:05:53:ERROR:asyncio: Task exception was never retrieved
localstack_1  | future: <Task finished name='Task-211' coro=<worker_serve.<locals>._server_callback() done, defined at /opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py:88> exception=SSLError(1, '[SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2730)')>
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 89, in _server_callback
localstack_1  |     await TCPServer(app, loop, config, reader, writer)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 84, in run
localstack_1  |     await self._close()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 129, in _close
localstack_1  |     await self.writer.wait_closed()
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
localstack_1  |     await self._protocol._get_close_waiter(self)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 104, in _read_data
localstack_1  |     data = await self.reader.read(MAX_RECV)
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 684, in read
localstack_1  |     await self._wait_for_data('read')
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
localstack_1  |     await self._waiter
localstack_1  |   File "/usr/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
localstack_1  |     ssldata, appdata = self._sslpipe.feed_ssldata(data)
localstack_1  |   File "/usr/lib/python3.8/asyncio/sslproto.py", line 207, in feed_ssldata
localstack_1  |     self._sslobj.unwrap()
localstack_1  |   File "/usr/lib/python3.8/ssl.py", line 948, in unwrap
localstack_1  |     return self._sslobj.shutdown()
localstack_1  | ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2730)
```

I get this log message every time I access the endpoint directly - I don't need to go near the portal to get it.

I don't know if this is related but when I started the latest image for the first time I did get an SSL error I've not seen before or since:

```
Creating network "arnie-devops_default" with the default driver
Creating arnie-devops_localstack_1 ... done
Attaching to arnie-devops_localstack_1
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2020-07-14 09:00:46,609 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2020-07-14 09:00:46,612 INFO supervisord started with pid 15
localstack_1  | 2020-07-14 09:00:47,619 INFO spawned: 'dashboard' with pid 21
localstack_1  | 2020-07-14 09:00:47,621 INFO spawned: 'infra' with pid 22
localstack_1  | 2020-07-14 09:00:47,625 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | 2020-07-14 09:00:47,626 INFO exited: dashboard (exit status 0; expected)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1  | LocalStack version: 0.11.3
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | 2020-07-14T09:00:48:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7f1206e795e0>
localstack_1  | 2020-07-14T09:00:48:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7f1207235040>
localstack_1  | 2020-07-14T09:00:48:DEBUG:localstack.utils.common: Starting download from https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key to /tmp/localstack/server.test.pem (2659 bytes)
localstack_1  | 2020-07-14T09:00:48:DEBUG:localstack.utils.common: Writing 3643 bytes (total 3643) to /tmp/localstack/server.test.pem
localstack_1  | 2020-07-14T09:00:48:DEBUG:localstack.utils.common: Done downloading https://github.com/localstack/localstack-artifacts/raw/master/local-certs/server.key, response code 200, total bytes 3643
localstack_1  | 2020-07-14 09:00:49,536 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2020-07-14T09:00:51:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2020-07-14T09:00:56:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7f120722cdc0>
localstack_1  | 2020-07-14T09:00:56:DEBUG:bootstrap.py: Plugin loading took 8.191148042678833 sec
localstack_1  | Starting mock Cognito Identity Provider (IdP) service on http ports 443 (recommended) and 4590 (deprecated)...
localstack_1  | Starting mock Cognito Identity service on http ports 443 (recommended) and 4591 (deprecated)...
localstack_1  | Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
localstack_1  | Starting edge router (http port 4566)...
localstack_1  | Starting edge router (https port 443)...
localstack_1  | Starting mock CloudFormation service in http ports 443 (recommended) and 4581 (deprecated)...
localstack_1  | Starting mock Lambda service on http ports 443 (recommended) and 4574 (deprecated)...
localstack_1  | Starting mock CloudWatch Logs service on http ports 443 (recommended) and 4586 (deprecated)...
localstack_1  | 2020-07-14T09:00:58:INFO:localstack.multiserver: Starting multi API server process on port 33595
localstack_1  | Running on 0.0.0.0:4590 over http (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:33595 over http (CTRL + C to quit)
localstack_1  | 2020-07-14 09:00:58,612:API:  * Running on http://0.0.0.0:60467/ (Press CTRL+C to quit)
localstack_1  | 2020-07-14 09:00:58,612:API:  * Running on http://0.0.0.0:60467/ (Press CTRL+C to quit)
localstack_1  | 2020-07-14 09:00:58,612:API:  * Running on http://0.0.0.0:60467/ (Press CTRL+C to quit)
localstack_1  | Running on 0.0.0.0:4591 over http (CTRL + C to quit)
localstack_1  | 2020-07-14 09:00:58,634:API:  * Running on http://0.0.0.0:54145/ (Press CTRL+C to quit)
localstack_1  | 2020-07-14 09:00:58,634:API:  * Running on http://0.0.0.0:54145/ (Press CTRL+C to quit)
localstack_1  | 2020-07-14 09:00:58,634:API:  * Running on http://0.0.0.0:54145/ (Press CTRL+C to quit)
localstack_1  | 2020-07-14T09:00:58:INFO:localstack.utils.server.http2_server: Error running server event loop on port 4566: [SSL] PEM lib (_ssl.c:4012) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 112, in run_app_sync
localstack_1  |     return loop.run_until_complete(serve(app, config, **run_kwargs))
localstack_1  |   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
localstack_1  |     return future.result()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/__init__.py", line 39, in serve
localstack_1  |     await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 85, in worker_serve
localstack_1  |     ssl_context = config.create_ssl_context()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 144, in create_ssl_context
localstack_1  |     context.load_cert_chain(certfile=self.certfile, keyfile=self.keyfile)
localstack_1  | ssl.SSLError: [SSL] PEM lib (_ssl.c:4012)
localstack_1  |
localstack_1  | Running on 0.0.0.0:4581 over http (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:443 over https (CTRL + C to quit)
localstack_1  | 2020-07-14T09:00:58:WARNING:localstack.utils.server.http2_server: Unable to create SSL context. Cert files exist: /tmp/localstack/server.test.pem.crt True (1938B), /tmp/localstack/server.test.pem.key True (1703B)
localstack_1  | 2020-07-14T09:00:58:WARNING:bootstrap.py: Thread run method <bound method run_server.<locals>.ProxyThread.run_proxy of <ProxyThread(Thread-152, started daemon 139715324578592)>>(None) failed: Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 499, in run
localstack_1  |     self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 138, in run_proxy
localstack_1  |     run_app_sync(loop=loop, shutdown_event=self.shutdown_event)
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 112, in run_app_sync
localstack_1  |     return loop.run_until_complete(serve(app, config, **run_kwargs))
localstack_1  |   File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
localstack_1  |     return future.result()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/__init__.py", line 39, in serve
localstack_1  |     await worker_serve(app, config, shutdown_trigger=shutdown_trigger)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 85, in worker_serve
localstack_1  |     ssl_context = config.create_ssl_context()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/config.py", line 144, in create_ssl_context
localstack_1  |     context.load_cert_chain(certfile=self.certfile, keyfile=self.keyfile)
localstack_1  | ssl.SSLError: [SSL] PEM lib (_ssl.c:4012)
localstack_1  |
localstack_1  | Running on 0.0.0.0:4586 over http (CTRL + C to quit)
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | Ready.
```

**Comment by whummer** [comment]
Thanks for the update @themandoug @Vaunorage . We were now able to reproduce this issue - there was an error in the SSL context initialization (`ssl.SSLError: [SSL] PEM lib`) which should now be fixed in #2746 . Can you please do a `docker pull localstack/localstack` and give it another try with the `latest` version of the Docker image? Please report here if the problem persists. Thanks!

**Comment by themandoug** [comment]
Hi @whummer,

I still get the same issue although the logged information appears to be slightly more verbose:

```
localstack_1  | 2020-07-20T08:38:17:ERROR:asyncio: Task exception was never retrieved
localstack_1  | future: <Task finished name='Task-185' coro=<worker_serve.<locals>._server_callback() done, defined at /opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py:88> exception=SSLError(1, '[SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2730)')>
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 89, in _server_callback
localstack_1  |     await TCPServer(app, loop, config, reader, writer)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 84, in run
localstack_1  |     await self._close()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 129, in _close
localstack_1  |     await self.writer.wait_closed()
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
localstack_1  |     await self._protocol._get_close_waiter(self)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 104, in _read_data
localstack_1  |     data = await self.reader.read(MAX_RECV)
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 684, in read
localstack_1  |     await self._wait_for_data('read')
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
localstack_1  |     await self._waiter
localstack_1  |   File "/usr/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
localstack_1  |     ssldata, appdata = self._sslpipe.feed_ssldata(data)
localstack_1  |   File "/usr/lib/python3.8/asyncio/sslproto.py", line 207, in feed_ssldata
localstack_1  |     self._sslobj.unwrap()
localstack_1  |   File "/usr/lib/python3.8/ssl.py", line 948, in unwrap
localstack_1  |     return self._sslobj.shutdown()
localstack_1  | ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2730)
```

There is now a new issue when I go to `app.localstack.cloud`:

```
localstack_1  | 2020-07-20T08:38:51:WARNING:localstack.utils.server.http2_server: Error in proxy handler for request POST https://localhost.localstack.cloud/graph: MyHTTPConnectionPool(host='6aabdbfc5f29', port=8080): Max retries exceeded with url: /graph (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f407bd69f70>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
localstack_1  |     conn = connection.create_connection(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
localstack_1  |     raise err
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
localstack_1  |     sock.connect(sa)
localstack_1  | ConnectionRefusedError: [Errno 111] Connection refused
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_1  |     httplib_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
localstack_1  |     conn.request(method, url, **httplib_request_kw)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
localstack_1  |     self._send_request(method, url, body, headers, encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
localstack_1  |     self.endheaders(body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
localstack_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
localstack_1  |     self.send(msg)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 944, in send
localstack_1  |     self.connect()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
localstack_1  |     conn = self._new_conn()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
localstack_1  |     raise NewConnectionError(
localstack_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f407bd69f70>: Failed to establish a new connection: [Errno 111] Connection refused
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_1  |     resp = conn.urlopen(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
localstack_1  |     retries = retries.increment(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
localstack_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack_1  | urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='6aabdbfc5f29', port=8080): Max retries exceeded with url: /graph (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f407bd69f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/server/http2_server.py", line 83, in index
localstack_1  |     result = await run_sync(handler, request, data)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 46, in run_sync
localstack_1  |     return await loop.run_in_executor(THREAD_POOL, copy_context().run, func, *args)
localstack_1  |   File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
localstack_1  |     result = self.fn(*self.args, **self.kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 19, in modify_and_forward
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 332, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 69, in forward_request
localstack_1  |     response = function(url, data=data, headers=headers, verify=False, stream=True)
localstack_1  |   File "/opt/code/localstack/localstack/utils/common.py", line 1114, in _wrapper
localstack_1  |     return method(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='6aabdbfc5f29', port=8080): Max retries exceeded with url: /graph (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f407bd69f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Thanks,
Paul

**Comment by Winterspite** [comment]
I'm also getting this on LocalStack version: 0.11.4, macOS 10.15.6 (Catalina), Firefox 79.0 (64-bit).

Browse to https://app.localstack.cloud/resources
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://localhost.localstack.cloud/graph. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). onloadwff.js:71:798666
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 4 utils.js:35:9
ERROR: Error: Network Error index.js:302:12
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). utils.js:35:9
downloadable font: no supported format found (font-family: "fs-icons" style:normal weight:400 stretch:100 src index:1) source: (end of source list)
```

docker-compose.yml
```
version: "3"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY}
      - SERVICES=edge,dynamodb,kinesis,lambda,s3,sqs,iam,sns
      - DEBUG=1
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    ports:
      - "443:443"
      - "4510-4520:4510-4520"
      - "4566-4620:4566-4620"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
```

Launch String:
`TMPDIR=/private$TMPDIR docker-compose up`

LocalStack console
```
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2020-09-01 00:29:07,455 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
localstack_1  | 2020-09-01 00:29:07,457 INFO supervisord started with pid 13
localstack_1  | 2020-09-01 00:29:08,462 INFO spawned: 'dashboard' with pid 19
localstack_1  | 2020-09-01 00:29:08,465 INFO spawned: 'infra' with pid 20
localstack_1  | 2020-09-01 00:29:08,469 INFO success: dashboard entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
localstack_1  | 2020-09-01 00:29:08,469 INFO exited: dashboard (exit status 0; expected)
localstack_1  | (. .venv/bin/activate; exec bin/localstack start --host)
localstack_1  | LocalStack version: 0.11.4
localstack_1  | Starting local dev environment. CTRL-C to quit.
localstack_1  | 2020-09-01T00:29:09:DEBUG:bootstrap.py: Loading plugins - scope "commands", module "localstack_ext": <function register_localstack_commands at 0x7fcadd4c5550>
localstack_1  | 2020-09-01T00:29:09:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack_ext": <function register_localstack_plugins at 0x7fcade0f3940>
localstack_1  | 2020-09-01 00:29:10,054 INFO success: infra entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
localstack_1  | 2020-09-01T00:29:11:INFO:localstack_ext.bootstrap.licensing: Successfully activated API key
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2020-09-01T00:29:16:DEBUG:bootstrap.py: Loading plugins - scope "services", module "localstack": <function register_localstack_plugins at 0x7fcade0f3670>
localstack_1  | Starting DNS servers (tcp/udp port 53 on 0.0.0.0)...
localstack_1  | Starting edge router (http port 4566)...
localstack_1  | Starting edge router (https port 443)...
localstack_1  | Starting mock DynamoDB service in http ports 443 (recommended) and 4569 (deprecated)...
localstack_1  | Starting mock IAM service on http ports 443 (recommended) and 4593 (deprecated)...
localstack_1  | Starting mock Kinesis service in http ports 443 (recommended) and 4568 (deprecated)...
localstack_1  | Starting mock Lambda service on http ports 443 (recommended) and 4574 (deprecated)...
localstack_1  | Starting mock CloudWatch Logs service on http ports 443 (recommended) and 4586 (deprecated)...
localstack_1  | Starting mock S3 service on http ports 443 (recommended) and 4572 (deprecated)...
localstack_1  | Starting mock SNS service on http ports 443 (recommended) and 4575 (deprecated)...
localstack_1  | Starting mock SQS service on http ports 443 (recommended) and 4576 (deprecated)...
localstack_1  | Initializing DynamoDB Local with the following configuration:
localstack_1  | Port:	58319
localstack_1  | InMemory:	false
localstack_1  | DbPath:	/tmp/localstack/data/dynamodb
localstack_1  | SharedDb:	true
localstack_1  | shouldDelayTransientStatuses:	false
localstack_1  | CorsParams:	*
localstack_1  |
localstack_1  | Listening at http://:::42071
localstack_1  | 2020-09-01T00:29:16:DEBUG:bootstrap.py: Plugin loading took 7.377140045166016 sec
localstack_1  | 2020-09-01T00:29:16:INFO:localstack_ext.utils.aws.metadata_service: Starting AWS instance metadata service on port 80
localstack_1  | 2020-09-01T00:29:16:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | Running on 0.0.0.0:4566 over https (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:443 over https (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:4569 over http (CTRL + C to quit)
localstack_1  | 2020-09-01T00:29:16:INFO:localstack.multiserver: Starting multi API server process on port 52199
localstack_1  | Running on 0.0.0.0:4593 over http (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:52199 over http (CTRL + C to quit)
localstack_1  | 2020-09-01 00:29:16,617:API:  * Running on http://0.0.0.0:45877/ (Press CTRL+C to quit)
localstack_1  | Running on 0.0.0.0:4568 over http (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:4586 over http (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:4572 over http (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:4575 over http (CTRL + C to quit)
localstack_1  | Running on 0.0.0.0:4576 over http (CTRL + C to quit)
localstack_1  | Waiting for all LocalStack services to be ready
localstack_1  | 2020-09-01T00:29:22:INFO:botocore.credentials: Found credentials in environment variables.
localstack_1  | Ready.
localstack_1  | 2020-09-01T00:29:22:INFO:localstack.utils.persistence: Restored 2 API calls from persistent file: /tmp/localstack/data/recorded_api_calls.json
localstack_1  | 2020-09-01T00:29:39:WARNING:bootstrap.py: Thread run method <function AdaptiveThreadPool.submit.<locals>._run at 0x7fcad806bc10>(None) failed: MyHTTPConnectionPool(host='846c796e17bc', port=8080): Max retries exceeded with url: /graph (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcad8083cd0>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
localstack_1  |     conn = connection.create_connection(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
localstack_1  |     raise err
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
localstack_1  |     sock.connect(sa)
localstack_1  | ConnectionRefusedError: [Errno 111] Connection refused
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
localstack_1  |     httplib_response = self._make_request(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
localstack_1  |     conn.request(method, url, **httplib_request_kw)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1230, in request
localstack_1  |     self._send_request(method, url, body, headers, encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
localstack_1  |     self.endheaders(body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
localstack_1  |     self._send_output(message_body, encode_chunked=encode_chunked)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
localstack_1  |     self.send(msg)
localstack_1  |   File "/usr/lib/python3.8/http/client.py", line 944, in send
localstack_1  |     self.connect()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
localstack_1  |     conn = self._new_conn()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
localstack_1  |     raise NewConnectionError(
localstack_1  | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7fcad8083cd0>: Failed to establish a new connection: [Errno 111] Connection refused
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
localstack_1  |     resp = conn.urlopen(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
localstack_1  |     retries = retries.increment(
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
localstack_1  |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
localstack_1  | urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='846c796e17bc', port=8080): Max retries exceeded with url: /graph (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcad8083cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  |
localstack_1  | During handling of the above exception, another exception occurred:
localstack_1  |
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/localstack/utils/bootstrap.py", line 514, in run
localstack_1  |     result = self.func(self.params)
localstack_1  |   File "/opt/code/localstack/localstack/utils/async_utils.py", line 28, in _run
localstack_1  |     return fn(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 555, in handler
localstack_1  |     response = modify_and_forward(method=method, path=path_with_params, data_bytes=data, headers=headers,
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/utils/aws/aws_utils.py", line 22, in modify_and_forward
localstack_1  |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 332, in modify_and_forward
localstack_1  |     listener_result = listener.forward_request(method=method,
localstack_1  |   File "/opt/code/localstack/localstack/services/edge.py", line 70, in forward_request
localstack_1  |     response = function(url, data=data, headers=headers, verify=False, stream=True)
localstack_1  |   File "/opt/code/localstack/localstack/utils/common.py", line 1159, in _wrapper
localstack_1  |     return method(*args, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
localstack_1  |     return request('post', url, data=data, json=json, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
localstack_1  |     return session.request(method=method, url=url, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
localstack_1  |     resp = self.send(prep, **send_kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
localstack_1  |     r = adapter.send(request, **kwargs)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
localstack_1  |     raise ConnectionError(e, request=request)
localstack_1  | requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='846c796e17bc', port=8080): Max retries exceeded with url: /graph (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcad8083cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
localstack_1  |
localstack_1  | 2020-09-01T00:29:44:ERROR:asyncio: Task exception was never retrieved
localstack_1  | future: <Task finished name='Task-344' coro=<worker_serve.<locals>._server_callback() done, defined at /opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py:88> exception=SSLError(1, '[SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2730)')>
localstack_1  | Traceback (most recent call last):
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/run.py", line 89, in _server_callback
localstack_1  |     await TCPServer(app, loop, config, reader, writer)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 83, in run
localstack_1  |     await self._close()
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 129, in _close
localstack_1  |     await self.writer.wait_closed()
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 359, in wait_closed
localstack_1  |     await self._protocol._get_close_waiter(self)
localstack_1  |   File "/opt/code/localstack/.venv/lib/python3.8/site-packages/hypercorn/asyncio/tcp_server.py", line 103, in _read_data
localstack_1  |     data = await self.reader.read(MAX_RECV)
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 684, in read
localstack_1  |     await self._wait_for_data('read')
localstack_1  |   File "/usr/lib/python3.8/asyncio/streams.py", line 517, in _wait_for_data
localstack_1  |     await self._waiter
localstack_1  |   File "/usr/lib/python3.8/asyncio/sslproto.py", line 529, in data_received
localstack_1  |     ssldata, appdata = self._sslpipe.feed_ssldata(data)
localstack_1  |   File "/usr/lib/python3.8/asyncio/sslproto.py", line 207, in feed_ssldata
localstack_1  |     self._sslobj.unwrap()
localstack_1  |   File "/usr/lib/python3.8/ssl.py", line 948, in unwrap
localstack_1  |     return self._sslobj.shutdown()
localstack_1  | ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2730)
```

Let me know if there's anything else I can provide for troubleshooting.

**Comment by andreas-bergstrom** [comment]
Still getting this on 0.11.5 (48c113a43bf2), Pro-user Web UI not functioning and seeing the same errors in log. Health-endpoint shows services up, can use aws cli against them.

**Comment by ashameem123** [comment]
@whummer - can't see resources on UI.
[LS_UI.docx](https://github.com/localstack/localstack/files/5262885/LS_UI.docx)
