### ISSUE TITLE
Latest Docker container does not allow for create of an SQS Queue

### ISSUE THREAD

**Issue by anjiemerchant** [localstack/localstack#2839]
# Type of request: This is a ...

[x] bug report
[ ] feature request

# Detailed description
Running `aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test_queue` results in the following error message:

```
Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{"status": "running"}'
```
Running `aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name test_queue` results in the following error message:
```
Connection was closed before we received a valid response from endpoint URL: "http://localhost:4576/".
```
...

## Expected behavior
Queues should be created. 

`aws --endpoint-url=http://localhost:4566 sqs list-queues` should list queues.
...

## Actual behavior
No queues are created. No queues are listed.
...

# Steps to reproduce
1. Start LocalStack.
2. Run `aws --endpoint-url=http://localhost:4576 sqs create-queue --queue-name test_queue` in terminal. See error message.
3. Run  `aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test_queue` in terminal. See error message.

## Command used to start LocalStack
Here is my Dockerfile:
```
version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

I ran `docker-compose -f localstack/docker-compose.yml up -d`
...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

...

**Comment by whummer** [comment]
Thanks for reporting @anjiemerchant . Can you please share the version of the `aws` command line, and the ID/age of the Docker image you're using? Thanks
```
$ aws --version
aws-cli/1.18.66 Python/3.8.2 Darwin/19.0.0 botocore/1.17.35
$ docker images | grep localstack/localstack
localstack/localstack                latest                                           dc1cc547086e        20 hours ago        677MB
```

**Comment by anjiemerchant** [comment]
Hi @whummer ,

Here is the information you requested:

**the version of the aws command line, and the ID/age of the Docker image you're using**

`aws-cli/2.0.37 Python/3.7.4 Darwin/19.4.0 exe/x86_64`

`localstack/localstack                                           latest              9daa5ae4baee        2 days ago          677MB`

**the HTTP request headers that are being sent to the API**

`aws --debug --endpoint-url=http://localhost:4566 sqs create-queue --queue-name test_queue`:
```
Sending http request: <AWSPreparedRequest stream_output=False, method=POST, url=http://localhost:4566/, headers={'Content-Type': b'application/x-www-form-urlencoded; charset=utf-8', 'User-Agent': b'aws-cli/2.0.37 Python/3.7.4 Darwin/19.4.0 exe/x86_64 command/sqs.create-queue', 'X-Amz-Date': b'20200813T122213Z', 'Authorization': b'AWS4-HMAC-SHA256 Credential={credentials_here}, SignedHeaders=content-type;host;x-amz-date, Signature=1ef9ea2bd09c8ae573473a4517eed9040aee8b0cb06d2d3ad3dceec612aa0bb7', 'Content-Length': '58'}>
```

**Comment by usmangani1** [comment]
@anjiemerchant Thanks for providing the information.

Looks like this has been fixed in the latest version of localstack. We have tried to reproduce the issue using the aws cli command attached below and it worked fine.Please let us know in case if it works with the latest docker image.

```
 $ aws sqs create-queue --queue-name test_queue --endpoint-url http://localhost:4566
{
    "QueueUrl": "http://localhost:4566/000000000000/test_queue"
}

$ docker images
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
localstack/localstack   latest              ff9275065956        11 hours ago        663MB
```

**Comment by anjiemerchant** [comment]
Thanks for your reply, @usmangani1. I repulled the latest Docker image this morning and tried to rerun, but I am still receiving the error with my version of the awi-cli (`aws-cli/2.0.37 Python/3.7.4 Darwin/19.4.0 exe/x86_64`). See below:

```
$ aws sqs create-queue --queue-name test_queue --endpoint-url http://localhost:4566

Unable to parse response (not well-formed (invalid token): line 1, column 0), invalid XML received. Further retries may succeed:
b'{"status": "running"}'
```

My colleague also did the same; he is running `aws-cli/1.16.132 Python/2.7.16 Darwin/19.3.0 botocore/1.12.122`. He received the same output as I did.

What version of the aws-cli are you running?

**Comment by usmangani1** [comment]
@anjiemerchant 

```
$ aws --version
aws-cli/1.18.74 Python/3.7.7 Linux/4.15.0-99-generic botocore/1.16.8
```
This is my version.

**Comment by anjiemerchant** [comment]
@usmangani1 

I ran `localstack start` this morning and attempted to create the queue again. When it worked, I realized that there was something wrong in the Docker compose file:

```version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_demo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
```

I was missing SQS in `services`. 

Thanks for all your help. This was user error.
