### ISSUE TITLE
MD5 returned by SQS does not match the calculation on the original request. (Message Attributes)

### ISSUE THREAD

**Issue by marcuswr** [localstack/localstack#3022]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description
Attempting to write to sqs on localstack versions > 0.11.2 results in an MD5 checksum error. The error is specific to the message attributes hash value and not the hash value on the message body.

org.springframework.boot:2.3.3.RELEASE
org.springframework.cloud:spring-cloud-starter-aws-messaging:2.2.4.RELEASE
com.amazonaws:aws-java-sdk:1.11.859
java:8
localstack > 0.11.2

## Expected behavior
Ability to write a message successfully to sqs using the spring boot aws messaging template. Ability to read message
from the queue.

## Actual behavior
com.amazonaws.AmazonClientException is raised with message:
MD5 returned by SQS does not match the calculation on the original request. (MD5 calculated by the message attributes: "6ae84cc479cfb42193fad38475fc8857", MD5 checksum returned: "68ce18ded74c096f45eda3a67ccd51e4")
Note, checksums returned are different each time, even when message sent is the same. At least one message attribute is likely dynamic, probably a timestamp.

# Steps to reproduce
I have attached a sample program. 
Unizip and run:
docker-compose up &
sleep 60
mvn test

## Command used to start LocalStack
docker-compose up

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
Map<String, Object> headers = new HashMap<String, Object>() {{
        put(MessageHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE);
    }};
queueMessagingTemplate.convertAndSend(queueName, new User("abcxyz", "jane", "doe"), headers);

## Run with previous versions
This works prior to localstack 0.11.3.
This can be seen by doing he following steps:
Stop docker compose
Edit localstack version in docker-compose.yml, use localstack image 0.11.2 or earlier
docker-compose up &
sleep 60
mvn test

## Application to reproduce issue
[localstack-sqs-md5-message-attributes.zip](https://github.com/localstack/localstack/files/5268752/localstack-sqs-md5-message-attributes.zip)

**Comment by rparker-indeed** [comment]
+1 I'm having the exact same issue in my project with `queueMessagingTemplate.convertAndSend`

**Comment by artemtere** [comment]
@usmangani1 Fixed this in moto  repository. Not merged yet.
https://github.com/spulec/moto/pull/3403

**Comment by artemtere** [comment]
@usmangani1 spulec/moto#3403 is merged into master and is part of moto >= 1.3.16.dev76 see [closed issue](https://github.com/spulec/moto/issues/3399#issuecomment-717231624)

**Comment by artemtere** [comment]
@usmangani1 please replay ↑

**Comment by usmangani1** [comment]
@artemtere As the issue has been fixed in upstream moto. We will pull the upstream changes and release a new version soon.Thanks

**Comment by whummer** [comment]
Thanks @artemtere @usmangani1 . The upstream changes are now included in LocalStack - can you please pull the `latest` Docker image and give it another try? Please report here if the problem persists. Thanks

**Comment by hyderkhanmoj** [comment]
I am using version `0.12.10` and the issue still persists. It does not exist in earlier versions using the same test.

**Comment by mgagliardo** [comment]
Hello @hyderkhanmoj , would you please open a new issue with example outputs as well as how are you running localstack,etc so we can reproduce this? Thanks.

**Comment by bravecobra** [comment]
I seem to have the same issue in the latest build

**Comment by hyderkhanmoj** [comment]
> Hello @hyderkhanmoj , would you please open a new issue with example outputs as well as how are you running localstack,etc so we can reproduce this? Thanks.

Hi @mgagliardo I have been doing some testing & attempted to re-create the problem. I will raise a new issue with an example.

**Comment by mvillafuertem** [comment]
Hi @whummer, I'm using version 1.0.4 and the issue still persists. Any workaround? Thanks
