### ISSUE TITLE
Option to disable web or change port

### ISSUE THREAD

**Issue by tadrinth** [localstack/localstack#303]
I am trying to use localstack to test a web server, however my web server cannot bind to port 8080 because that port is in use by localstack's web server.  

Is there a way to tell localstack not to spin up the web server, or to change the port used?  

I can see a default port in the constants file, but I don't see any documentation about how to override that default.

**Comment by whummer** [comment]
Thanks for reporting @tadrinth . This is fixed in 231d22599ff7ce944e5895e024e0672d07df8f93, you can now configure the port of the Web UI using the environment variable `PORT_WEB_UI`. Can you please give it a try with the latest Docker image (currently being built and pushed here: https://travis-ci.org/localstack/localstack/builds/272144671). Thanks

**Comment by tadrinth** [comment]
This does not work:

PORT_WEB_UI=9080 docker-compose up

May need to add to docker-compose.yml?

**Comment by whummer** [comment]
Good catch, that was an oversight. Fixed in 005d048eeb976ca12e3265b8a9260bdb467d2534 . Closing this issue, please re-open if there are any other problems. Thanks

**Comment by tadrinth** [comment]
This still does not work: 

PORT_WEB_UI=9080 docker-compose up

It still spins up the web server on 8080, no idea why as your changes to docker-compose.yml look correct to me.

**Comment by whummer** [comment]
That's odd. This is what happens on my machine (note that I had to re-map TMPDIR, this is a known issue under Mac OS):
```
$ PORT_WEB_UI=9080 TMPDIR=/private/$TMPDIR docker-compose up
...
localstack_1  | (. .venv/bin/activate; bin/localstack web)
localstack_1  | 2017-09-22T00:46:00:INFO:werkzeug:  * Running on http://0.0.0.0:9080/ (Press CTRL+C to quit)
...
```
Can you try pulling the latest version of the image:
```
docker pull localstack/localstack
docker pull localstack/localstack:latest
```

**Comment by tadrinth** [comment]
That fixed it, I guess i needed to pull the latest docker image, not just
the latest version of the code in github.  Thanks!

**Comment by jeromegn** [comment]
This spins up the webserver on the correct port, but the docker-compose.yml still tries to bind port `8080:8080` without regards to the environment variable: https://github.com/localstack/localstack/blob/master/docker-compose.yml#L8

I'm not sure how it that feature worked, if the correct port is not bound on the host, then you can't really access the web UI unless you use the container's IP.

**Comment by whummer** [comment]
Thanks for the hint @jeromegn , this should be fixed in #571 . We now configure docker-compose to use the port in `PORT_WEB_UI` , and fall back to `8080` by default.

**Comment by mayaschuster** [comment]
Was it fixed? This still happens to me after pulling the latest docker image... (trying to run with PORT_WEB_UI=9080, localstack still tries port 8080)

**Comment by pubkey** [comment]
Can we reopen this? Or is this really fixed?

**Comment by whummer** [comment]
The following works for me under Mac OS with the latest image:
```
$ PORT_WEB_UI=9182 docker-compose up
...
localstack_1  | 2018-05-11T04:33:27:INFO:werkzeug:  * Running on http://0.0.0.0:9182/ (Press CTRL+C to quit)
```
```
$ curl -v localhost:9182 2>&1 | grep HTTP/
```
Which OS version are you using?

**Comment by pubkey** [comment]
@whummer I'm using linux mint Sarah.
The problem is not that I could change the port in docker-compose, but I want to change the port when running `localstack start --docker`

**Comment by bradcurfman** [comment]
I tried this today on an AWS Linux EC2 server that has port 8080 bound to Tomcat and I still get the error after setting PORT_WEB_UI to port 8888. You can see in the docker output that it sees my port override. I issued these commands

```
export PORT_WEB_UI=8888
localstack start --docker

```
and got the output below

```
docker run -it -e HOSTNAME="ip-172-31-61-28" -e LOCALSTACK_HOSTNAME="ip-172-31-61-28" -e PORT_WEB_UI="8888" -p 8080:8080 -p 443:443 -p 4567-4583:4567-4583 -p 4590-4593:4590-4593 -v "/tmp/localstack:/tmp/localstack" -v "/var/run/docker.sock:/var/run/docker.sock" -e DOCKER_HOST="unix:///var/run/docker.sock" -e HOST_TMP_FOLDER="/tmp/localstack" "localstack/localstack" 
docker: Error response from daemon: driver failed programming external connectivity on endpoint pensive_varahamihira (cf61839335905f6fa8b4bd57a464a175744ea14b0175f851010aa9df14b4111f): Error starting userland proxy: listen tcp 0.0.0.0:8080: bind: address already in use.
```
