### ISSUE TITLE
RDS data does not persist in docker volume

### ISSUE THREAD

**Issue by holyoaks** [localstack/localstack#3391]
# Type of request: This is a ...

[ X] bug report
[ ] feature request

# Detailed description

RDS instances do not persist even when a volume is specified in the docker app. Especially egregious when the corresponding DynamoDB and S3 volume data DOES persist

## Expected behavior

RDS instances will persist if a volume is specified, along with the underlying postgresql database and data

## Actual behavior

Every time the Docker app is started, querying the RDS service instances returns: 
```
aws --endpoint-url=http://host.docker.internal:4566 rds describe-db-instances

{
    "DBInstances": []
}
```

# Steps to reproduce

## Command used to start LocalStack

Docker-compose. Please notice the volumes at the bottom. A volume is specified individually for each LocalStack service. Only the RDS volume fails to persist data.

```
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRON: dev
    depends_on:
      - localstack
      - rabbitmq
      - redis
    environment:
      - AWS_ACCESS_KEY_ID='FakeAccessKey'
      - AWS_SECRET_ACCESS_KEY='FakeSecretAccessKey'
      - AWS_DEFAULT_REGION=us-east-1
      - WAIT_HOSTS=rabbitmq:4369, rabbitmq:5672, rabbitmq:25672, rabbitmq:15672, redis:6379, localstack:4566
      - WAIT_HOSTS_TIMEOUT=60
      - WAIT_BEFORE_HOSTS=30
    ports:
      - "8001:80"
    command: sh -c "/wait && circusd /srv/circus.ini --log-output /var/log/circusd.log"

  rabbitmq:
    image: "bitnami/rabbitmq:3.7"
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"

  redis:
    image: "bitnami/redis:6.0.9"
    environment:
      - REDIS_PASSWORD=password123
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "443:443"
      - "4510-4520:4510-4520"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3,dynamodb,rds
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_API_KEY=########
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "s3data:/tmp/localstack/data/s3"
      - "dynamodata:/tmp/localstack/data/ddb"
      - "rdsdata:/tmp/localstack/data/rds"

  celery-flower:
    image: gregsi/latest-celery-flower-docker:latest
    environment:
      - AMQP_USERNAME=user
      - AMQP_PASSWORD=bitnami
      - AMQP_ADMIN_USERNAME=user
      - AMQP_ADMIN_PASSWORD=bitnami
      - AMQP_HOST=rabbitmq
      - AMQP_PORT=5672
      - AMQP_ADMIN_HOST=rabbitmq
      - AMQP_ADMIN_PORT=15672
      - FLOWER_BASIC_AUTH=user:test
    ports:
      - "5555:5555"

volumes:
  dynamodata:
  rdsdata:
  s3data:
  rabbitmq_data:
    driver: local
  redis_data:
    driver: local

```

**Comment by whummer** [comment]
Thanks for reporting @holyoaks , and apologies for the long delay. This has been fixed in the meantime - can you please pull the `latest` Docker image and give it another try? (We'll release a new tagged version shortly.) Please keep us posted how it goes. Thanks for your help!

**Comment by holyoaks** [comment]
@whummer , I'm afraid I can't agree that this has been fixed. I completely deleted all my docker containers that form part of the app, and ran `docker volume prune` to completely clear out the existing environment. I changed my localstack configuration to:

```
  localstack:
    image: localstack/localstack:latest
```

and ran `docker-compose ...up --build`

Everything built properly, as expected. I ran the bootstrap script I have to create the RDS database instance, and populate the initial, required data. All that worked fine. I queried the database, and verified that the data was present in the tables.

I then shut down the docker app, and restarted it when it finished shutting down. I expected the RDS database instance and the corresponding data to still be present. They were not. I had to run my bootstrap script again, and again, it successfully created the RDS instance. The RDS instance, and the associated data, is not persisting.

**Comment by holyoaks** [comment]
@whummer I'm afraid this is not resolved. I deleted all the docker containers in my app, then ran `docker volume prune` to clear out the entire app. I then ran `docker image rm <image id> -f` to completely remove the localstack docker image. I changed my localstack config in my docker-compose file to:

```
  localstack:
    image: localstack/localstack:latest
```

and ran `docker-compose ... up --build`. The new image was downloaded (version 0.12.6) and everything built and the app started up as expected. I ran by bootstrap script to create and populate the RDS instance with required data. I queried the database to verify the data was present, and it was.

I then shut down the docker app, and restarted it once it finished shutting down. I expected the RDS instance and data to still be present. They were not. I had to again run my bootstrap script to create and populate the RDS instance.

RDS instances are still not persisting after app shutdown and restart

**Comment by whummer** [comment]
Thanks for the update @holyoaks . Can you please try mounting the entire `/tmp/localstack/data` folder as a volume into the container - the RDS DB data should get stored in a folder `$DATA_DIR/rds-data`. Hope that helps - please keep us posted. Thanks!

**Comment by holyoaks** [comment]
My volumes for localstack are mounted as:

```
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "s3data:/tmp/localstack/data/s3"
      - "dynamodata:/tmp/localstack/data/ddb"
      - "rdsdata:/tmp/localstack/data/rds"
```
  Is that not a viable approach? Are you recommending eliminating the 3 separate volume specifications to include just the one?

**Comment by whummer** [comment]
Yes, if possible, that would be great. The general recommendation is to create a volume specification for the entire `$DATA_DIR` folder. We currently have not (yet) defined a standard that prescribes the layout of different folders in the persistence folder - ideally the entire `$DATA_DIR` should get persisted and be made available to the container. Thanks

**Comment by holyoaks** [comment]
No joy. I still don't get a persistent RDS instance. My localstack volumes:
```
    volumes:
      - "data:/tmp/localstack/data"
```
 and my docker app volumes:
```
volumes:
  data:
...
```

**Comment by whummer** [comment]
Closing this issue here, continuing the discussion directly on Slack.. Thanks again.

**Comment by nallwhy** [comment]
How was this issue solved?
