### ISSUE TITLE
Error when creating HTTPS SNS Subscription

### ISSUE THREAD

**Issue by dimdog** [localstack/localstack#350]
Hey!

I'm trying to create an SNS notification to a local https endpoint using the AWS cli and localstack.

Where I am right now, I've created a bucket "test" in localstack S3.

I've created an SNS topic:
```
aws --endpoint-url=http://localhost:4575 sns create-topic --name putnotifications --region=us-east-1
{
    "TopicArn": "arn:aws:sns:us-east-1:123456789012:putnotifications"
}
```

Then to configure the notifications, running ```aws s3api --endpoint=http://localhost:4572 --region=us-east-1 put-bucket-notification-configuration --bucket test --notification-configuration file://notificationconfiguration.json``` with notificationconfiguration.json looking like: ```{ "TopicConfigurations": [ { "TopicArn": "arn:aws:sns:us-east-1:123456789012:putnotifications", "Events": [ "s3:ObjectCreated:*" ] } ] }```

Lastly, to attempt to set the subscription I've been running: 
`aws --endpoint=http://localhost:4572 --region us-east-1 sns subscribe --topic-arn arn:aws:sns:us-east-1:123456789012:putnotifications --protocol https --notification-endpoint https://storagehook.wake.devel `

I can see a stack trace on the localstack side: 

```2017-09-26T11:10:41:ERROR:localstack.services.generic_proxy: Error forwarding request: 'boundary' Traceback (most recent call last):
  File "/Users/ben/code/wake-dev/.venv/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 171, in forward
    path=path, data=data, headers=forward_headers)
  File "/Users/ben/code/wake-dev/.venv/lib/python2.7/site-packages/localstack/services/s3/s3_listener.py", line 345, in forward_request
    expanded_data = expand_multipart_filename(original_data, headers)
  File "/Users/ben/code/wake-dev/.venv/lib/python2.7/site-packages/localstack/services/s3/s3_listener.py", line 261, in expand_multipart_filename
    boundary = params['boundary'].encode('ascii')
KeyError: 'boundary'```

**Comment by julienduchesne** [comment]
You are using the endpoint on port 4572 here:
`
aws --endpoint=http://localhost:4572 --region us-east-1 sns subscribe --topic-arn arn:aws:sns:us-east-1:123456789012:putnotifications --protocol https --notification-endpoint https://storagehook.wake.devel
`

SNS is on port 4575

**Comment by dimdog** [comment]
Thanks @julienduchesne ! I've now successfully created my subscription, however when the event triggers, I get this warning: `2017-10-04T14:07:40:WARNING:localstack.services.sns.sns_listener: Unexpected protocol "https" for SNS subscription` and the event doesn't fire. I'm sure i'm doing something simple wrong... :-/

**Comment by whummer** [comment]
That looks like a bug @dimdog . Did you start LocalStack with the `USE_SSL=1` configuration by any chance?

**Comment by dimdog** [comment]
@whummer 

Thanks! I hoped it might be as easy as changing line 70 in services/sns/sns_listener.py to include "or subscriber['Protocol'] == 'https':", but that doesn't seem to have had the effect I thought it would.

**Comment by whummer** [comment]
@dimdog This should be fixed now, can you please give it a try with the latest version.

Please note that the endpoint `https://storagehook.wake.devel` needs to respond to `POST` requests, the name `storagehook.wake.devel` needs to resolve properly, and the host needs to be accessible from the LocalStack process (either from the local machine, or from within Docker if you are running LocalStack within Docker).

If it does not work with the latest version, please provide the error details here. Thanks

**Comment by dimdog** [comment]
@whummer 

I've updated my localstack (`pip install localstack -U`) and restarted it, then created the subscription. One thing I've noticed is I had to change my configuration file to 
```
{ "TopicConfigurations":
    [
        { "TopicArn": "arn:aws:sns:us-east-1:123456789012:putnotifications", "Events": [ "s3:ObjectCreated:*", "" ] }
    ]
}

```
from 
```
{ "TopicConfigurations":
    [
        { "TopicArn": "arn:aws:sns:us-east-1:123456789012:putnotifications", "Events": [ "s3:ObjectCreated:*" ] }
    ]
}
```

If I used the latter .json file, It parsed each letter in `Events` as an individual item -  though I tried with both .jsons and neither seemed to work.

I've confirmed the endpoint responds both from where localstack is running (not dockerized)
```ping storagehook.wake.devel
PING storagehook.wake.devel (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.048 ms
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.085 ms
```

and that it responds to POSTs. 

Unfortunately, even in debug mode on localstack, I'm no longer seeing any error messages.

**Comment by whummer** [comment]
Sorry, I forgot to mention that this is fixed only on `master` and for the `latest` Docker image, but the fix is not yet released as a new version of the `pip` package.

Can you try running the latest version of `master` via:
```
git clone https://github.com/localstack/localstack
cd localstack
make install
DEBUG=1 make infra
```
... and then give it another try with the SNS notification. Thanks

**Comment by dimdog** [comment]
Thanks for the detailed update @whummer !

I've done exactly as you described, though I'm still getting similar results. I've pulled some additional information to help debug:
To get the  bucket configuration, and the configuration itself...
```
aws s3api --endpoint=http://localhost:4572 --region=us-east-1 get-bucket-notification-configuration --bucket storage
{
    "TopicConfigurations": [
        {
            "Id": "e5c5f992-cf4f-4bf9-9413-5a374031e88a",
            "TopicArn": "arn:aws:sns:us-east-1:123456789012:putnotifications",
            "Events": [
                "s3:ObjectCreated:*",
                "None"
            ]
        }
    ]
}
```
and I accidentally made two subscriptions, but that should just result in double messages, I would think...

```
aws --endpoint=http://localhost:4575 --region us-east-1 sns list-subscriptions-by-topic --topic-arn arn:aws:sns:us-east-1:123456789012:putnotifications
{
    "Subscriptions": [
        {
            "Owner": "",
            "Endpoint": "https://storagehook.wake.devel",
            "Protocol": "https",
            "TopicArn": "arn:aws:sns:us-east-1:123456789012:putnotifications",
            "SubscriptionArn": "arn:aws:sns:us-east-1:123456789012:putnotifications:3eae440d-f952-4e99-98be-7ae2300dc13e"
        },
        {
            "Owner": "",
            "Endpoint": "https://storagehook.wake.devel",
            "Protocol": "https",
            "TopicArn": "arn:aws:sns:us-east-1:123456789012:putnotifications",
            "SubscriptionArn": "arn:aws:sns:us-east-1:123456789012:putnotifications:7b5d039a-add6-4a70-a39d-d202857c3983"
        }
    ]
}
```

To be clear, my client is making a request that yields this log from localstack: 
```
127.0.0.1 - - [09/Oct/2017 11:21:15] "PUT /3eVxxVQzuUSWbFsn8d8r6c/9oLhXL5pCi9R1OztLnWpY/orig/Screen%20Shot%202017-09-03%20at%2012.44.20%20PM.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=300&X-Amz-SignedHeaders=host%3Bx-amz-server-side-encryption&X-Amz-Signature=e80097a6f7467b897e210c5bbb40f14378d0ce45c98d1671be18aebb87c162b8&X-Amz-Date=20171009T182115Z&X-Amz-Credential=accessKey1%2F20171009%2Fus-east-1%2Fs3%2Faws4_request HTTP/1.1" 200 -
```

...and I'm expected a post to https://storagehook.wake.devel after that happens. 


Thanks for all of your help!

**Comment by dimdog** [comment]
I also seem to have triggered this stack trace somehow (randomly though testing)

```2017-10-09T12:30:40:ERROR:localstack.services.generic_proxy: Error forwarding request: You must specify a region. Traceback (most recent call last):
  File "/Users/ben/code/wake-dev/code/localstack/localstack/services/generic_proxy.py", line 194, in forward
    path=path, data=data, headers=forward_headers, response=response)
  File "/Users/ben/code/wake-dev/code/localstack/localstack/services/s3/s3_listener.py", line 436, in return_response
    send_notifications(method, bucket_name, object_path)
  File "/Users/ben/code/wake-dev/code/localstack/localstack/services/s3/s3_listener.py", line 138, in send_notifications
    sns_client = aws_stack.connect_to_service('sns')
  File "/Users/ben/code/wake-dev/code/localstack/localstack/utils/aws/aws_stack.py", line 150, in connect_to_service
    return method(service_name, region_name=region, endpoint_url=endpoint_url, verify=verify)
  File "/Users/ben/code/wake-dev/code/localstack/.venv/lib/python2.7/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/Users/ben/code/wake-dev/code/localstack/.venv/lib/python2.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/Users/ben/code/wake-dev/code/localstack/.venv/lib/python2.7/site-packages/botocore/session.py", line 836, in create_client
    client_config=config, api_version=api_version)
  File "/Users/ben/code/wake-dev/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 71, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/ben/code/wake-dev/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 281, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/ben/code/wake-dev/code/localstack/.venv/lib/python2.7/site-packages/botocore/args.py", line 45, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/Users/ben/code/wake-dev/code/localstack/.venv/lib/python2.7/site-packages/botocore/args.py", line 111, in compute_client_args
    service_name, region_name, endpoint_url, is_secure)
  File "/Users/ben/code/wake-dev/code/localstack/.venv/lib/python2.7/site-packages/botocore/client.py", line 354, in resolve
    service_name, region_name)
  File "/Users/ben/code/wake-dev/code/localstack/.venv/lib/python2.7/site-packages/botocore/regions.py", line 122, in construct_endpoint
    partition, service_name, region_name)
  File "/Users/ben/code/wake-dev/code/localstack/.venv/lib/python2.7/site-packages/botocore/regions.py", line 135, in _endpoint_for_partition
    raise NoRegionError()
NoRegionError: You must specify a region.```

**Comment by whummer** [comment]
Thanks for pointing out that error, this one is fixed in #391 . I'm assuming that this could be the root cause for your other issue. Can you please pull the code and try again?

**Comment by dimdog** [comment]
Hey! Sorry for going dark - This seems to work now. I've been getting another error in the pipeline that I am pretty sure now is unrelated, so I think you can close this, and if I can isolate the other issue and confirm its not on my side I'll make another issue. Thank you so much for your help!
