### ISSUE TITLE
Respect "Accept: application/json" Header to return results as JSON not XML

### ISSUE THREAD

**Issue by seveibar** [localstack/localstack#3715]
# Type of request: This is a ...

[X] bug report
[ ] feature request

# Detailed description

The AWS API will return a JSON response if `Accept: application/json` is put on requests. e.g. for SQS one can request `<queue url>?Action=ListQueues` with `Accept: application/json` and get...

```
{
   "ListQueuesResponse":{
      "ListQueuesResult":{
         "NextExclusiveStartQueueName":null,
         "NextToken":null,
         "queueUrls":[
            
         ]
      },
      "ResponseMetadata":{
         "RequestId":"a7f38b75-cb64-5ef7-b202-d3fd30eeb26c"
      }
   }
}
```

## Actual behavior

XML is always returned.

# Steps to reproduce

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)

```
curl -H 'Accept: application/json' \
     -H 'Authorization: AWS4-HMAC-SHA256 Credential=_not_needed_locally_/20210312/us-east-1/sqs/aws4_request' \
     'http://localhost:4566?Action=ListQueues'
```

Returns something like...

```
<ListQueuesResponse>
   <ListQueuesResult></ListQueuesResult>
   <ResponseMetadata>
      <RequestId>UT0OFIKVW2V18LFISE5DUFLRMYG1VEGHKHUK7XNZRQTHOK0VYD9E</RequestId>
   </ResponseMetadata>
</ListQueuesResponse>
```

**Comment by seveibar** [comment]
I've released a pip module for converting XML responses to AWS-structured JSON. It should make this substantially easier: https://pypi.org/project/awsxmltojson/

**Comment by RussellNS** [comment]
As of today, this is still an issue.

I can run these commands:

```
# curl -vi -H 'Content-Type: application/xml' -H 'Accept: application/xml' -X GET http://s3.localhost:4566/test1234
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 10.10.12.50:4566...
* Connected to s3.localstack.example.com (xx.xx.xx.xx) port 4566 (#0)
> GET /test1234 HTTP/1.1
> Host: s3.localstack.example.com:4566
> User-Agent: curl/7.88.1
> Content-Type: application/xml
> Accept: application/xml
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Server: TwistedWeb/24.3.0
Server: TwistedWeb/24.3.0
< Date: Tue, 23 Jul 2024 19:53:46 GMT
Date: Tue, 23 Jul 2024 19:53:46 GMT
< Content-Type: application/xml
Content-Type: application/xml
< Content-Length: 539
Content-Length: 539
< x-amz-request-id: 6dd544b1-ac23-4f72-9727-953b6f9d7f6c
x-amz-request-id: 6dd544b1-ac23-4f72-9727-953b6f9d7f6c
< x-amz-id-2: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=
x-amz-id-2: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=

<
<?xml version='1.0' encoding='utf-8'?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><IsTruncated>false</IsTruncated><Marker /><Name>test1234</Name><Prefix /><MaxKeys>1000</MaxKeys><Contents><Key>testFile.txt</Key><ETag>"bdbc556026ca6d7855ad1996c21c7bca"</ETag><Owner><DisplayName>webfile</DisplayName><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID></Owner><Size>17</Size><LastModified>2024-07-16T14:26:33.000Z</LastModified><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>
* Connection #0 to host s3.localstack.example.com left intact
```

Or

```
# curl -vi -H 'Content-Type: application/json' -H 'Accept: application/json' -X GET http://s3.localhost:4566/test1234

Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:4566...
* Connected to s3.localhost (127.0.0.1) port 4566 (#0)
> GET /test1234 HTTP/1.1
> Host: s3.localhost:4566
> User-Agent: curl/7.88.1
> Content-Type: application/json
> Accept: application/json
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Server: TwistedWeb/24.3.0
Server: TwistedWeb/24.3.0
< Date: Tue, 23 Jul 2024 19:56:46 GMT
Date: Tue, 23 Jul 2024 19:56:46 GMT
< Content-Type: application/xml
Content-Type: application/xml
< Content-Length: 539
Content-Length: 539
< x-amz-request-id: a3865fc4-691a-4a6a-b6ae-dbe310078406
x-amz-request-id: a3865fc4-691a-4a6a-b6ae-dbe310078406
< x-amz-id-2: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=
x-amz-id-2: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=

<
<?xml version='1.0' encoding='utf-8'?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><IsTruncated>false</IsTruncated><Marker /><Name>test1234</Name><Prefix /><MaxKeys>1000</MaxKeys><Contents><Key>testFile.txt</Key><ETag>"bdbc556026ca6d7855ad1996c21c7bca"</ETag><Owner><DisplayName>webfile</DisplayName><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID></Owner><Size>17</Size><LastModified>2024-07-16T14:26:33.000Z</LastModified><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>
* Connection #0 to host s3.localhost left intact
```

Or

```
# curl -vi -H 'Content-Type: application/blahblahblah' -H 'Accept: application/blahblahblah' -X GET http://s3.localhost:4566/test1234

Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 127.0.0.1:4566...
* Connected to s3.localhost (127.0.0.1) port 4566 (#0)
> GET /test1234 HTTP/1.1
> Host: s3.localhost:4566
> User-Agent: curl/7.88.1
> Content-Type: application/blahblahblah
> Accept: application/blahblahblah
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Server: TwistedWeb/24.3.0
Server: TwistedWeb/24.3.0
< Date: Tue, 23 Jul 2024 19:57:49 GMT
Date: Tue, 23 Jul 2024 19:57:49 GMT
< Content-Type: application/xml
Content-Type: application/xml
< Content-Length: 539
Content-Length: 539
< x-amz-request-id: eef7220c-1b38-40fc-990c-2674b81d820c
x-amz-request-id: eef7220c-1b38-40fc-990c-2674b81d820c
< x-amz-id-2: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=
x-amz-id-2: s9lzHYrFp76ZVxRcpX9+5cjAnEH2ROuNkd2BHfIa6UkFVdtjf5mKR3/eTPFvsiP/XV/VLi31234=

<
<?xml version='1.0' encoding='utf-8'?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><IsTruncated>false</IsTruncated><Marker /><Name>test1234</Name><Prefix /><MaxKeys>1000</MaxKeys><Contents><Key>testFile.txt</Key><ETag>"bdbc556026ca6d7855ad1996c21c7bca"</ETag><Owner><DisplayName>webfile</DisplayName><ID>75aa57f09aa0c8caeab4f8c24e99d10f8e7faeebf76c078efc7c6caea54ba06a</ID></Owner><Size>17</Size><LastModified>2024-07-16T14:26:33.000Z</LastModified><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>
* Connection #0 to host s3.localhost left intact
```

All 3 commands work successfully ('application/blahblahblah'?), and all 3 commands return XML.

**Comment by bentsku** [comment]
Hello @RussellNS,

This is exactly in line with AWS behavior, I've just gave it a try against a live bucket in S3.

```bash
$ curl -vi https://test-bucket-2307.s3.amazonaws.com/
*   Trying 52.217.17.220:443...
* Connected to test-bucket-2307.s3.amazonaws.com (52.217.17.220) port 443
* using HTTP/1.1
> GET / HTTP/1.1
> Host: test-bucket-2307.s3.amazonaws.com
> User-Agent: curl/8.4.0
> Accept: */*
>
HTTP/1.1 200 OK
x-amz-id-2: u/JVEEDl3THwrhVvrBD8lQ1+k/E5gZw4Pf7xRbCwMVrO72HPHPhCKxvnyzoeJjgWC56CX+2ZqLk=
x-amz-request-id: 5DD4GSSA91NDEDCY
Date: Tue, 23 Jul 2024 22:44:27 GMT
x-amz-bucket-region: us-east-1
Content-Type: application/xml
Transfer-Encoding: chunked
Server: AmazonS3

<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host test-bucket-2307.s3.amazonaws.com left intact
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test-bucket-2307</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>

$ curl -vi https://test-bucket-2307.s3.amazonaws.com/ -H 'Content-Type: application/json' -H 'Accept: application/json'
*   Trying 16.182.104.209:443...
* Connected to test-bucket-2307.s3.amazonaws.com (16.182.104.209) port 443
* using HTTP/1.1
> GET / HTTP/1.1
> Host: test-bucket-2307.s3.amazonaws.com
> User-Agent: curl/8.4.0
> Content-Type: application/json
> Accept: application/json
>
HTTP/1.1 200 OK
x-amz-id-2: Rgv/+Vz64Xj/NOOa2OHb5e8w8VOq0FWAVqgafg50DVsdwPBSjdLemRFa308MyWYFCcuFl78RWP8=
x-amz-request-id: BY481QW7TC7M200X
Date: Tue, 23 Jul 2024 22:45:21 GMT
x-amz-bucket-region: us-east-1
Content-Type: application/xml
Transfer-Encoding: chunked
Server: AmazonS3

<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host test-bucket-2307.s3.amazonaws.com left intact
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test-bucket-2307</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>

$ curl -vi https://test-bucket-2307.s3.amazonaws.com/ -H 'Content-Type: application/blahblahblah' -H 'Accept: application/blahblahblah'
*   Trying 52.217.114.81:443...
* Connected to test-bucket-2307.s3.amazonaws.com (52.217.114.81) port 443
* using HTTP/1.1
> GET / HTTP/1.1
> Host: test-bucket-2307.s3.amazonaws.com
> User-Agent: curl/8.4.0
> Content-Type: application/blahblahblah
> Accept: application/blahblahblah
>
HTTP/1.1 200 OK
x-amz-id-2: TewsMYWnEFNptTb/awYKQRJSId6siAhnnHZj9cDIK/u7Z6CX4qaVUkFR8IM1AXZlbQsReox7k0U=
x-amz-request-id: F0CC2A2D1ZWFFN24
Date: Tue, 23 Jul 2024 22:45:45 GMT
x-amz-bucket-region: us-east-1
Content-Type: application/xml
Transfer-Encoding: chunked
Server: AmazonS3

<?xml version="1.0" encoding="UTF-8"?>
* Connection #0 to host test-bucket-2307.s3.amazonaws.com left intact
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test-bucket-2307</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated></ListBucketResult>
```

AWS S3 does not support returning JSON data. Or am I missing something to test it against AWS? 

For the original issue, SQS should now return JSON data, and also support `application/x-amz-json-1.1`.

**Comment by RussellNS** [comment]
> AWS S3 does not support returning JSON data. Or am I missing something to test it against AWS?
> 
> For the original issue, SQS should now return JSON data, and also support `application/x-amz-json-1.1`.

Ahhh, well then, my apologies.  Thank you for educating me!

**Comment by bentsku** [comment]
No worries, I was also worried we'd be missing something! 😄
