### ISSUE TITLE
Timestream delete_database, list_tables and query errors

### ISSUE THREAD

**Issue by villekr** [localstack/localstack#3739]
# Type of request: This is a ...

[ x] bug report
[ ] feature request

# Detailed description
macOS, localstack 0.12.8 PRO, python 3.8.1 and boto3 1.16.38.
...

## Expected behavior
The script below run against AWS works as it should.
...

## Actual behavior
The script below run against Localstack fails when executing "list_tables", "delete_database" and "query" requests.
...

# Steps to reproduce

## Command used to start LocalStack

...

## Client code (AWS SDK code snippet, or sequence of "awslocal" commands)
```
import asyncio
from uuid import uuid4
import boto3


endpoint_url = "http://localhost:4566"  # set to None when accessing AWS
session = boto3.session.Session(region_name="eu-west-1")
ts_write_client = session.client(
    "timestream-write", endpoint_url=endpoint_url
)
ts_query_client = session.client(
    "timestream-query", endpoint_url=endpoint_url
)
database_name = "local_timestream_database"
table_name = "local_timestream_table"


async def setup_timestream():
    print("setup_timestream")
    try:
        print("create_database")
        response = ts_write_client.create_database(DatabaseName=database_name)
        print(response)
        print("Sleep 5s...")
        await asyncio.sleep(5)
    except Exception as e:
        print(e)

    try:
        print("create_table")
        response = ts_write_client.create_table(
            DatabaseName=database_name,
            TableName=table_name,
            RetentionProperties={
                "MemoryStoreRetentionPeriodInHours": 12,
                "MagneticStoreRetentionPeriodInDays": 30,
            },
        )
        print(response)
        print("Sleep 5s...")
        await asyncio.sleep(5)
    except Exception as e:
        print(e)

    try:
        print("list_tables")
        response = ts_write_client.list_tables(DatabaseName=database_name)
        print(response)
    except Exception as e:
        print(e)


async def write_values():
    print("write_values")
    records = [
        {
            "Dimensions": [{"Name": "location", "Value": "Example"}],
            "MeasureName": "Sample",
            "MeasureValue": "2.5",
            "MeasureValueType": "DOUBLE",
            "Time": "1615962288611",
            "TimeUnit": "MILLISECONDS",
        }
    ]

    try:
        response = ts_write_client.write_records(
            DatabaseName=database_name,
            TableName=table_name,
            Records=records,
        )
        print(response)
    except Exception as e:
        print(e)


async def read_values():
    print("read_values")
    query_string = (
            f'SELECT * FROM "{database_name}"."{table_name}"'
    )
    print(query_string)
    try:
        response = ts_query_client.query(
            QueryString=query_string, ClientToken=str(uuid4()), MaxRows=1
        )
        print(response)
    except Exception as e:
        print(e)


async def teardown_timestream():
    print("teardown_timestream")
    try:
        print("delete_table")
        response = ts_write_client.delete_table(
            DatabaseName=database_name, TableName=table_name,
        )
        print(response)
        print("sleep 5s...")
        await asyncio.sleep(5)
    except Exception as e:
        print(e)

    try:
        print("delete_database")
        response = ts_write_client.delete_database(DatabaseName=database_name)
        print(response)
    except Exception as e:
        print(e)


async def main():
    await setup_timestream()
    await write_values()
    await read_values()
    await teardown_timestream()


if __name__ == "__main__":
    asyncio.run(main())
```

Log when running above script agains Localstack:
```
setup_timestream
create_database
{'Database': {'Arn': 'TODO', 'DatabaseName': 'local_timestream_database'}, 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '71', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Wed, 17 Mar 2021 11:55:11 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
Sleep 5s...
create_table
{'Table': {'TableName': 'local_timestream_table', 'DatabaseName': 'local_timestream_database', 'RetentionProperties': {'MemoryStoreRetentionPeriodInHours': 12, 'MagneticStoreRetentionPeriodInDays': 30}}, 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '195', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Wed, 17 Mar 2021 11:55:16 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
Sleep 5s...
list_tables
An error occurred (InternalServiceError) when calling the ListTables operation: Error: Unable to find handler for action: Timestream_20181101.ListTables
write_values
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '3', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Wed, 17 Mar 2021 11:55:22 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
read_values
SELECT * FROM "local_timestream_database"."local_timestream_table"
An error occurred (InternalServiceError) when calling the Query operation (reached max retries: 4): InternalServiceError: relation "local_timestream_database.local_timestream_table" does not exist
LINE 1: SELECT * FROM "local_timestream_database"."local_timestream_...
                      ^

teardown_timestream
delete_table
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '3', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Wed, 17 Mar 2021 11:55:27 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
sleep 5s...
delete_database
An error occurred (InternalServiceError) when calling the DeleteDatabase operation: Error: Unable to find handler for action: Timestream_20181101.DeleteDatabase

```
...

**Comment by villekr** [comment]
I updated the script to include also query, which works against AWS.

**Comment by whummer** [comment]
Hi @villekr , thanks for reporting this issue. This should be fixed in the meantime - can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists. Thanks for your help!

**Comment by villekr** [comment]
```
import asyncio
from uuid import uuid4
import boto3


endpoint_url = "http://localhost:4566"  # set to None when accessing AWS
session = boto3.session.Session(region_name="eu-west-1")
ts_write_client = session.client(
    "timestream-write", endpoint_url=endpoint_url
)
ts_query_client = session.client(
    "timestream-query", endpoint_url=endpoint_url
)
database_name = "local_timestream_database"
table_name = "local_timestream_table"


async def setup_timestream():
    print("setup_timestream")
    try:
        print("create_database")
        response = ts_write_client.create_database(DatabaseName=database_name)
        print(response)
        print("Sleep 5s...")
        await asyncio.sleep(5)
    except Exception as e:
        print(e)

    try:
        print("create_table")
        response = ts_write_client.create_table(
            DatabaseName=database_name,
            TableName=table_name,
            RetentionProperties={
                "MemoryStoreRetentionPeriodInHours": 12,
                "MagneticStoreRetentionPeriodInDays": 30,
            },
        )
        print(response)
        print("Sleep 5s...")
        await asyncio.sleep(5)
    except Exception as e:
        print(e)

    try:
        print("list_tables")
        response = ts_write_client.list_tables(DatabaseName=database_name)
        print(response)
    except Exception as e:
        print(e)


async def write_values():
    print("write_values")
    records = [
        {
            "Dimensions": [{"Name": "location", "Value": "Example"}],
            "MeasureName": "Sample",
            "MeasureValue": "2.5",
            "MeasureValueType": "DOUBLE",
            "Time": "1615962288611",
            "TimeUnit": "MILLISECONDS",
        }
    ]

    try:
        response = ts_write_client.write_records(
            DatabaseName=database_name,
            TableName=table_name,
            Records=records,
        )
        print(response)
    except Exception as e:
        print(e)


async def read_values():
    print("read_values")
    query_string = (
            f'SELECT * FROM "{database_name}"."{table_name}"'
    )
    print(query_string)
    try:
        response = ts_query_client.query(
            QueryString=query_string, ClientToken=str(uuid4()), MaxRows=1
        )
        print(response)
    except Exception as e:
        print(e)


async def teardown_timestream():
    print("teardown_timestream")
    try:
        print("delete_table")
        response = ts_write_client.delete_table(
            DatabaseName=database_name, TableName=table_name,
        )
        print(response)
        print("sleep 5s...")
        await asyncio.sleep(5)
    except Exception as e:
        print(e)

    try:
        print("delete_database")
        response = ts_write_client.delete_database(DatabaseName=database_name)
        print(response)
    except Exception as e:
        print(e)


async def main():
    await setup_timestream()
    await write_values()
    await read_values()
    await teardown_timestream()


if __name__ == "__main__":
    asyncio.run(main())

"""
On 1st run it's almost ok, except the read_values part:

setup_timestream
create_database
{'Database': {'Arn': 'arn:aws:timestream:eu-west-1:000000000000:database/local_timestream_database', 'DatabaseName': 'local_timestream_database'}, 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '143', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Fri, 19 Mar 2021 07:39:59 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
Sleep 5s...
create_table
{'Table': {'Arn': 'arn:aws:timestream:eu-west-1:000000000000:database/local_timestream_database/table/local_timestream_table', 'TableName': 'local_timestream_table', 'DatabaseName': 'local_timestream_database', 'TableStatus': 'ACTIVE', 'RetentionProperties': {'MemoryStoreRetentionPeriodInHours': 12, 'MagneticStoreRetentionPeriodInDays': 30}, 'CreationTime': datetime.datetime(2021, 3, 19, 9, 40, 4, tzinfo=tzlocal()), 'LastUpdatedTime': datetime.datetime(2021, 3, 19, 9, 40, 4, tzinfo=tzlocal())}, 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '387', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Fri, 19 Mar 2021 07:40:04 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
Sleep 5s...
list_tables
{'Tables': [{'Arn': 'arn:aws:timestream:eu-west-1:000000000000:database/local_timestream_database/table/local_timestream_table', 'TableName': 'local_timestream_table', 'DatabaseName': 'local_timestream_database', 'TableStatus': 'ACTIVE', 'RetentionProperties': {'MemoryStoreRetentionPeriodInHours': 12, 'MagneticStoreRetentionPeriodInDays': 30}, 'CreationTime': datetime.datetime(2021, 3, 19, 9, 40, 4, tzinfo=tzlocal()), 'LastUpdatedTime': datetime.datetime(2021, 3, 19, 9, 40, 4, tzinfo=tzlocal())}], 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '390', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Fri, 19 Mar 2021 07:40:09 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
write_values
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '3', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Fri, 19 Mar 2021 07:40:09 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
read_values
SELECT * FROM "local_timestream_database"."local_timestream_table"
An error occurred (InternalServiceError) when calling the Query operation (reached max retries: 4): InternalServiceError: relation "local_timestream_table" does not exist
LINE 1: SELECT * FROM local_timestream_table
                      ^

teardown_timestream
delete_table
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '3', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Fri, 19 Mar 2021 07:40:15 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
sleep 5s...
delete_database
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '3', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Fri, 19 Mar 2021 07:40:20 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}

On 2nd run (without taking localstack down) I get the following:

setup_timestream
create_database
An error occurred (InternalServiceError) when calling the CreateDatabase operation (reached max retries: 4): InternalServiceError: {'S': 'ERROR', 'V': 'ERROR', 'C': '42P04', 'M': 'database "local_timestream_database" already exists', 'F': 'dbcommands.c', 'L': '489', 'R': 'createdb'}
create_table
An error occurred (ResourceNotFoundError) when calling the CreateTable operation: Database "local_timestream_database" does not exist
list_tables
An error occurred (ResourceNotFoundError) when calling the ListTables operation: Database "local_timestream_database" does not exist
write_values
An error occurred (ResourceNotFoundError) when calling the WriteRecords operation: Database "local_timestream_database" does not exist
read_values
SELECT * FROM "local_timestream_database"."local_timestream_table"
An error occurred (InternalServiceError) when calling the Query operation (reached max retries: 4): InternalServiceError: relation "local_timestream_table" does not exist
LINE 1: SELECT * FROM local_timestream_table
                      ^

teardown_timestream
delete_table
An error occurred (ResourceNotFoundError) when calling the DeleteTable operation: Database "local_timestream_database" does not exist
delete_database
An error occurred (ResourceNotFoundError) when calling the DeleteDatabase operation: Database "local_timestream_database" does not exist
"""
```

**Comment by villekr** [comment]
Still doesn't quite work. In order to rely on Localstack Timestream during integration tests then the following are mandatory (without taking down localstack container):
* Create Timestream database
* Create Timestream table for database
* Delete Timestream table from database
* Delete Timestream database
* Write records to Timestream table

**Comment by villekr** [comment]
```
import asyncio
from uuid import uuid4
import boto3


endpoint_url = "http://localhost:4566"  # set to None when accessing AWS
session = boto3.session.Session(region_name="eu-west-1")
ts_write_client = session.client(
    "timestream-write", endpoint_url=endpoint_url
)
ts_query_client = session.client(
    "timestream-query", endpoint_url=endpoint_url
)
database_name = "local_timestream_database"
table_name = "local_timestream_table"


async def setup_timestream():
    print("setup_timestream")
    database_exists = None
    try:
        print("list_databases")
        response = ts_write_client.list_databases()
        if response and "Databases" in response and len(response["Databases"]) > 0:
            for item in response["Databases"]:
                if item["DatabaseName"] == database_name:
                    print(f"database already exists")
                    database_exists = True
        if not database_exists:
            print("create_database")
            response = ts_write_client.create_database(DatabaseName=database_name)
            print(response)
            print("Sleep 5s...")
            await asyncio.sleep(5)
    except Exception as e:
        print(e)

    table_exists = None
    try:
        print("list_tables")
        response = ts_write_client.list_tables(DatabaseName=database_name)
        if response and "Tables" in response and len(response["Tables"]) > 0:
            for item in response["Tables"]:
                if item["TableName"] == database_name:
                    print(f"table already exists")
                    table_exists = True
        if not table_exists:
            print("create_table")
            response = ts_write_client.create_table(
                DatabaseName=database_name,
                TableName=table_name,
                RetentionProperties={
                    "MemoryStoreRetentionPeriodInHours": 12,
                    "MagneticStoreRetentionPeriodInDays": 30,
                },
            )
            print(response)
            print("Sleep 5s...")
            await asyncio.sleep(5)
    except Exception as e:
        print(e)


async def write_values():
    print("write_values")
    records = [
        {
            "Dimensions": [{"Name": "location", "Value": "Example"}],
            "MeasureName": "Sample",
            "MeasureValue": "2.5",
            "MeasureValueType": "DOUBLE",
            "Time": "1615962288611",
            "TimeUnit": "MILLISECONDS",
        }
    ]

    try:
        response = ts_write_client.write_records(
            DatabaseName=database_name,
            TableName=table_name,
            Records=records,
        )
        print(response)
    except Exception as e:
        print(e)


async def read_values():
    print("read_values")
    query_string = (
            f'SELECT * FROM "{database_name}"."{table_name}"'
    )
    print(query_string)
    try:
        response = ts_query_client.query(
            QueryString=query_string, ClientToken=str(uuid4()), MaxRows=1
        )
        print(response)
    except Exception as e:
        print(e)


async def teardown_timestream():
    print("teardown_timestream")
    try:
        print("delete_table")
        response = ts_write_client.delete_table(
            DatabaseName=database_name, TableName=table_name,
        )
        print(response)
        print("sleep 5s...")
        await asyncio.sleep(5)
    except Exception as e:
        print(e)

    try:
        print("delete_database")
        response = ts_write_client.delete_database(DatabaseName=database_name)
        print(response)
    except Exception as e:
        print(e)


async def main():
    await setup_timestream()
    await write_values()
    await read_values()
    await teardown_timestream()


if __name__ == "__main__":
    asyncio.run(main())


"""
setup_timestream
list_databases
An error occurred (InternalServiceError) when calling the ListDatabases operation: Error: Unable to find handler for action: Timestream_20181101.ListDatabases
list_tables
An error occurred (ResourceNotFoundError) when calling the ListTables operation: Database "local_timestream_database" does not exist
write_values
An error occurred (ResourceNotFoundError) when calling the WriteRecords operation: Database "local_timestream_database" does not exist
read_values
SELECT * FROM "local_timestream_database"."local_timestream_table"
An error occurred (InternalServiceError) when calling the Query operation (reached max retries: 4): InternalServiceError: relation "local_timestream_table" does not exist
LINE 1: SELECT * FROM local_timestream_table
                      ^

teardown_timestream
delete_table
An error occurred (ResourceNotFoundError) when calling the DeleteTable operation: Database "local_timestream_database" does not exist
delete_database
An error occurred (ResourceNotFoundError) when calling the DeleteDatabase operation: Database "local_timestream_database" does not exist
"""
```

**Comment by villekr** [comment]
I also updated the script the check database and table existence before creating them but that doesn't either quite work.

**Comment by whummer** [comment]
Thanks for the update, this should be fixed in the meantime - can you please give it another try with the `latest` image? (Happy to continue the conversation over on Slack..). Thanks for your help!

**Comment by villekr** [comment]
Some progress but still not there. When running the script 1st time it's fine. But running it immediately again will produce errors i.e. Localstack Timestream is still unusable to developing and testing locally.

LocalStack version: 0.12.9.1
LocalStack build date: 2021-03-31
LocalStack build git hash: 118d0c3

```
import asyncio
from uuid import uuid4
import boto3


endpoint_url = "http://localhost:4566"  # set to None when accessing AWS
session = boto3.session.Session(region_name="eu-west-1")
ts_write_client = session.client(
    "timestream-write", endpoint_url=endpoint_url
)
ts_query_client = session.client(
    "timestream-query", endpoint_url=endpoint_url
)
database_name = "local_timestream_database"
table_name = "local_timestream_table"


async def setup_timestream():
    print("setup_timestream")
    database_exists = None
    try:
        print("list_databases")
        response = ts_write_client.list_databases()
        if response and "Databases" in response and len(response["Databases"]) > 0:
            for item in response["Databases"]:
                if item["DatabaseName"] == database_name:
                    print(f"database already exists")
                    database_exists = True
        if not database_exists:
            print("create_database")
            response = ts_write_client.create_database(DatabaseName=database_name)
            print(response)
            print("Sleep 5s...")
            await asyncio.sleep(5)
    except Exception as e:
        print(e)

    table_exists = None
    try:
        print("list_tables")
        response = ts_write_client.list_tables(DatabaseName=database_name)
        if response and "Tables" in response and len(response["Tables"]) > 0:
            for item in response["Tables"]:
                if item["TableName"] == database_name:
                    print(f"table already exists")
                    table_exists = True
        if not table_exists:
            print("create_table")
            response = ts_write_client.create_table(
                DatabaseName=database_name,
                TableName=table_name,
                RetentionProperties={
                    "MemoryStoreRetentionPeriodInHours": 12,
                    "MagneticStoreRetentionPeriodInDays": 30,
                },
            )
            print(response)
            print("Sleep 5s...")
            await asyncio.sleep(5)
    except Exception as e:
        print(e)


async def write_values():
    print("write_values")
    records = [
        {
            "Dimensions": [{"Name": "location", "Value": "Example"}],
            "MeasureName": "Sample",
            "MeasureValue": "2.5",
            "MeasureValueType": "DOUBLE",
            "Time": "1615962288611",
            "TimeUnit": "MILLISECONDS",
        }
    ]

    try:
        response = ts_write_client.write_records(
            DatabaseName=database_name,
            TableName=table_name,
            Records=records,
        )
        print(response)
    except Exception as e:
        print(e)


async def read_values():
    print("read_values")
    query_string = (
            f'SELECT * FROM "{database_name}"."{table_name}"'
    )
    print(query_string)
    try:
        response = ts_query_client.query(
            QueryString=query_string, ClientToken=str(uuid4()), MaxRows=1
        )
        print(response)
    except Exception as e:
        print(e)


async def teardown_timestream():
    print("teardown_timestream")
    try:
        print("delete_table")
        response = ts_write_client.delete_table(
            DatabaseName=database_name, TableName=table_name,
        )
        print(response)
        print("sleep 5s...")
        await asyncio.sleep(5)
    except Exception as e:
        print(e)

    try:
        print("delete_database")
        response = ts_write_client.delete_database(DatabaseName=database_name)
        print(response)
    except Exception as e:
        print(e)


async def main():
    await setup_timestream()
    await write_values()
    await read_values()
    await teardown_timestream()


if __name__ == "__main__":
    asyncio.run(main())

"""
Log output

1st run:
setup_timestream
list_databases
create_database
{'Database': {'Arn': 'arn:aws:timestream:eu-west-1:000000000000:database/local_timestream_database', 'DatabaseName': 'local_timestream_database'}, 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '143', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Wed, 31 Mar 2021 16:19:06 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
Sleep 5s...
list_tables
create_table
{'Table': {'Arn': 'arn:aws:timestream:eu-west-1:000000000000:database/local_timestream_database/table/local_timestream_table', 'TableName': 'local_timestream_table', 'DatabaseName': 'local_timestream_database', 'TableStatus': 'ACTIVE', 'RetentionProperties': {'MemoryStoreRetentionPeriodInHours': 12, 'MagneticStoreRetentionPeriodInDays': 30}, 'CreationTime': datetime.datetime(2021, 3, 31, 19, 19, 12, tzinfo=tzlocal()), 'LastUpdatedTime': datetime.datetime(2021, 3, 31, 19, 19, 12, tzinfo=tzlocal())}, 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '387', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Wed, 31 Mar 2021 16:19:12 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
Sleep 5s...
write_values
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '3', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Wed, 31 Mar 2021 16:19:17 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
read_values
SELECT * FROM "local_timestream_database"."local_timestream_table"
{'QueryId': 'fb6a7497', 'Rows': [{'Data': [{'ScalarValue': '2021-03-17T06:24:48.000Z'}, {'ScalarValue': 'Sample'}, {'ScalarValue': 2.5}, {'ScalarValue': 'Example'}]}], 'ColumnInfo': [{'Name': 'time', 'Type': {'ScalarType': 1114}}, {'Name': 'measure_name', 'Type': {'ScalarType': 1043}}, {'Name': 'measure_value', 'Type': {'ScalarType': 1700}}, {'Name': 'location', 'Type': {'ScalarType': 1043}}], 'QueryStatus': {'ProgressPercentage': 100}, 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '406', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Wed, 31 Mar 2021 16:19:17 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
teardown_timestream
delete_table
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '3', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Wed, 31 Mar 2021 16:19:17 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}
sleep 5s...
delete_database
{'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'content-type': 'application/json', 'content-length': '3', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH', 'access-control-allow-headers': 'authorization,content-type,content-length,content-md5,cache-control,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent,x-amz-target,x-amz-acl,x-amz-version-id,x-localstack-target,x-amz-tagging', 'access-control-expose-headers': 'x-amz-version-id', 'connection': 'close', 'date': 'Wed, 31 Mar 2021 16:19:22 GMT', 'server': 'hypercorn-h11'}, 'RetryAttempts': 0}}

---

2nd run:
setup_timestream
list_databases
create_database
An error occurred (InternalServiceError) when calling the CreateDatabase operation (reached max retries: 4): InternalServiceError: {'S': 'ERROR', 'V': 'ERROR', 'C': '42P04', 'M': 'database "local_timestream_database" already exists', 'F': 'dbcommands.c', 'L': '489', 'R': 'createdb'}
list_tables
An error occurred (ResourceNotFoundError) when calling the ListTables operation: Database "local_timestream_database" does not exist
write_values
An error occurred (ResourceNotFoundError) when calling the WriteRecords operation: Database "local_timestream_database" does not exist
read_values
SELECT * FROM "local_timestream_database"."local_timestream_table"
An error occurred (InternalServiceError) when calling the Query operation (reached max retries: 4): InternalServiceError: relation "local_timestream_table" does not exist
LINE 1: SELECT * FROM local_timestream_table
                      ^

teardown_timestream
delete_table
An error occurred (ResourceNotFoundError) when calling the DeleteTable operation: Database "local_timestream_database" does not exist
delete_database
An error occurred (ResourceNotFoundError) when calling the DeleteDatabase operation: Database "local_timestream_database" does not exist
"""
```

**Comment by whummer** [comment]
Hi @villekr , thanks for the update, and apologies for the delay. This should be (hopefully) fixed in the meantime - can you please give it another try with the `latest` version of the Docker image? Please keep us posted how it goes, thanks!
