### ISSUE TITLE
Unable to run lambda

### ISSUE THREAD

**Issue by Surfoo** [localstack/localstack#377]
Hello,

I tried to run a simple example of lambda function like this one : 

> exports.handler = function(event, context) {
    console.log('hello');
}

And I got this error message : 

> fake-aws_1            | 2017-10-06T09:50:29:WARNING:localstack.services.awslambda.lambda_api: Error executing Lambda function: Lambda process returned error status code: 1. Output:
fake-aws_1            | START RequestId: da7a853e-4fc7-102a-8d48-3b476d75f3e5 Version: $LATEST
fake-aws_1            | Unable to parse input as json: Unexpected token ' in JSON at position 681: SyntaxError
fake-aws_1            |     at Object.parse (native)
fake-aws_1            | END RequestId: da7a853e-4fc7-102a-8d48-3b476d75f3e5
fake-aws_1            | REPORT RequestId: da7a853e-4fc7-102a-8d48-3b476d75f3e5	Duration: 4.65 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 28 MB	
fake-aws_1            |  Traceback (most recent call last):
fake-aws_1            |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 328, in run_lambda
fake-aws_1            |     result, log_output = run_lambda_executor(cmd, env_vars)
fake-aws_1            |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 414, in run_lambda_executor
fake-aws_1            |     (return_code, log_output))
fake-aws_1            | Exception: Lambda process returned error status code: 1. Output:
fake-aws_1            | START RequestId: da7a853e-4fc7-102a-8d48-3b476d75f3e5 Version: $LATEST
fake-aws_1            | Unable to parse input as json: Unexpected token ' in JSON at position 681: SyntaxError
fake-aws_1            |     at Object.parse (native)
fake-aws_1            | END RequestId: da7a853e-4fc7-102a-8d48-3b476d75f3e5
fake-aws_1            | REPORT RequestId: da7a853e-4fc7-102a-8d48-3b476d75f3e5	Duration: 4.65 ms	Billed Duration: 100 ms	Memory Size: 1536 MB	Max Memory Used: 28 MB
fake-aws_1            | 2017-10-06T09:50:29:WARNING:localstack.services.awslambda.lambda_api: Unable to run Lambda function on SNS message: working outside of application context Traceback (most recent call last):
fake-aws_1            |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 176, in process_sns_notification
fake-aws_1            |     run_lambda(lambda_function, event=event, context={}, func_arn=func_arn)
fake-aws_1            |   File "/opt/code/localstack/localstack/utils/cloudwatch/cloudwatch_util.py", line 108, in wrapped
fake-aws_1            |     raise e
fake-aws_1            | RuntimeError: working outside of application context

The lambda should run after a notification from SNS, but I didn't how to solve this issue.

Let me know if you want more informations.

**Comment by whummer** [comment]
Thanks for reporting @Surfoo . How are you invoking your Lambda, looks like there is a JSON syntax problem in the payload:
```
fake-aws_1 | Unable to parse input as json: Unexpected token ' in JSON at position 681: SyntaxError
```

**Comment by Surfoo** [comment]
The lambda is invoked with a sns subscription to the lambda : 

> aws --endpoint-url=http://fake-aws:4575 sns subscribe --topic-arn arn:aws:sns:eu-west-1:123456789012:morpheus-input --protocol lambda --notification-endpoint arn:aws:lambda:eu-west-1:000000000000:function:input-indexer;

IMO, the error is: 
> Unable to run Lambda function on SNS message: working outside of application context 

It's not a JSON answer, then I got the `Unable to parse input as json`

**Comment by whummer** [comment]
Ok, I see. Can you please post the message that gets sent to SNS (which then triggers the Lambda)? We need to create a repeatable test case to make it easier to debug and fix. Thanks

**Comment by Surfoo** [comment]
Here the json:
`{"content":{"test":1323},"attributes":{"stream_ad_id":1507296689784,"stream_external_ad_id":"azerty","stream_step":1,"stream_action":"new","stream_reception_time":1503065816,"stream_action_time":1503065816,"stream_partner_name":"azerty","stream_site_name":"azerty","stream_vertical":"job","stream_version":"v2","stream_status":"INPUT_TRANSFORMATION","stream_contract_number":"azerty","receipt":""},"errors":null}`

**Comment by Surfoo** [comment]
The issue is related to Elastisearch used in the lambda.
Here the error : 
> START RequestId: 1177ce0f-42cf-1760-4be1-42ee327e36ef Version: $LATEST
fake-aws_1            | 2017-10-09T12:17:48.528Z	1177ce0f-42cf-1760-4be1-42ee327e36ef	Error: Error: getaddrinfo ENOTFOUND fake-aws fake-aws:4571
fake-aws_1            | 2017-10-09T12:17:48.530Z	1177ce0f-42cf-1760-4be1-42ee327e36ef	{"errorMessage":"Lambda failed with error Error: getaddrinfo ENOTFOUND fake-aws fake-aws:4571"}
fake-aws_1            | END RequestId: 1177ce0f-42cf-1760-4be1-42ee327e36ef
fake-aws_1            | REPORT RequestId: 1177ce0f-42cf-1760-4be1-42ee327e36ef	Duration: 233.00 ms	Billed Duration: 300 ms	Memory Size: 1536 MB	Max Memory Used: 43 MB	
fake-aws_1            |  Traceback (most recent call last):
fake-aws_1            |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 328, in run_lambda
fake-aws_1            |     result, log_output = run_lambda_executor(cmd, env_vars)
fake-aws_1            |   File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 414, in run_lambda_executor
fake-aws_1            |     (return_code, log_output))
fake-aws_1            | Exception: Lambda process returned error status code: 1. Output:
fake-aws_1            | START RequestId: 1177ce0f-42cf-1760-4be1-42ee327e36ef Version: $LATEST
fake-aws_1            | 2017-10-09T12:17:48.528Z	1177ce0f-42cf-1760-4be1-42ee327e36ef	Error: Error: getaddrinfo ENOTFOUND fake-aws fake-aws:4571
fake-aws_1            | 2017-10-09T12:17:48.530Z	1177ce0f-42cf-1760-4be1-42ee327e36ef	{"errorMessage":"Lambda failed with error Error: getaddrinfo ENOTFOUND fake-aws fake-aws:4571"}

and here the code of the lambda: 

https://pastebin.com/8PqKnxB5

The lambda can't send data to the Elasticsearch. Without the call to postToES(), it works and I have this result: 
> {
    "StatusCode": 200
}

And I have a question, what's the difference between Elasticsearch (port 4571) and Elasticsearch service (port 4578)?

**Comment by whummer** [comment]
Which command do you use to start LocalStack, and how do you create and invoke your Lambda - I'm assuming you're running in docker-compose with `LAMBDA_EXECUTOR=docker`, and that your code sets the environment variable `endpoint` to `fake-aws`, correct?

The problem is that if Lambdas are executed in Docker (`LAMBDA_EXECUTOR=docker`), each function is running in a separate container which is not part of the docker-compose stack, and hence cannot access its network.

We have the special purpose environment variable `LOCALSTACK_HOSTNAME`, see [README](https://github.com/localstack/localstack#configurations). Can you try using that as the endpoint for Elasticsearch?

The difference between ES and Elasticsearch is: ES is the API that allows to create Elasticsearch domains, manage cluster configuration etc., and Elasticsearch (port 4571) is the actual Elasticsearch database endpoint. In other words, LocalStack currently only supports a single domain and it always runs on the same port (4571).

**Comment by Surfoo** [comment]
Yes, I use `LAMBDA_EXECUTOR=docker` and `fake-aws` as endpoint.

Thanks for pointing me the `LOCALSTACK_HOSTNAME`. I set this env var to `fake-aws` but didn't work.

Here my config: https://pastebin.com/U6mwvz42

The normal process run a go program and call the publish method for SNS, but I tried just with:

> aws lambda invoke --endpoint-url=http://localhost:4574 --function-name input-indexer --payload '{"Records":[{"Sns":{"Messsage":{"content":"test"}}}]}' result.log

and I got the same error (and the same with the go process):

> An error occurred (InternalFailure) when calling the Invoke operation (reached max retries: 4): Error executing Lambda function: Lambda process returned error status code: 1. Output:
START RequestId: 08df0045-63e2-12b4-f510-1c77d66d61cb Version: $LATEST
2017-10-09T14:10:04.736Z	08df0045-63e2-12b4-f510-1c77d66d61cb	Error: Error: getaddrinfo ENOTFOUND fake-aws fake-aws:4571
2017-10-09T14:10:04.738Z	08df0045-63e2-12b4-f510-1c77d66d61cb	{"errorMessage":"Lambda failed with error Error: getaddrinfo ENOTFOUND fake-aws fake-aws:4571"}
END RequestId: 08df0045-63e2-12b4-f510-1c77d66d61cb
REPORT RequestId: 08df0045-63e2-12b4-f510-1c77d66d61cb	Duration: 284.74 ms	Billed Duration: 300 ms	Memory Size: 1536 MB	Max Memory Used: 41 MB	
 Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 328, in run_lambda
    result, log_output = run_lambda_executor(cmd, env_vars)
  File "/opt/code/localstack/localstack/services/awslambda/lambda_api.py", line 414, in run_lambda_executor
    (return_code, log_output))
Exception: Lambda process returned error status code: 1. Output:
START RequestId: 08df0045-63e2-12b4-f510-1c77d66d61cb Version: $LATEST
2017-10-09T14:10:04.736Z	08df0045-63e2-12b4-f510-1c77d66d61cb	Error: Error: getaddrinfo ENOTFOUND fake-aws fake-aws:4571
2017-10-09T14:10:04.738Z	08df0045-63e2-12b4-f510-1c77d66d61cb	{"errorMessage":"Lambda failed with error Error: getaddrinfo ENOTFOUND fake-aws fake-aws:4571"}
END RequestId: 08df0045-63e2-12b4-f510-1c77d66d61cb
REPORT RequestId: 08df0045-63e2-12b4-f510-1c77d66d61cb	Duration: 284.74 ms	Billed Duration: 300 ms	Memory Size: 1536 MB	Max Memory Used: 41 MB

**Comment by whummer** [comment]
Sorry for not being clear - `LOCALSTACK_HOSTNAME` is a read-only variable that contains the host or IP address of LocalStack. Instead of setting it to `fake-aws` you can use its value in your application code.

**Comment by Surfoo** [comment]
Oh ok, no problem :)

I updated the code with:

> // Only for Docker to push to ES
if (process.env.LOCALSTACK_HOSTNAME !== 'undefined') {
    process.env.endpoint = 'http://' + process.env.LOCALSTACK_HOSTNAME + ':4571';
}
let aws = require('aws-sdk'),
    path = require('path'),
    endpoint = new aws.Endpoint(process.env.endpoint),
    creds = new aws.EnvironmentCredentials('AWS');

But I have a timeout in the debug log:

> botocore.vendored.requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=4574): Read timed out. (read timeout=60)

**Comment by Surfoo** [comment]
do you have any ideas about this timeout @whummer ?
I still have this issue with localstack 0.8.2.

**Comment by whummer** [comment]
This error is related to another issue here: https://github.com/localstack/localstack/issues/381 Unfortunately, we currently have not solved the issue of connecting from a Lambda running in Docker (when using the `LAMBDA_EXECUTOR=docker` configuration) to the LocalStack services running in docker-compose. We need to look into the network configuration to make sure the Lambda containers are part of the same network as the `docker-compose` stack.

**Comment by DannyRyman** [comment]
Am I correct in saying that this issue prevents Lambda functions running in docker from accessing any of the other localstack services? If so, this is unusable for the current function I am working on. Does anyone have any suggestions for a work around for this? Would it be possible to pass a network (based on say an environment variable) to the --network flag when creating the containers as a temporary work around?

**Comment by mikebrules** [comment]
hi @DannyRyman  - we are passing localstack elasticsearch urls to the Lambdas in localstack - in our case the IP we pass is the docker host, but it should be possible to use LOCALSTACK_HOSTNAME too - I will try later on our stack. In case it helps, we pass ENVs to the function as follows;

    awslocal lambda create-function --function-name dynamo-to-elastic-publications --zip-file fileb://build/dynamo-to-elastic-publications.zip --handler index.handler --environment "Variables={PRIMARY_ELASTIC_HOST=10.0.2.15,PRIMARY_ELASTIC_PORT=4571,SECONDARY_ELASTIC_HOST=10.0.2.15,SECONDARY_ELASTIC_PORT=4571, ENV=LOCAL}" --runtime 'nodejs6.10'   --role admin

**Comment by DannyRyman** [comment]
Thanks @mikebrules - What Lambda execution mode are you using? I think you misunderstood my problem (either that or I've misunderstood your solution ;)). Because we are using node and local execution mode is not supported, we are using docker execution mode which spins up a new docker instance to run the Lambda. Unfortunately, the spawned docker instance does not appear to have access to the other LocalStack services which we started using docker-compose. This is stopping us from running and testing our Lambda as it needs access to the other LocalStack services.

**Comment by mikebrules** [comment]
@DannyRyman yes, we are using docker execution mode. We are accessing ElasticSearch and Dynamo (both running in Localstack) by using the snippet I added above. I think that is what you are aiming to do?

**Comment by mcosta91** [comment]
Hey @DannyRyman, did you find any solution for this? Your hypothetical workaround (the --network thing) looks interesting.

**Comment by gadgetjunkie** [comment]
fyi The latest version of my repo with the pull request can be pulled from the docker registry as gadgetjunkie/localstack.

Let me know if you have any questions regarding the pull request changes.  The main purpose of the changes was to address the very situation you are encountering -- the need to allow lambda functions to communicate with services running in the non-default docker network.  We have some lambdas in our environment that are running on specific vpc subnets on aws, and we can now simulate that with the changes in the pr.

**Comment by andycmaj** [comment]
note, if you use `docker-reuse`, you can link the lambda docker container (in re-use mode only) to the docker-compose default network by doing `docker network connect local_default <lambda container id> --link localstack`

**Comment by Ovski4** [comment]
@andycmaj thank you for your answer, it pointed me in the right direction.

If it can help someone else, I updated the **docker-compose.yml** file by adding a service that listen to docker events and connect the lambda containers to the **local_default** network automatically (the network name could be different)

Here is the service in **docker-compose.yml**

```
services:

  localstack:
    ...

  docker-events-listener:
    build:
      context: build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
```

Here is the **Dockerfile** in the build folder

```
FROM docker:18.06.0-ce
RUN apk add --no-cache bash
COPY listen-docker-events.sh /var/listen-docker-events.sh
CMD ["/bin/bash", "/var/listen-docker-events.sh"]
```

Here is the content of **listen-docker-events.sh** in the build folder

```
#!/bin/bash

docker events --filter 'event=create' --filter 'type=container' --format '{{.Actor.Attributes.name}}' | while read container_name

do
    echo "$container_name was created"

    # Connect any container whose name contains localstack_lambda_ to the local_default network
    if [[ $container_name = *"localstack_lambda_"* ]]; then
        docker network connect localstack_default $container_name --link localstack
        echo "The container $container_name is now connected to the local_default network"
    fi
done

```

**Comment by whummer** [comment]
Closing this issues as fixed/outdated. Please refer to the README for the `LOCALSTACK_HOSTNAME`, `DOCKER_FLAGS` and `LAMBDA_DOCKER_NETWORK` configuration variables.

**Comment by machnicki** [comment]
I had also problems with connect localstack Lambda to localstack DynamoDB

I was running `LAMBDA_EXECUTOR=docker localstack start` (I did install localstack via pip).

Problem has gone, when I download repo and run 
`TMPDIR=/private$TMPDIR LAMBDA_EXECUTOR=docker docker-compose up`
 from localstack directory

**Comment by ambreenshameem** [comment]
> This error is related to another issue here: #381 Unfortunately, we currently have not solved the issue of connecting from a Lambda running in Docker (when using the `LAMBDA_EXECUTOR=docker` configuration) to the LocalStack services running in docker-compose. We need to look into the network configuration to make sure the Lambda containers are part of the same network as the `docker-compose` stack.

Is this issue resolved? i am running into the exact same problem

**Comment by whummer** [comment]
@ambreenshameem Which endpoint URL are you using in your AWS SDK clients from your Lambdas? Please note that `http://localhost:xxxx` is *not* working - please use `http://$LOCALSTACK_HOSTNAME:xxxx` instead (see README for more details). Thanks

**Comment by ambreenshameem** [comment]
@whummer  - code snippet 

package lambda;

import java.io.IOException;
import java.io.InputStream;
import java.util.List;
import java.util.Map;

import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder.EndpointConfiguration;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.AmazonDynamoDBClientBuilder;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper;
import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import com.amazonaws.services.lambda.runtime.events.S3Event;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;
import com.amazonaws.services.s3.model.GetObjectRequest;
import com.amazonaws.services.s3.model.S3Object;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.type.CollectionType;
import com.fasterxml.jackson.databind.type.TypeFactory;

import model.PersonDetailsVo;

public class S3EventHandler implements RequestHandler<S3Event, String> {

	@Override
	public String handleRequest(S3Event event, Context context) {
		System.out.println("------->> Lambda INvoked---------------------");

		Map<String, String> environment = System.getenv();
		context.getLogger().log("Received event: " + event);

		// Get the object from the event and show its content type
		String bucket = event.getRecords().get(0).getS3().getBucket().getName();
		String key = event.getRecords().get(0).getS3().getObject().getKey();

		S3Object response = getAmazonS3(environment, context).getObject(new GetObjectRequest(bucket, key));
		InputStream objectContent = response.getObjectContent();
		ObjectMapper mapper = new ObjectMapper();
		try {
			CollectionType typeReference = TypeFactory.defaultInstance().constructCollectionType(List.class,
					PersonDetailsVo.class);
			List<PersonDetailsVo> personDetailsVo = mapper.readValue(objectContent, typeReference);
			context.getLogger().log(personDetailsVo.toString());
			saveToDynamo(personDetailsVo, environment, context);
		} catch (IOException e) {
			e.printStackTrace();
			context.getLogger().log(e.getMessage());
		}
		String contentType = response.getObjectMetadata().getContentType();
		context.getLogger().log("CONTENT TYPE: " + contentType);
		System.out.println("-------->> Lambda finished execution---------------");
		return contentType;
	}

	private void saveToDynamo(List<PersonDetailsVo> personDetailsVo, Map<String, String> environment, Context context) {
		AmazonDynamoDB client = getAmazonDynamoDB(environment, context);
		DynamoDBMapper mapper = new DynamoDBMapper(client);
		mapper.batchSave(personDetailsVo);
	}

	private AmazonS3 getAmazonS3(Map<String, String> environment, Context context) {
		String profile = environment.get("PROFILE");
		context.getLogger().log("Profile is: " + profile);
		if ("LOCAL".equals(profile)) {
			BasicAWSCredentials creds = new BasicAWSCredentials("test", "test");
			AmazonS3ClientBuilder standard = AmazonS3ClientBuilder.standard();
			String s3Endpoint = environment.get("LOCALSTACK_HOSTNAME");

			EndpointConfiguration configuration = new EndpointConfiguration("http://" + s3Endpoint + ":4566",
					"us-east-1");
			standard.withEndpointConfiguration(configuration);
			standard.withPathStyleAccessEnabled(true);
			standard.withCredentials(new AWSStaticCredentialsProvider(creds));
			return standard.build();
		}
		context.getLogger().log("After if of amazon: " + profile);
		return AmazonS3ClientBuilder.standard().build();
	}

	private AmazonDynamoDB getAmazonDynamoDB(Map<String, String> environment,Context context) {
		String profile = environment.get("PROFILE");
		context.getLogger().log("Profile is: " + profile);
		if ("LOCAL".equals(profile)) {
			BasicAWSCredentials creds = new BasicAWSCredentials("test", "test");
			String dynamoEndPoint = environment.get("LOCALSTACK_HOSTNAME");
			AmazonDynamoDBClientBuilder standard = AmazonDynamoDBClientBuilder.standard();
			EndpointConfiguration configuration = new EndpointConfiguration("http://" + dynamoEndPoint + ":4566",
					"us-east-1");
			standard.withEndpointConfiguration(configuration);
			standard.withCredentials(new AWSStaticCredentialsProvider(creds));
			return standard.build();
		}

		context.getLogger().log("After if in dynamo block: " + profile);
		return AmazonDynamoDBClientBuilder.standard().build();
	}
}

**Comment by gabp** [comment]
@Ovski4 Your solution saves the day.  Thanks a lot!

**Comment by Ovski4** [comment]
@gabp You are welcome, but hopefully you should not need this fix anymore! Have a look at the `LAMBDA_DOCKER_NETWORK` env variable in the README (https://github.com/localstack/localstack/issues/377#issuecomment-473751178)
