### ISSUE TITLE
SubscribeToShardEvent.continuationSequenceNumber() returns null on every event on Kinesis

### ISSUE THREAD

**Issue by wem** [localstack/localstack#3822]
[x] bug report
[ ] feature request

# Detailed description

The continuationSequenceNumber() on every SubscribeToShardEvent returns null. This makes it hard to test enhanced fan-out with Localstack. As the continuationSequenceNumber() should return null only in the case if the corresponding shard was involved in a resharding.

## Expected behavior

The continuationSequenceNumber() should return the sequence number of the next record on the shard (or of the latest record in the event if there is no record left on the shard), except the shard get resharded.

## Actual behavior

The continuationSequenceNumber() on every SubscribeToShardEvent returns null.

## Workaround

To determine if a shard got resharded, it's possible to check the ending sequence number. If it's not null the shard did end (got resharded).

```kotlin
shard.sequenceNumberRange().endingSequenceNumber() != null
```

Localstack version: 0.12.9.1
AWS SDK V2 Java: 2.16.19

**Comment by aliaksei-sych** [comment]
Localstack version: 0.12.9.1
AWS SDK V2 Java: 2.16.18

It totally blocks usage of enhanced fanout feature, we are using kcl 2.0 enhanced fanout, aws checks if this field is null then throws exception
https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/fanout/FanOutRecordsPublisher.java#L489

**Comment by sjmittal-plenty** [comment]
Any idea when the fix of this would be available. Is there any workaround we can do in the meantime.

**Comment by pinzon** [comment]
Hi, sorry for the delay, in a moment I'm gonna take a look so tomorrow should be fixed.

**Comment by wem** [comment]
We dont use KCL but according the code mentioned by @aliaksei-sych. The method `isValidResult` will still fail on resharding as ChildShards would always be empty and this is not expected when continuationSequenceNumber is empty / null.

So, handling resharding would still only be possible with additional describeStream / listShard requests.
