### ISSUE TITLE
CloudWatch listener returns Internal Server Error

### ISSUE THREAD

**Issue by mathewmarcus** [localstack/localstack#457]
Attempting to access the CloudWatch service at port 4582 returns `HTTP/1.0 500 INTERNAL SERVER ERROR`

**Steps to reproduce**

```
$ localstack start
$ curl http://127.0.0.1:4582
```

this returns

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
```

**Comment by ivica-k** [comment]
Looked into this a bit, and I saw that several other services were affected as well, such as `cloudformation` and `ses`.

Running
```
bin/moto_server cloudwatch -p 4582 -H 0.0.0.0
```
shows what's wrong
```
  File "PATH/venv/lib/python3.6/site-packages/moto/core/responses.py", line 182, in _dispatch
    return self.call_action()
  File "PATH/venv/lib/python3.6/site-packages/moto/core/responses.py", line 251, in call_action
    action = camelcase_to_underscores(self._get_action())
  File "PATH/venv/lib/python3.6/site-packages/moto/core/utils.py", line 22, in camelcase_to_underscores
    for index, char in enumerate(argument):
TypeError: 'NoneType' object is not iterable
```

**Comment by opb-bbeach** [comment]
It looks like this was fixed in moto earlier this month.

https://github.com/spulec/moto/commit/81f3cbb54880bdf68fd6f52b9aa30ea25a4b7bd9

**Comment by whummer** [comment]
Thanks for reporting @mathewmarcus . This should be fixed in #527. We're now returning a 404 error if the client executes an invalid request.

PR raised against `moto` here: https://github.com/spulec/moto/pull/1415

**Comment by xiangzprime8** [comment]
With the latest localstack/localstack, I still get the "500 Internal Server Error" when running the following:

aws --endpoint-url=http://localhost:4582 logs create-log-group --log-group-name my-logs

Is creating log groups a supported scenario?  Thanks for your help!

**Comment by radusw** [comment]
I can confirm @xiangzprime8 issue

**Comment by mmikhalko** [comment]
I have the same error @xiangzprime8
