### ISSUE TITLE
bug: API-Gateway-v2 does not recognize {proxy} and {proxy+} placeholders

### ISSUE THREAD

**Issue by awehrung** [localstack/localstack#4954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When configuring a route and integration for my local setup, I am unable to use the variables `{proxy}` and `{proxy+}`. The API-Gateway seems unable to reach the application with the correct path and I get back the following response, which looks like a Spring-Boot default response for undefined endpoints:

```json
{
    "timestamp": "2021-11-18T14:41:42.157+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/%7Bproxy%7D"
}
```

The following log-entry also shows up:

```
2021-11-18T14:41:42.073:WARNING:localstack_ext.services.apigateway.invocations: Unexpected mismatch of API GW invocation path '/' and routeKey path '/{proxy+}'
```

See steps to reproduce below

### Expected Behavior

I would expect Localstack to correctly route every call to the corresponding path according to the defined behavior of the greedy path variable (see docs [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-routes.html) and [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-http.html)).

When using the "real" AWS in a Terraform setup, this works without problems:
* the route-key is `ANY /{proxy+}`
* the integration-URI is `https://backend-service.example/{proxy}`
* every request to the API-Gateway is redirected to `backend-service.example` with the same resource path

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```yaml
localstack:
  image: localstack/localstack:latest  # sha256:7ce018759cab08645cef064c7a694f36d6b5a1d71dd33fbcf9915196d631ca1f 
  container_name: "localstack"
  networks:
    default:
      aliases:
        - redacted.localstack  # for s3 routing with spring-boot
  env_file:
    - configuration/environment/localstack.env
    - ../localstack_api_key.env
  ports:
    - "4566:4566"
    - "443:443"  # for localstack.cloud UI
  volumes:
    - "./configuration/localstack/scripts:/docker-entrypoint-initaws.d"  # this is where the scripts for apigatewayv2 creation are located
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./configuration/localstack/kms/seed.yaml:/init/seed.yaml:ro"
    - "../redacted/dist:/opt/code/lambda_import"
    - "localstack_persistence:/tmp/localstack"
```

Contents of localstack.env:

```env
SERVICES=s3,kms,cognito,serverless
HOSTNAME=localstack
HOSTNAME_EXTERNAL=localstack
DEFAULT_REGION=eu-central-1
DEBUG=0
KMS_SEED_PATH=/init/seed.yaml
KMS_PROVIDER=local-kms
LS_LOG=info
DATA_DIR=/tmp/localstack/data
LAMBDA_EXECUTOR=local
EAGER_SERVICE_LOADING=1
DNS_SERVER=127.0.0.11
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

In the following setup, `backend-service` is a Spring-Boot application running in a container on the same Docker-Compose setup that exposes multiple endpoints, from which `GET /test` just returns a HTTP-200 response.

Locastack setup:

```bash
# Create the HTTP-API with custom ID
awslocal apigatewayv2 create-api --name=my-api --protocol-type=HTTP --tags="_custom_id_=my-api"
# Create an auto-deployed stage to avoid name conflicts
awslocal apigatewayv2 create-stage --api-id=my-api --stage-name=local --auto-deploy
# Create the integration for all endpoints, save ID for route creation
awslocal apigatewayv2 create-integration --api-id=my-api --integration-type=HTTP_PROXY --payload-format-version=2.0 --integration-method=GET --integration-uri=http://backend-service:9010/{proxy}
# Add route using the greedy path variable
awslocal apigatewayv2 create-route --api-id=my-api --route-key="ANY /{proxy+}" --target=integrations/005f9269  # replace ID here
```

Calling `GET http://my-api.execute-api.localhost.localstack.cloud:4566/local/test` triggers the above-mentioned bug.

### Environment

```markdown
- OS: Ubuntu 20.04
- LocalStack: latest (published Nov. 18, 14:20 UTC)
```

### Anything else?

Maybe I'm using the API wrong, or I missed an explanation somewhere in the docs or perhaps Localstack does not support this at all? Either way, thanks in advance for the help.

**Comment by whummer** [comment]
Thanks for the detailed report @awehrung , appreciate the reproducible example. This should be (hopefully) fixed in the meantime. Can you please pull the `latest` Docker image and give it another try? Please let us know if the problem persists.. Thanks for your help!

**Comment by awehrung** [comment]
Hi @whummer, thanks for pushing a fix over the weekend, I greatly appreciate the effort.

The `{proxy}` and `{proxy+}` variables seem to work better now (pulled latest image `sha256:a58b91600fd6c8c92151bb53daf1b902d6a67cdc820c293bb2d8e348cc7b9eaf`), however not quite as expected:
* :heavy_check_mark: the path gets transmitted correctly and the correct endpoint is called for requests with only path-params
* :grey_question: for POST requests, the request-body gets correctly transmitted but not the response from the backend service -- although this may be a configuration error on my side, I will check in depth
* :x: the query parameters are always ignored -- `GET <api-gw-url>/test?p=123` leads to `GET /test` on the backend service; or am I using this wrong?
* :grey_question: the ANY "verb" cannot be used as an `integration-method` -- this is not per se a problem because I can simply define an integration for every verb but I don't know if this is the intended behavior

The query-param problem means that the problem persists for me.

Can someone please reopen this ticket? Thanks in advance for your support.

**Comment by whummer** [comment]
Thanks for the update @awehrung . The issue with missing query parameters should now be resolved - can you please try again with the `latest` Docker image? We're still looking into the issue with the `ANY` verb in integration methods - should be able to provide an update here shortly.. Thanks for your help!

**Comment by awehrung** [comment]
Ok, looks like it works! Thanks @whummer :smile: 

I still have problems with the transmission of the response body and HTTP status (404 and 204 getting mapped to 200, some 200 coming as 503 without body) but this could be an issue on my side. I'll debug this and open a new issue if needed.

From my point of view, this thread can now be closed. Are you able to tell which stable tag this fix will land in?

**Comment by whummer** [comment]
Sounds great, thanks for confirming @awehrung ! 👍 We'll release a new tagged version shortly (probably later today..). Thanks!

**Comment by whummer** [comment]
Hi again. Apologies for the long delay - version tag `0.13.1` is now released and available on Docker Hub. 👍  Thanks
