### ISSUE TITLE
bug: State machines in non-default regions can't be deleted and fail to create proper ARN

### ISSUE THREAD

**Issue by dominikschubert** [localstack/localstack#5030]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- Sometimes wrong ARNs are created for the child state machine (e.g. `arn:aws:states:us-east-1:000000000000:stateMachine:us-east-1_us-east-1_mystatemachine` ... the double region shouldn't be there).

- Deleting a CloudFormation stack with a nested statemachine will fail to properly delete the child state machine when deleting the stack.

### Expected Behavior

State machines should work the same in all regions due to the transparent ARN patching. 

Parity with AWS should be established for nested state machines.

### How are you starting LocalStack?

Custom (please describe below)

### Steps To Reproduce

will be provided via integration test

### Environment

```markdown
- OS: Ubuntu 20.04 LTS
- LocalStack: latest
```

### Anything else?

Might be regressions from the move of stepfunctions functionality to Community.

**Comment by dominikschubert** [comment]
We're currently evaluating a new approach to support multiple regions in stepfunctions which should also fix these issues.

We'll update this issue if there's any further progress on this.

**Comment by Anastasiia-Kosiak** [comment]
Hi, Dominik! Thanks a lot for your help. By the way, do you know if there's any other region which could be working fine in this case?

**Comment by dominikschubert** [comment]
@Anastasiia-Kosiak  In general `us-east-1` should be the one with the best support right now.

**Comment by whummer** [comment]
Quick update for anyone following this thread - we have now pushed a few updates which should fix the multi-region support in StepFunctions. @Anastasiia-Kosiak Can you please pull the `latest` Docker image and give it another try? Thanks

@dominikschubert anything else that needs to be done, or can we close this issue? 🙌

**Comment by Anastasiia-Kosiak** [comment]
Hello, @whummer ! Thanks for taking a look at this issue. I've pulled the latest Docker image but seems like the changes didn't fix the problem I had. I'm still getting this error message: 
```
localstack_main | 2022-01-02 18:03:02.413: arn:aws:states:us-east-2:000000000000:execution:CreateClusterStateMachine:5bd7bc2d-8763-4bf4-bc93-f2a7f13d3b70 : {"Type":"ExecutionFailed","PreviousEventId":2,"ExecutionFailedEventDetails":{"Error":"States.Runtime","Cause":"An error occurred while scheduling the state 'CopyTransform'. The provided ARN 'arn:aws:states:us-east-2:000000000000:elasticmapreduce:addStep.sync' is invalid."}}
```
I think this might not be a bug in localstack but a bug in StepFunctionsLocal.jar that locastack uses to work with stepfunctions. I will probably write to the AWS support about this issue.
Thanks for your help!

**Comment by JacobReynolds** [comment]
I'm experiencing the same issue with `sqs:createQueue`. For a step function task that is declared with:
```
{
    "Create Queue": {
        "Type": "Task",
        "Parameters": {
            "QueueName.$": "States.Format('data-{}.fifo', $.executionId)",
            "Attributes": {
                "FifoQueue": "true"
            }
        },
        "Resource": "arn:aws:states:::aws-sdk:sqs:createQueue",
        "Next": "Queue data"
    }
}
```

I get the error
```
2022-01-09 22:18:55.389: arn:aws:states:us-east-1:000000000000:execution:local-state-machine:df583593-0281-4d23-b23c-5c105fcdc1ab : {"Type":"ExecutionFailed","PreviousEventId":6,"ExecutionFailedEventDetails":{"Error":"States.Runtime","Cause":"An error occurred while scheduling the state 'Create DNS Queue'. The provided ARN 'arn:aws:states:us-east-1:000000000000:aws-sdk:sqs:createQueue' is invalid."}}
```

**Comment by JacobReynolds** [comment]
Some more detailed reproduction steps for the above comment
```console
me@home:~$ DEBUG=1 localstack start
me@home:~$ # in another terminal
me@home:~$ awslocal stepfunctions create-state-machine --name test --definition '{"Comment":"State machine that creates a queue","StartAt":"Create queue","States":{"Create queue":{"Type":"Task","Parameters":{"QueueName":"test.fifo","Attributes":{"FifoQueue":"true"}},"Resource":"arn:aws:states:::aws-sdk:sqs:createQueue","End":true}}}' --role-arn arn:aws:iam::000000000000:role/fake
me@home:~$ awslocal stepfunctions start-execution --state-machine-arn arn:aws:states:us-east-1:000000000000:stateMachine:test
```
The task execution will fail, which can be seen by `awslocal stepfunctions describe-execution...` and the localstack debug console outputs:
```
2022-01-10 23:55:24.371: StartExecution => {"requestClientOptions":{"readLimit":131073,"skipAppendUriPath":false},"requestMetricCollector":null,"customRequestHeaders":null,"customQueryParameters":null,"cloneSource":null,"sdkRequestTimeout":null,"sdkClientExecutionTimeout":null,"stateMachineArn":"arn:aws:states:us-east-1:000000000000:stateMachine:test","name":null,"input":null,"traceHeader":null,"requestCredentials":null,"requestCredentialsProvider":null,"generalProgressListener":{"syncCallSafe":true},"readLimit":131073,"cloneRoot":null}
2022-01-10 23:55:24.431: [200] StartExecution <= {"sdkResponseMetadata":null,"sdkHttpMetadata":null,"executionArn":"arn:aws:states:us-east-1:000000000000:execution:test:12f0abaa-401d-4b5e-af76-e8a759ea1252","startDate":1641858924420}
2022-01-10 23:55:24.482: arn:aws:states:us-east-1:000000000000:execution:test:12f0abaa-401d-4b5e-af76-e8a759ea1252 : {"Type":"ExecutionStarted","PreviousEventId":0,"ExecutionStartedEventDetails":{"Input":"{}","RoleArn":"arn:aws:iam::000000000000:role/fake"}}
2022-01-10 23:55:24.485: arn:aws:states:us-east-1:000000000000:execution:test:12f0abaa-401d-4b5e-af76-e8a759ea1252 : {"Type":"TaskStateEntered","PreviousEventId":0,"StateEnteredEventDetails":{"Name":"Create queue","Input":"{}"}}
2022-01-10 23:55:24.503: arn:aws:states:us-east-1:000000000000:execution:test:12f0abaa-401d-4b5e-af76-e8a759ea1252 : {"Type":"ExecutionFailed","PreviousEventId":2,"ExecutionFailedEventDetails":{"Error":"States.Runtime","Cause":"An error occurred while scheduling the state 'Create queue'. The provided ARN 'arn:aws:states:us-east-1:000000000000:aws-sdk:sqs:createQueue' is invalid."}}
```

**Comment by dominikschubert** [comment]
@JacobReynolds please pull the latest image again and give it a try. We've added a new mechanism to handle these sdk calls from stepfunctions. Using the aws-sdk task type with sqs:createQueue (and more sdk calls) should be working now with the latest image.

@Anastasiia-Kosiak unfortunately `addStep.sync` is one of the optimized integrations that AWS hasn't yet pushed to the stepfunctions emulator. You could try using the newer aws-sdk task type to do this instead but keep in mind it that there are a few differences to the "optimized" version that you can look up in the table here: https://docs.aws.amazon.com/step-functions/latest/dg/connect-emr.html

**Comment by JacobReynolds** [comment]
@dominikschubert sorry for the delay but confirming the fix works as intended. Thanks so much!
