### ISSUE TITLE
bug: CloudWatch metrics backdoor API returns empty list

### ISSUE THREAD

**Issue by kaklakariada** [localstack/localstack#5115]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The Cloudwatch backdoor API `GET /cloudwatch/metrics/raw` implemented in #3535 returns empty data `{"metrics":[]}` with docker container `localstack/localstack:0.13.1`.

### Expected Behavior

The Cloudwatch backdoor API returns the expected data:

```json
{"metrics":[{"ns":"Exasol","n":"USERS","v":1.0,"t":"2021-12-13T16:17:15.673Z","d":[{"n":"Deployment","v":"TEST-1639412295577-953"},{"n":"Cluster Name","v":"MAIN"}]},{"ns":"Exasol","n":"USERS","v":1.0,"t":"2021-12-13T16:17:31.504Z","d":[{"n":"Deployment","v":"TEST-1639412311414-507"},{"n":"Cluster Name","v":"MAIN"}]},{"ns":"Exasol","n":"USERS","v":1.0,"t":"2021-12-13T16:15:31.897Z","d":[{"n":"Deployment","v":"TEST-1639412311827-268"},{"n":"Cluster Name","v":"MAIN"}]},{"ns":"Exasol","n":"USERS","v":1.0,"t":"2021-12-13T16:16:31.897Z","d":[{"n":"Deployment","v":"TEST-1639412311827-268"},{"n":"Cluster Name","v":"MAIN"}]},{"ns":"Exasol","n":"USERS","v":1.0,"t":"2021-12-13T16:17:31.897Z","d":[{"n":"Deployment","v":"TEST-1639412311827-268"},{"n":"Cluster Name","v":"MAIN"}]},{"ns":"Exasol","n":"QUERIES","v":1.0,"t":"2021-12-13T16:17:31.450Z","d":[{"n":"Deployment","v":"TEST-1639412312371-508"},{"n":"Cluster Name","v":"MAIN"}]},{"ns":"Exasol","n":"USERS","v":1.0,"t":"2021-12-13T16:22:09.830Z","d":[{"n":"Deployment","v":"TEST-1639412589721-572"},{"n":"Cluster Name","v":"MAIN"}]}]}
```

This was working with docker container `localstack/localstack:0.12.6`.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

Using Java library `org.testcontainers:localstack:1.16.2`

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```java
    private void putPoints(final CloudWatchClient cloudwatch, final Stream<MetricDatum> points) {
        final PutMetricDataRequest putRequest = PutMetricDataRequest.builder().namespace(CLOUDWATCH_NAMESPACE)
                .metricData(points.collect(Collectors.toList())).build();
        try {
            cloudwatch.putMetricData(putRequest);
        } catch (final SdkClientException exception) {
            throw new IllegalStateException("...");
        }
    }
```
There where no changes in the client code compared to when it worked before.

### Environment

```markdown
- OS: macOS 11.6.1, Docker running in a Fedora 34 VM
- LocalStack: 0.13.1 (0.12.6 was working)
```

### Anything else?

I tried different versions and it looks like the feature broke between `0.12.9` and `0.12.10`.

**Comment by steffyP** [comment]
Hi @kaklakariada,
I cannot reproduce this issue with the latest version (0.14.3.1) anymore. Can you confirm that it was resolved?

**Comment by kaklakariada** [comment]
Hi @steffyP ,
sorry for the late response.
The problem still exists with version 0.14.3.1 and also 1.0.3

**Comment by steffyP** [comment]
Hi @kaklakariada,

thanks for getting back to us! Unfortunately, I cannot reproduce your issue.  Maybe you can give me another hint how you are trying to use the endpoint. 

Could you also try if the following (aws-cli) commands work for you?
```
$ awslocal cloudwatch put-metric-data --namespace "AWS/custom" --metric-name "my-metric" --dimensions abc=123  --value 1115
$ awslocal cloudwatch put-metric-data --namespace "AWS/EC2" --metric-name "CPUUtilization" --dimensions InstanceId=i-46cdcd06a11207ab3 --value 15
```

And then try to run the `curl` command on the endpoint?
```
$ curl http://localhost:4566/cloudwatch/metrics/raw
{"metrics": [{"ns": "AWS/EC2", "n": "CPUUtilization", "v": 15.0, "t": "2022-08-03T13:48:29.216Z", "d": [{"n": "InstanceId", "v": "i-46cdcd06a11207ab3"}]}, {"ns": "AWS/custom", "n": "my-metric", "v": 1115.0, "t": "2022-08-03T13:49:21.711Z", "d": [{"n": "abc", "v": "123"}]}, {"ns": "AWS/EC2", "n": "CPUUtilization", "v": 15.0, "t": "2022-08-03T13:49:28.768Z", "d": [{"n": "InstanceId", "v": "i-46cdcd06a11207ab3"}]}]}
```

Following up on your problem with `testcontainers`: I ran a test with the AWS SDK v2 and the latest `testcontainers` version 1.17.3, using `localstack/localstack:1.0.3`.
My test looks like this
```
public class TestCloudWatchMetricsIssue {
    DockerImageName localstackImage = DockerImageName.parse("localstack/localstack:1.0.3");

    @Rule
    public LocalStackContainer localstack = new LocalStackContainer(localstackImage)
            .withServices(CLOUDWATCH);

    @Test
    public void testMy(){
        CloudWatchClient cloudwatch = CloudWatchClient
                .builder()
                .endpointOverride(localstack.getEndpointOverride(CLOUDWATCH))
                .credentialsProvider(StaticCredentialsProvider.create(
                        AwsBasicCredentials.create(localstack.getAccessKey(), localstack.getSecretKey())
                )).region(Region.of(localstack.getRegion())).build();

        List<MetricDatum> metrics = new ArrayList<>();
        metrics.add(MetricDatum.builder()
                .metricName("my-metric")
                .value(123.0)
                .dimensions(Dimension.builder()
                        .name("abc")
                        .value("def")
                        .build())
                .build());
        new TestCloudwatchMetrics().putPoints(cloudwatch, metrics.stream());

    }
}
```

When I set a breakpoint right after the `putPoints` call, I can see that the docker-container for localstack is still up. 
When I check the port-mapping and run a `curl` eg `$ curl http://localhost:<port>/cloudwatch/metrics/raw` I also retrieve the metric the test inserted (in my case the port mapped to 51066):
```
$ curl http://localhost:51066/cloudwatch/metrics/raw
{"metrics": [{"ns": "my-namespace", "n": "my-metric", "v": 123.0, "t": "2022-08-03T14:37:57.367Z", "d": [{"n": "abc", "v": "def"}]}]}%
```

Could you let me know if this example works for you, or how your test looks like?

**Comment by kaklakariada** [comment]
Wow. Thank you @steffyP for your example code, finally my tests are working!
My problem was that I used dummy values for access key, secret key and region. Using the values provided by `LocalStackContainer` it works now. Looks like the older versions of localstack didn't validate credentials and region.

Would it be possible to let the API return status 400 and an error message in case of invalid credentials? The log shows that it always returns 200, also for invalid credentials.

Thanks again for your patience, quick response and professional help!
