### ISSUE TITLE
bug: API Gateway does not invoke authorizer on GET request with query parameters

### ISSUE THREAD

**Issue by heshamnaim** [localstack/localstack#5329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If I make a GET request to a route, the authorizer is invoked. If I add query parameters to the same route, the authorizer is not invoked, but the lambda function is.

### Expected Behavior

Expect the authorizer to always be invoked.

### How are you starting LocalStack?

With the `localstack` script

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

   localstack start -d (pro mode, with hot reload config for python)

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

  ``` 
class BackendStatelessService(core.Construct):
    api_domain = None
    def __init__(self, scope: core.Construct, id: str):
        super().__init__(scope, id)
        self.api_domain= apigateway.RestApi(self,'rest-api',
                rest_api_name="Rest API",
                description="Rest API",
                binary_media_types=["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
                endpoint_types = [apigateway.EndpointType.REGIONAL],
                default_cors_preflight_options = apigateway.CorsOptions(allow_origins = apigateway.Cors.ALL_ORIGINS, allow_headers = ['*'], allow_methods = apigateway.Cors.ALL_METHODS, expose_headers=['*'], allow_credentials=True),
            )
         self.api_domain.add_gateway_response('response-401', type=apigateway.ResponseType.UNAUTHORIZED, response_headers={'Access-Control-Allow-Origin':"'*'", 'Access-Control-Allow-Headers':"'*'", 'Access-Control-Allow-Methods':"'*'"})
  
        authorizer_handler = lambda_.Function(self, 'token-authorizer-handler',
            function_name = "authorizer",
            runtime = lambda_.Runtime.PYTHON_3_8, 
            code = python_code,
            handler = "authorizer.lambda_handler",
            vpc = vpc,
            vpc_subnets = ec2.SubnetSelection(subnet_type = ec2.SubnetType.ISOLATED),
        )
        authorizer_handler.add_environment("region", 'us-west-2')
        api_authorizer = apigateway.TokenAuthorizer(self, 'api-authorizer', handler = authorizer_handler)
        api_handler = lambda_.Function(self, "api-handler", 
            function_name = "api-example",
            runtime = lambda_.Runtime.PYTHON_3_8, 
            code = python_code,
            handler = "example.lambda_handler",
        )
        api = self.api_domain.root.add_resource("example", default_integration=apigateway.LambdaIntegration(api_handler))
        api.add_method('GET', 
            authorization_type = apigateway.AuthorizationType.CUSTOM, 
            authorizer = api_authorizer,
            integration=apigateway.LambdaIntegration(
                analytics_handler,
                request_parameters = {'integration.request.querystring.group': 'method.request.querystring.group','integration.request.querystring.id': 'method.request.querystring.id'}
            ),
            request_parameters = {'method.request.querystring.group': True,'method.request.querystring.id': True},
        )                      
```

### Environment

```markdown
- OS: Mac
- LocalStack: 0.13.3.3
```

### Anything else?

Deployed with cdklocal

**Comment by heshamnaim** [comment]
https://github.com/localstack/localstack/blob/2117db1cda9bf24924527adbf4f28af1e487fb3d/localstack/services/apigateway/apigateway_listener.py#L312

Trying to dig in a bit. This looks interesting...
```
def run_authorizer(invocation_context: ApiInvocationContext, authorizer: Dict):
    # TODO implement authorizers
    pass
```

**Comment by calvernaz** [comment]
Hi @heshamnaim thanks and appreciated! The issue for your use case is related to a mismatch between paths associated with the authorizer, query parameters should not be used to evaluate matching paths, and they were.

**Comment by heshamnaim** [comment]
> Hi @heshamnaim thanks and appreciated! The issue for your use case is related to a mismatch between paths associated with the authorizer, query parameters should not be used to evaluate matching paths, and they were.

Ah I get it, thanks for the quick reply. Let me know if there is anything I can do to help!

**Comment by calvernaz** [comment]
@heshamnaim I merged a fix for this, should be included in the latest version soon. Thanks!

**Comment by heshamnaim** [comment]
> @heshamnaim I merged a fix for this, should be included in the latest version soon. Thanks!

@calvernaz I just tried reinstalling localstack via pip and re-ran the test and still have the same issue. I read above that the fix would be included in the current tag `0.13.3.3` but it isn't there yet if that is the case. Please advise.

**Comment by heshamnaim** [comment]
@calvernaz I don't see a related commit or PR, not sure what I am missing. Appreciate the help! @whummer thoughts?

**Comment by calvernaz** [comment]
Hi @heshamnaim, you are right, the PR was done on a downstream project and the release process is a bit different. Once it's available, I'll post back to you! Sorry for the inconvenience.

**Comment by calvernaz** [comment]
Hi @heshamnaim the latest version has been published, you should be able to verify it 👍

**Comment by heshamnaim** [comment]
@calvernaz still not working. I pip uninstalled and reinstalled `0.13.3.3` the authorizer is not being called with query parameters, but without it is. Same route. Here is my `pip freeze`
```
localstack==0.13.3.3
localstack-client==1.31
localstack-ext==0.13.3.8
localstack-plugin-loader==1.1.1
```

**Comment by whummer** [comment]
Hi @heshamnaim , just to clarify - the changes are included in the Docker image itself (not the pip package). Can you please do a `docker pull localstack/localstack` and try again? Thanks!

**Comment by heshamnaim** [comment]
Ah ok, my apologies! Pulled the latest docker image and it is working well thanks!

**Comment by heshamnaim** [comment]
@calvernaz @whummer I am seeing this same issue intermittently when debugging python lambdas with 
```LAMBDA_REMOTE_DOCKER=0 \
    LAMBDA_DOCKER_FLAGS='-p 19891:19891' \
    DEBUG=1 localstack start```
It works fine as long as `LAMBDA_DOCKER_FLAGS='-p 19891:19891'` is not set.

**Comment by heshamnaim** [comment]
I am also seeing an issue when using a regex in the route like `{id}`, or if I have added several subroutes

```
project_activity_resource = projects_api.root.add_resource('activity')
        project_activity_resource.add_method('GET', authorization_type = apigateway.AuthorizationType.CUSTOM, authorizer = projects_authorizer)
        one_project_resource = projects_api.root.add_resource('{id}')
        one_project_resource.add_method('GET', authorization_type = apigateway.AuthorizationType.CUSTOM, authorizer = projects_authorizer)
        one_project_resource.add_method('PATCH', authorization_type = apigateway.AuthorizationType.CUSTOM, authorizer = projects_authorizer)
```

Would you like me to open a new issue @calvernaz ?

**Comment by calvernaz** [comment]
@heshamnaim it looks like two different bugs can you create a new one for the debugging lambdas?

**Comment by heshamnaim** [comment]
@calvernaz I created another [issue for debugging lamdas](https://github.com/localstack/localstack/issues/5424) would you like me to create another issue for the regex routes and sub-resources not calling authorizer as well? Or just reopen this issue?

**Comment by calvernaz** [comment]
@heshamnaim Hi, reopening it's fine, I have a fix for it already it just needs to be published, like before.
