### ISSUE TITLE
S3 DELETE incorrectly returns a nonzero Content-Length in 0.8.4

### ISSUE THREAD

**Issue by esilverberg** [localstack/localstack#541]
In localstack 0.8.3, this call:

`curl -i -X DELETE http://localstack:4572/bucketname/objectname`

Would correctly return:

```
HTTP/1.1 204 No Content
Server: BaseHTTP/0.3 Python/2.7.13
Date: Sat, 06 Jan 2018 19:25:50 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 0
Server: Werkzeug/0.14.1 Python/2.7.13
Date: Sat, 06 Jan 2018 19:25:50 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Headers: authorization,content-type,content-md5,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent
```

Starting with 0.8.4, the same call returns:

```
HTTP/1.1 204 No Content
Server: BaseHTTP/0.3 Python/2.7.13
Date: Sat, 06 Jan 2018 19:25:50 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 199
Server: Werkzeug/0.14.1 Python/2.7.13
Date: Sat, 06 Jan 2018 19:25:50 GMT
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,PUT,POST,DELETE,OPTIONS,PATCH
Access-Control-Allow-Headers: authorization,content-type,content-md5,x-amz-content-sha256,x-amz-date,x-amz-security-token,x-amz-user-agent
```

Note the spurious **Content-Length: 199** causes an exception in the Seahorse library used by the ruby aws-sdk:

`Seahorse::Client::NetworkingError: http response body truncated, expected 199 bytes, received 0 bytes`
  
This is blocking our tests and so we have had to revert back to 0.8.3 for now.

**Comment by whummer** [comment]
Thanks for reporting @esilverberg . This should be fixed in #548 - can you please give it a try with the latest version? Thanks

**Comment by whummer** [comment]
Closing this issue. Please re-open or comment here if the problem persists. Thanks

**Comment by cknave** [comment]
This is still an issue for gzipped responses. I opened a PR to fix: #3225
