### ISSUE TITLE
Broken pipe when clients disconnect

### ISSUE THREAD

**Issue by scarlac** [localstack/localstack#585]
Using `nodemon` to auto-restart a NodeJS server will cause "Broken pipe" errors very often.

I'm using SQS and `receiveMessage()` to long-poll for messages. I suspect the broken pipe is a result of a long-poll `receiveMessage()` being killed without a proper TCP close. I would however not expect localstack to complain like this. A broken pipe is less of a fatal error and more of a warning.

Example output from a `docker-compose` stack where localstack is integrated into:
```
node_1             | >>> RESTARTING <<<
localstack_1       | 2018-01-26T16:04:44:ERROR:localstack.services.generic_proxy: Error forwarding request: [Errno 32] Broken pipe Traceback (most recent call last):
localstack_1       |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 220, in forward
localstack_1       |     self.send_response(response.status_code)
localstack_1       |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 406, in send_response
localstack_1       |     self.send_header('Server', self.version_string())
localstack_1       |   File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
localstack_1       |     self.wfile.write("%s: %s\r\n" % (keyword, value))
localstack_1       |   File "/usr/lib/python2.7/socket.py", line 328, in write
localstack_1       |     self.flush()
localstack_1       |   File "/usr/lib/python2.7/socket.py", line 307, in flush
localstack_1       |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
localstack_1       | error: [Errno 32] Broken pipe
localstack_1       | 
localstack_1       | Traceback (most recent call last):
localstack_1       |   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
localstack_1       |     self.finish_request(request, client_address)
localstack_1       |   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
localstack_1       |     self.RequestHandlerClass(request, client_address, self)
localstack_1       |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 81, in __init__
localstack_1       |     BaseHTTPRequestHandler.__init__(self, request, client_address, server)
localstack_1       |   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
localstack_1       |     self.finish()
localstack_1       |   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
localstack_1       |     self.wfile.close()
localstack_1       |   File "/usr/lib/python2.7/socket.py", line 283, in close
localstack_1       |     self.flush()
localstack_1       |   File "/usr/lib/python2.7/socket.py", line 307, in flush
localstack_1       |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
localstack_1       | error: [Errno 32] Broken pipe
```

localstack setup from docker-compose.yml:
```
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-west-1
      - FORCE_NONINTERACTIVE=true
      - HOSTNAME_EXTERNAL=localstack
    ports:
      - "4576:4576"
      - "8080:8080"
```

Expected behavior: No output on broken pipes or at most a 1-line 'Warning: Client closed connection prematurely" or similar low-noise behavior.

**Comment by whummer** [comment]
Thanks for reporting @scarlac , this should be fixed in #596. Can you please confirm that the verbosity of the log output is now more appropriate?

**Comment by scarlac** [comment]
Thanks for the quick reaction @whummer. Unfortunately I am still seeing the issue with a docker build from master. I do get the new error message though:
```
localstack_1       | 2018-02-05T10:56:08:WARNING:localstack.services.generic_proxy: Connection prematurely closed by client (broken pipe).
localstack_1       | Traceback (most recent call last):
localstack_1       |   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
localstack_1       |     self.finish_request(request, client_address)
localstack_1       |   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
localstack_1       |     self.RequestHandlerClass(request, client_address, self)
localstack_1       |   File "/opt/code/localstack/localstack/services/generic_proxy.py", line 81, in __init__
localstack_1       |     BaseHTTPRequestHandler.__init__(self, request, client_address, server)
localstack_1       |   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
localstack_1       |     self.finish()
localstack_1       |   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
localstack_1       |     self.wfile.close()
localstack_1       |   File "/usr/lib/python2.7/socket.py", line 283, in close
localstack_1       |     self.flush()
localstack_1       |   File "/usr/lib/python2.7/socket.py", line 307, in flush
localstack_1       |     self._sock.sendall(view[write_offset:write_offset+buffer_size])
localstack_1       | error: [Errno 32] Broken pipe
```
I jumped into the container and checked the code just to make sure I was running the correct version and it does seems like I am:
```
(...)
            error_msg = 'Error forwarding request: %s %s' % (e, trace)
            if 'Broken pipe' in trace:
                LOGGER.warn('Connection prematurely closed by client (broken pipe).')
            elif not self.proxy.quiet or not conn_error:
(...)
```

**Comment by sashas777** [comment]
I use Ubuntu
Installed Localstack using pip.
Localstack version 0.8.7 
I have the same issue, after sometime in console I getting error:
```
2018-07-29T16:28:38:WARNING:localstack.services.generic_proxy: Connection prematurely closed by client (broken pipe).
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45940)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/sashas/.local/lib/python2.7/site-packages/localstack/services/generic_proxy.py", line 81, in __init__
    BaseHTTPRequestHandler.__init__(self, request, client_address, server)
  File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
    self.wfile.close()
  File "/usr/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/usr/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

**Comment by topwik** [comment]
i just started seeing this in localstack 0.8.8 with regards to kinesis.

**Comment by 3lix** [comment]
Seeing the same issue as well likely when using localstack's elasticsearch.
This issue broke tests and causes the whole localstack to die on docker. A docker restart is required for a successful run.

**Comment by whummer** [comment]
Thanks for reporting. This should be fixed in the mean time - please re-open if the problem persists.

**Comment by josemando** [comment]
This problem is happening to me when using SQS on docker image `localstack/localstack-light:0.11.1`
