### ISSUE TITLE
bug: Localstack Pro not triggering boto GoneException when calling post_to_connection on socket_id that is no longer connected

### ISSUE THREAD

**Issue by paulrobello** [localstack/localstack#6493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I save all connects to DDB on connect and remove them on disconnect or when a GoneException is raise when trying to send to one.
As LS is not firing $disconnect for my websockets (see separate bug I have posted) I have many orphaned connection id's in my DDB table.
When I go to broadcast a message I loop over all id's in my table and if an exception is raised in remove it so future broadcasts wont waist their time on a dead connection.

### Expected Behavior

When call post_to_connection with an id of a websocket that has been disconnected a GoneException should be raised by boto from the response.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

docker-compose.yml

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

pulumi typescript

### Environment

```markdown
- OS: Win11, Mac OSX
- LocalStack: 1.0.0
```

**Comment by whummer** [comment]
Hi @paulrobello, thanks for reporting. We have pushed a couple of enhancements for handling of WebSocket disconnects and GoneException. Can you please pull the `latest` Docker image and give it another try? In parallel, we continue to work on the separate thread with `$disconnect` messages (see #6383). Please keep us posted on how it goes, thanks!

**Comment by paulrobello** [comment]
The issue still persists with localstack:latest

 

 

Paul Robello | Principal Solution Architect

VistaJet | XO | XOA | A LEADER IN PRIVATE JET OPERATIONS

mobile 1.916.402.0471

email  ***@***.***> ***@***.***

**Comment by whummer** [comment]
Thanks for the feedback @paulrobello . Can you please help us create a small reproducible example? With the latest version we don't seem to be able to expose this behavior anymore. Thanks for your help!

**Comment by whummer** [comment]
Closing this issue for now, please let us know (with a reproducible example) if the problem persists. We'll continue the thread on `$disconnect` messages over at https://github.com/localstack/localstack/issues/6383 👍 Thanks
