### ISSUE TITLE
bug: KMS GetPublicKey API call fails

### ISSUE THREAD

**Issue by davecardwell** [localstack/localstack#6605]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After create an RSA KMS key in Localstack you get a `NotFoundException` when attempting to retrieve its public key.

### Expected Behavior

The `GetPublicKey` call should succeed.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```sh
$ curl -O https://raw.githubusercontent.com/localstack/localstack/master/docker-compose.yml
$ mkdir volume
$ DEBUG=1 docker compose up

$ docker compose exec localstack /bin/bash
$ bin/localstack status
┌─────────────────┬───────────────────────────────────────────────────────┐
│ Runtime version │ 1.0.4.dev                                             │
│ Docker image    │ tag: latest, id: 96c3043a8413, 📆 2022-08-05T11:04:56 │
│ Runtime status  │ ✔ running (name: "localstack_main", IP: 172.29.0.2)   │
└─────────────────┴───────────────────────────────────────────────────────┘
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```sh
$ awslocal kms create-key --key-usage ENCRYPT_DECRYPT --key-spec RSA_2048
{
    "KeyMetadata": {
        "AWSAccountId": "000000000000",
        "KeyId": "35e165aa-7af5-4489-9833-7b8d80e335ae",
        "Arn": "arn:aws:kms:us-east-1:000000000000:key/35e165aa-7af5-4489-9833-7b8d80e335ae",
        "CreationDate": 1659890513.684544,
        "Enabled": true,
        "Description": "",
        "KeyUsage": "ENCRYPT_DECRYPT",
        "KeyState": "Enabled",
        "Origin": "AWS_KMS",
        "KeyManager": "CUSTOMER",
        "CustomerMasterKeySpec": "RSA_2048",
        "KeySpec": "RSA_2048",
        "EncryptionAlgorithms": [
            "RSAES_OAEP_SHA_1",
            "RSAES_OAEP_SHA_256"
        ]
    }
}

$ awslocal kms create-alias --alias-name alias/test-rsa-key --target-key-id 35e165aa-7af5-4489-9833-7b8d80e335ae

$ awslocal kms list-keys
{
    "Keys": [
        {
            "KeyId": "35e165aa-7af5-4489-9833-7b8d80e335ae",
            "KeyArn": "arn:aws:kms:us-east-1:000000000000:key/35e165aa-7af5-4489-9833-7b8d80e335ae"
        }
    ]
}

$ awslocal kms list-aliases
{
    "Aliases": [
        {
            "AliasName": "alias/test-rsa-key",
            "AliasArn": "arn:aws:kms:us-east-1:000000000000:alias/test-rsa-key",
            "TargetKeyId": "35e165aa-7af5-4489-9833-7b8d80e335ae"
        },
        # etc.
    ]
}

$ awslocal kms get-public-key --key-id alias/test-rsa-key

An error occurred (NotFoundException) when calling the GetPublicKey operation:

$ awslocal kms get-public-key --key-id 35e165aa-7af5-4489-9833-7b8d80e335ae

An error occurred (NotFoundException) when calling the GetPublicKey operation:

$ awslocal kms get-public-key --key-id arn:aws:kms:us-east-1:000000000000:key/35e165aa-7af5-4489-9833-7b8d80e335ae

An error occurred (NotFoundException) when calling the GetPublicKey operation:
```

Each time the Localstack logs shows simply:
```
localstack_main  | 2022-08-07T16:38:27.578  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS kms.GetPublicKey => 400 (NotFoundException)
```

### Environment

```markdown
- OS: macOS 12.5 (M1 Pro)
- LocalStack: 1.0.4.dev (build git hash 5c77d192)
- Docker: Engine 20.10.17, Desktop v4.10.1 (82475), Compose v2.6.1
```

### Anything else?

Test commands to create key and retrieve public key taken from https://aws.amazon.com/blogs/security/how-to-use-aws-kms-rsa-keys-for-offline-encryption/

**Comment by davecardwell** [comment]
Further to my report, it appears that setting `KMS_PROVIDER=local-kms` in compose.yaml allows this functionality to work, so it’s an issue with the default moto provider.

**Comment by taras-kobernyk-localstack** [comment]
https://github.com/localstack/localstack/pull/6675 should fix the issue.
Also have a plan to change a lot of stuff in KMS soon, which is supposed to fix this better and also address other possible issue.

**Comment by taras-kobernyk-localstack** [comment]
The mentioned PR has just been merged. The fix should start working with the next docker image release.
Closing the issue, but do not hesitate to open it again if something won't work.

**Comment by davecardwell** [comment]
@taras-kobernyk-localstack unfortunately #6675 did not seem to fix the issue.

Rerunning the steps from my original issue description with the following version still fails:
```
┌─────────────────┬───────────────────────────────────────────────────────┐
│ Runtime version │ 1.1.1.dev                                             │
│ Docker image    │ tag: latest, id: f33cf1831a32, 📆 2022-09-06T19:41:09 │
│ Runtime status  │ ✔ running (name: "localstack_main", IP: 172.26.0.2)   │
└─────────────────┴───────────────────────────────────────────────────────┘
```

**Comment by taras-kobernyk-localstack** [comment]
You are right, totally my bad. Sorry for that.

Luckily, a total rework of KMS was underway. Hopefully it is going to be merged in a few days. I have just checked and it succeeds with all 4 types of the identifiers - key IDs, key ARNs, alias names and alias ARNs.

I will update the ticket when it is available.

**Comment by davecardwell** [comment]
@taras-kobernyk-localstack Thanks so much for your work on this! Looking forward to checking out the KMS rework 🙌

**Comment by taras-kobernyk-localstack** [comment]
Apologies for the delay. But the code is finally there.
Let me know if everything is fine or if something is still failing.

**Comment by davecardwell** [comment]
@taras-kobernyk-localstack Thank you again for your work on this!

I can confirm that I re-ran the Steps to Reproduce in my original PR with `localstack/localstack:latest` (`b07825443747`) and `kms.GetPublicKey` by the key ID, ARN, and alias all worked! 🙌

**Comment by taras-kobernyk-localstack** [comment]
Awesome! Glad to hear it worked. :-)
And sorry for such a delay with this.
