### ISSUE TITLE
bug: DynamoDB stores are not populated when localstack is restarted in persistent mode

### ISSUE THREAD

**Issue by phi-tz** [localstack/localstack#6842]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

DynamoDB stores are populated when we create a new table.  This is a correct assumption when you're deploying from a clean slate.  However with persistence mode turned on, if I turn off localstack's docker, turn it back on, and re-deploy my DynamoDB tables, because there are no changes, no tables are re-created, and therefore, the stores are not populated.

This leads to a variety of issues, most notably when you have a stream on a table.  At some point, we will call `SchemaExtractor.extract_keys(item=item, table_name=table_name)`,  which would try to obtain the table definitions from `get_store()`.  The store, of course, has no table definitions there, and it will throw.  This is the error you will get:

```
2022-09-08T22:28:13.161 ERROR --- [   asgi_gw_5] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 81, in __call__
    result = self.forward_request(
  File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 141, in forward_request
    return do_forward_request(
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 53, in D
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 602, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 682, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
    response = self.request(request)
  File "/opt/code/localstack/localstack/aws/proxy.py", line 46, in request
    return self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/forwarder.py", line 56, in _call
    return handler(context, req)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/api/core.py", line 115, in operation_marker
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 805, in transact_write_items
    records = self.prepare_transact_write_item_records(
  File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 1127, in prepare_transact_write_item_records
    keys = SchemaExtractor.extract_keys(item=put_request["Item"], table_name=table_name)
  File "/opt/code/localstack/localstack/services/dynamodb/utils.py", line 43, in extract_keys
    key_schema = cls.get_key_schema(table_name)
  File "/opt/code/localstack/localstack/services/dynamodb/utils.py", line 66, in get_key_schema
    raise Exception(f"Unknown table: {table_name} not found in {table_definitions.keys()}")
Exception: Unknown table: ordersTable not found in dict_keys([])
2022-09-08T22:28:13.170  INFO --- [   asgi_gw_5] localstack.request.aws     : AWS dynamodb.TransactWriteItems => 500 (InternalError)
```

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

Covered above

### Environment

```markdown
- OS: Ubuntu
- LocalStack: docker, 1.1.0
```

**Comment by eytan-avisror** [comment]
+1 on this, definitely seeing the same behavior - would be great if we can prioritize this fix since it basically means persistence for dynamodb is not working.

**Comment by whummer** [comment]
Thanks for reporting @phi-tz @eytan-avisror - we have now pushed a small change which should (hopefully) get this issue resolved. Can you please pull the `latest` Docker image and give it another try?

Please note that some of the persistence features (incl. DynamoDB stores) are only available in the Pro version of LocalStack. 

Please let us know if there are any other questions or issues.. 👍  Thanks!

**Comment by eytan-avisror** [comment]
@whummer 
Just tried out latest (1.1.1-dev), issue is still there:
```
2022-09-22T19:11:20.394 ERROR --- [   asgi_gw_2] l.aws.handlers.logging     : exception during call chain
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 90, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 122, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 92, in __call__
    skeleton_response = self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/forwarder.py", line 56, in _call
    return handler(context, req)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/api/core.py", line 149, in operation_marker
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 810, in transact_write_items
    records = self.prepare_transact_write_item_records(
  File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 1132, in prepare_transact_write_item_records
    keys = SchemaExtractor.extract_keys(item=put_request["Item"], table_name=table_name)
  File "/opt/code/localstack/localstack/services/dynamodb/utils.py", line 43, in extract_keys
    key_schema = cls.get_key_schema(table_name)
  File "/opt/code/localstack/localstack/services/dynamodb/utils.py", line 66, in get_key_schema
    raise Exception(f"Unknown table: {table_name} not found in {table_definitions.keys()}")
Exception: Unknown table: ts_cohort_membership not found in dict_keys([])
2022-09-22T19:11:20.395  INFO --- [   asgi_gw_2] localstack.request.aws     : AWS dynamodb.TransactWriteItems => 500 (InternalError)
```

**Comment by eytan-avisror** [comment]
Just FYI @whummer - I tried out the same think with Localstack Pro (using a trial API Key) and I am getting the same problem.
So this is a genuine bug with localstack.

**Comment by eytan-avisror** [comment]
Here is a clear reproduce of this issue using `localaws`

### Create a table
1. `localaws dynamodb create-table --cli-input-json file://table.json`

```json
# table.json
{
    "TableName": "MusicCollection2",
    "KeySchema": [
      { "AttributeName": "Artist", "KeyType": "HASH" },
      { "AttributeName": "SongTitle", "KeyType": "RANGE" }
    ],
    "AttributeDefinitions": [
      { "AttributeName": "Artist", "AttributeType": "S" },
      { "AttributeName": "SongTitle", "AttributeType": "S" }
    ],
    "ProvisionedThroughput": {
      "ReadCapacityUnits": 5,
      "WriteCapacityUnits": 5
    }
}

```

### Write a transaction
2. `localaws dynamodb transact-write-items  --transact-items file://artist.json`

```json
# artist.json
[{
  "Put": {
    "Item": {
      "Artist": {
        "S": "Test"
      },
      "SongTitle": {
        "S": "Test"
      }
    },
    "TableName": "MusicCollection2"
  }
}]
```

### Restart pod
3. restart localstack pod/container

### Validate that table is persisted
4. `localaws dynamodb describe-table --table-name MusicCollection2`

```json
# response - table is still there - persistence is on
{
    "Table": {
        "AttributeDefinitions": [
            {
                "AttributeName": "Artist",
                "AttributeType": "S"
            },
            {
                "AttributeName": "SongTitle",
                "AttributeType": "S"
            }
        ],
        "TableName": "MusicCollection2",
        "KeySchema": [
            {
                "AttributeName": "Artist",
                "KeyType": "HASH"
            },
            {
                "AttributeName": "SongTitle",
                "KeyType": "RANGE"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": "2022-09-27T16:29:52.715000+00:00",
        "ProvisionedThroughput": {
            "LastIncreaseDateTime": "1970-01-01T00:00:00+00:00",
            "LastDecreaseDateTime": "1970-01-01T00:00:00+00:00",
            "NumberOfDecreasesToday": 0,
            "ReadCapacityUnits": 5,
            "WriteCapacityUnits": 5
        },
        "TableSizeBytes": 52,
        "ItemCount": 2,
        "TableArn": "arn:aws:dynamodb:us-east-1:000000000000:table/MusicCollection2"
    }
}
```


### Try to write a new object
5. `localaws dynamodb transact-write-items  --transact-items file://artist2.json`

```json
# artist2.json
[{
  "Put": {
    "Item": {
      "Artist": {
        "S": "Test123"
      },
      "SongTitle": {
        "S": "Test123"
      }
    },
    "TableName": "MusicCollection2"
  }
}]
```


### Error:
  ```
  An error occurred (InternalError) when calling the TransactWriteItems operation (reached max retries: 2): exception while calling dynamodb.TransactWriteItems: Traceback (most recent call last):
  File "/opt/code/localstack/localstack/aws/chain.py", line 57, in handle
    handler(self, self.context, response)
  File "/opt/code/localstack/localstack/aws/handlers/service.py", line 121, in __call__
    handler(chain, context, response)
  File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 81, in __call__
    result = self.forward_request(
  File "/opt/code/localstack/localstack/aws/handlers/legacy.py", line 141, in forward_request
    return do_forward_request(
  File "/opt/code/localstack/localstack/utils/patch.py", line 38, in proxy
    return new(target, *args, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.10/site-packages/localstack_ext/services/edge.py.enc", line 53, in D
  File "/opt/code/localstack/localstack/services/edge.py", line 225, in do_forward_request
    result = do_forward_request_inmem(api, method, path, data, headers, port=port)
  File "/opt/code/localstack/localstack/services/edge.py", line 249, in do_forward_request_inmem
    response = modify_and_forward(
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 604, in wrapper
    value = func(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 684, in modify_and_forward
    listener_result = listener.forward_request(
  File "/opt/code/localstack/localstack/http/adapters.py", line 51, in forward_request
    response = self.request(request)
  File "/opt/code/localstack/localstack/aws/proxy.py", line 46, in request
    return self.skeleton.invoke(context)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 153, in invoke
    return self.dispatch_request(context, instance)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 165, in dispatch_request
    result = handler(context, instance) or {}
  File "/opt/code/localstack/localstack/aws/forwarder.py", line 55, in _call
    return handler(context, req)
  File "/opt/code/localstack/localstack/aws/skeleton.py", line 117, in __call__
    return self.fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/aws/api/core.py", line 115, in operation_marker
    return fn(*args, **kwargs)
  File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 744, in transact_write_items
    records = self.prepare_transact_write_item_records(
  File "/opt/code/localstack/localstack/services/dynamodb/provider.py", line 1065, in prepare_transact_write_item_records
    keys = SchemaExtractor.extract_keys(item=put_request["Item"], table_name=table_name)
  File "/opt/code/localstack/localstack/services/dynamodb/utils.py", line 45, in extract_keys
    key_schema = cls.get_key_schema(table_name)
  File "/opt/code/localstack/localstack/services/dynamodb/utils.py", line 68, in get_key_schema
    raise Exception(f"Unknown table: {table_name} not found in {table_definitions.keys()}")
Exception: Unknown table: MusicCollection2 not found in dict_keys([])
```

**Comment by whummer** [comment]
Hi @eytan-avisror , thanks for providing the reproducible example! Can you please run a `docker pull localstack/localstack:latest`, and give it another try with the`latest` Docker image tag? (you may need to update your startup configuration to use the `latest` image tag, e.g., in `docker-compose.yml`)

**Comment by eytan-avisror** [comment]
Thanks @whummer it is working!
would be great if you can reference the PR that fixed it for educational purposes 👍
