### ISSUE TITLE
bug: API Gateway v2:  API Mapping fails to utilize mapping key

### ISSUE THREAD

**Issue by jrauen** [localstack/localstack#6984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm utilizing API Gateway v2 with a custom domain name and API mapping. All requests and responses for the creation are correct but when I make requests to the endpoint it does now behave as expected. Here is the setup:

- API Gateway
- Domain Name
- API Mapping
- Route
- Integration

```terraform
resource "aws_apigatewayv2_api" "api" {
  name          = "api"
  protocol_type = "HTTP"
}
resource "aws_apigatewayv2_stage" "default" {
  api_id      = aws_apigatewayv2_api.api.id
  name        = "$default"
  auto_deploy = true
}
resource "aws_apigatewayv2_integration" "lambda" {
  api_id                 = aws_apigatewayv2_api.api.id
  integration_type       = "AWS_PROXY"
  integration_method     = "POST"
  integration_uri        = module.lambda.lambda_function_invoke_arn
  payload_format_version = "2.0"
}
resource "aws_apigatewayv2_route" "endpoint" {
  api_id    = aws_apigatewayv2_api.api.id
  route_key = "GET /endpoint"
  target    = "integrations/${aws_apigatewayv2_integration.lambda.id}"
}
resource "aws_apigatewayv2_api_mapping" "mapping" {
  api_id          = aws_apigatewayv2_api.api.id
  domain_name = "api.mydomain.com"
  stage           = aws_apigatewayv2_stage.default.id
  api_mapping_key = "prefix"
}
```

With this configuration I would expect to be able to make requests to `https://api.mydomain.com/prefix/endpoint`. However, the behavior I see is that this endpoint is not found but I can make requests to `https://api.mydomain.com/endpoint` ignoring the API mapping prefix.

### How are you starting LocalStack?

With a docker-compose file

### Steps To Reproduce

```yaml
version: "3.3"
services:
  localstack:
    image: localstack/localstack:latest
    environment:
      HOSTNAME: "localstack"
      HOSTNAME_EXTERNAL: "localstack"
      SERVICES: "apigateway,iam,sts,ec2,secretsmanager,acm,route53,logs,lambda"
      LOCALSTACK_API_KEY: ${LOCALSTACK_API_KEY}
      DISABLE_CORS_CHECKS: 1
      DEBUG: "1"
      LS_LOG: "trace"
      TEST_AWS_ACCOUNT_ID: "000000000000"
    ports:
      - "443:443"
      - "4566:4566"
      - "4571:4571"
```

### Environment

```markdown
- OS: macOS Monterey 12.6
- LocalStack: latest `86b855a67499`
```

**Comment by whummer** [comment]
Hi @jrauen , thanks for reporting. Quick update - we have now pushed a couple of enhancements for API Gateway v2 API mappings that should (hopefully) get this issue resolved. Can you please pull the `latest` Docker image and give it another try? Please keep us posted on how it goes.. Thanks!

**Comment by jrauen** [comment]
I'm still experiencing the issue with image `sha256:ab19bad77d7eecf2da1440cc370351e54638cd04b8d02ca1114527a0247ea5d1`. 

logs for `/{prefix}/` which should default to the `$default` route:
```
2022-10-17T16:17:50.906 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : GET api-local.mts.bah.com/docs/
2022-10-17T16:17:50.908910038Z 2022-10-17T16:17:50.908 DEBUG --- [   asgi_gw_0] l.s.a.apigateway_utils     : Skipping RouteKey '$default' for protocol 'HTTP'
2022-10-17T16:17:51.139945858Z 2022-10-17T16:17:51.139 DEBUG --- [   asgi_gw_0] l.s.a.apigateway_utils     : Skipping RouteKey '$default' for protocol 'HTTP'
2022-10-17T16:17:51.140553326Z 2022-10-17T16:17:51.140 DEBUG --- [   asgi_gw_0] l.s.a.integrations         : Invoking Lambda arn:aws:lambda:us-east-1:000000000000:function:swagger-ui for integration of API ID cd154862
2022-10-17T16:17:51.147906227Z 2022-10-17T16:17:51.147 DEBUG --- [   asgi_gw_1] l.aws.serving.wsgi         : POST localhost:4566/2015-03-31/functions/arn%3Aaws%3Alambda%3Aus-east-1%3A000000000000%3Afunction%3Aswagger-ui/invocations
2022-10-17T16:17:51.152108110Z 2022-10-17T16:17:51.151 DEBUG --- [uest_thread)] l.s.awslambda.lambda_api   : Running lambda arn:aws:lambda:us-east-1:000000000000:function:swagger-ui
2022-10-17T16:17:51.155790364Z 2022-10-17T16:17:51.154 DEBUG --- [   asgi_gw_2] l.aws.serving.wsgi         : GET localhost:4566/2015-03-31/functions/
2022-10-17T16:17:51.160187568Z 2022-10-17T16:17:51.159  INFO --- [   asgi_gw_2] l.request.internal.aws     : AWS lambda.ListFunctions => 200
2022-10-17T16:17:51.323536403Z 2022-10-17T16:17:51.322  INFO --- [uest_thread)] l.s.a.lambda_executors     : ['node', '-e', 'const res = require("/tmp/function.zipfile.016c29e9/lambda.js").handler({"version": "2.0", "routeKey": "POST /docs/", "rawPath": "/docs/", "rawQueryString": "", "headers": {"host": "api-local.mts.bah.com", "cache-control": "max-age=0", "sec-ch-ua": "\\"Chromium\\";v=\\"106\\", \\"Google Chrome\\";v=\\"106\\", \\"Not;A=Brand\\";v=\\"99\\"", "sec-ch-ua-mobile": "?0", "sec-ch-ua-platform": "\\"macOS\\"", "upgrade-insecure-requests": "1", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36", "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9", "sec-fetch-site": "none", "sec-fetch-mode": "navigate", "sec-fetch-user": "?1", "sec-fetch-dest": "document", "accept-encoding": "gzip, deflate, br", "accept-language": "en-US,en;q=0.9", "x-localstack-tgt-api": "apigateway", "x-forwarded-for": "172.20.0.1, api-local.mts.bah.com", "x-localstack-edge": "https://api-local.mts.bah.com"}, "body": "", "requestContext": {"accountId": "000000000000", "apiId": "cd154862", "authorizer": {}, "domainName": "api-local.mts.bah.com", "domainPrefix": "api-local", "http": {"method": "GET", "path": "/docs/", "protocol": "HTTP/1.1", "sourceIp": "172.20.0.1", "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"}, "requestId": "d6472480-31a8-4bb6-89e8-a75b15b91e7b", "routeKey": "POST /docs/", "stage": "$default", "time": "17/Oct/2022:16:17:51 +0000", "timeEpoch": 1666023471139}, "isBase64Encoded": false, "queryStringParameters": {}, "stageVariables": {}, "pathParameters": {}, "cookies": []},{"function_name": "swagger-ui", "function_version": "$LATEST", "client_context": null, "invoked_function_arn": "arn:aws:lambda:us-east-1:000000000000:function:swagger-ui", "cognito_identity": null, "aws_request_id": "376edbe1-b96b-421e-87e9-44b6f1e40759", "memory_limit_in_mb": 512, "log_group_name": "/aws/lambda/swagger-ui", "log_stream_name": "2022/10/17/[1]e6ed1272"}); const log = (rs) => console.log(JSON.stringify(rs)); res && res.then ? res.then(r => log(r)) : log(res)']
```
logs for `/{prefix}/openapi.yaml` which should execute a different lambda, but instead invokes the `$default` route again:
```
2022-10-17T16:21:31.779 DEBUG --- [   asgi_gw_0] l.aws.serving.wsgi         : GET api-local.mts.bah.com/docs/openapi.yaml
2022-10-17T16:21:31.781837206Z 2022-10-17T16:21:31.781 DEBUG --- [   asgi_gw_0] l.s.a.apigateway_utils     : Skipping RouteKey '$default' for protocol 'HTTP'
2022-10-17T16:21:31.781883855Z 2022-10-17T16:21:31.781 DEBUG --- [   asgi_gw_0] l.s.a.apigateway_utils     : Skipping RouteKey '$default' for protocol 'HTTP'
2022-10-17T16:21:31.782055213Z 2022-10-17T16:21:31.781 DEBUG --- [   asgi_gw_0] l.s.a.integrations         : Invoking Lambda arn:aws:lambda:us-east-1:000000000000:function:swagger-ui for integration of API ID cd154862
2022-10-17T16:21:31.786933929Z 2022-10-17T16:21:31.785 DEBUG --- [   asgi_gw_3] l.aws.serving.wsgi         : POST localhost:4566/2015-03-31/functions/arn%3Aaws%3Alambda%3Aus-east-1%3A000000000000%3Afunction%3Aswagger-ui/invocations
2022-10-17T16:21:31.789869418Z 2022-10-17T16:21:31.789 DEBUG --- [uest_thread)] l.s.awslambda.lambda_api   : Running lambda arn:aws:lambda:us-east-1:000000000000:function:swagger-ui
2022-10-17T16:21:31.807079608Z 
```

**Comment by whummer** [comment]
Hi @jrauen , thanks for sharing the update. It seems we still had a small gap in our implementation, the issue you shared should now (hopefully) be fixed. When you get a chance, can you please pull the `latest` Docker image and try again? Thanks for your help!

**Comment by jrauen** [comment]
Worked like a charm. Thanks!
