### ISSUE TITLE
bug: `cloudformation:GetTemplate` does not return the template

### ISSUE THREAD

**Issue by bajelidze** [localstack/localstack#7657]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting from version 1.1.0 of LocalStack, the `cloudformation:GetTemplate` call no longer returns the stack template, but rather returns:
```json
{
    "StagesAvailable": [
        "Original",
        "Processed"
    ]
}
```

By default, AWS SDK requests the `Processed` stage of the template, so there is no reason why LocalStack would respond like this. But even when specifying the stage explicitly using the `--template-stage` option, it still responds like this. 

### Expected Behavior

The expected behavior is for `cloudformation:GetTemplate` to return the template of the stack in the `Processed` stage by default.

### How are you starting LocalStack?

With a `docker run` command

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    docker run -dp '0.0.0.0:4566:4566' localstack/localstack:1.3.1

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    aws --region eu-west-1 --endpoint 'http://localhost:4566' cloudformation create-stack --stack-name test-stack --template-body file://tmpl.yaml

Where `tmpl.yaml` is a Cloudformation template located in the same directory with the following content:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Test Stack
Resources:
  MainSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Main security group
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - Ref: 'EC2Role'
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: EC2Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:*
                  - cloudformation:*
                Resource: '*'
  n11:
    Type: AWS::EC2::Instance
    Properties:
      Tags:
        - Key: node_id
          Value: n11
      InstanceType: c5d.2xlarge
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 20
        - DeviceName: /dev/sdb
          Ebs:
            VolumeSize: 100
        - DeviceName: /dev/sdc
          Ebs:
            VolumeSize: 50
        - DeviceName: /dev/sdd
          Ebs:
            VolumeSize: 50
      ImageId: ami-785db401
      IamInstanceProfile:
        Ref: 'InstanceProfile'
      NetworkInterfaces:
        - GroupSet:
            - Ref: MainSecurityGroup
          DeviceIndex: 0
          AssociatePublicIpAddress: 'true'
      SourceDestCheck: 'false'
```

Afterwards the call to `get-template` will return the list of available stages instead of the template:
```bash
$ aws --region eu-west-1 --endpoint 'http://localhost:4566' cloudformation get-template --stack-name test-stack
{
    "StagesAvailable": [
        "Original",
        "Processed"
    ]
}
```

### Environment

```markdown
- OS: Fedora 37
- LocalStack: 1.3.1
```

### Anything else?

This bug appeared starting from LocalStack version `1.1.0`. Version `1.0.4` works as expected, i.e., returns the template of the stack. I suspect that this PR could have introduced the bug: https://github.com/localstack/localstack/pull/6635, but I can't say for sure.

**Comment by deepak2431** [comment]
@whummer Can I work on this issue?

**Comment by deepak2431** [comment]
Working on this issue

**Comment by pinzon** [comment]
Hi @bajelidze please make sure to pull the latest version of LocalStack. This problem has been already fixed in newer versions. 

Thanks @deepak2431 for triaging this.

**Comment by bajelidze** [comment]
@pinzon, Hi! Thanks for the reply. Sorry it took me some time to respond.

I checked the latest version of LocalStack, which is `1.4.0` right now, and the bug is still there. The steps of reproduction described in this issue stay the same, except LocalStack needs to be run with version `1.4.0` instead of `1.3.1`.
```bash
docker run -dp '0.0.0.0:4566:4566' localstack/localstack:1.3.1
```

I tried the fix by @deepak2431 and it does indeed fix the issue (thanks a lot to @deepak2431 for the efforts!). Using the LocalStack image built from their branch I was able to successfully get the template using the `GetTemplate` call.

**Comment by pinzon** [comment]
@bajelidze thanks for checking with us again. After triaging again, I found out that if you run that exact version (1.4.0), **the problem does exis**t. You need to pull the image with the tag: **latest**. And run the container with the same tag.

With the latest build. the error it's not reproducible. 
```
LocalStack version: 1.4.1.dev
LocalStack build date: 2023-03-16
LocalStack build git hash: 77aab874
```

**Comment by bajelidze** [comment]
@pinzon Oh, sorry for bothering. It does indeed work on `latest`. I somehow assumed that the `latest` tag was pointing to `1.4.0`, not a big expert of Docker. Thank you very much for you help.
