### ISSUE TITLE
bug: Creating aws_db_option_group failure

### ISSUE THREAD

**Issue by jathael** [localstack/localstack#8176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behaviour

When I want to create an option group in RDS using `tflocal` I receive below error:

```bash
tflocal apply -target aws_db_option_group.rds_mssql

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_db_option_group.rds_mssql will be created
  + resource "aws_db_option_group" "rds_mssql" {
      + arn                      = (known after apply)
      + engine_name              = "sqlserver-ee"
      + id                       = (known after apply)
      + major_engine_version     = "11.00"
      + name                     = "option-group-test-terraform"
      + name_prefix              = (known after apply)
      + option_group_description = "Terraform Option Group"
      + tags_all                 = (known after apply)

      + option {
          + db_security_group_memberships  = []
          + option_name                    = "SQLSERVER_BACKUP_RESTORE"
          + vpc_security_group_memberships = []

          + option_settings {
              + name  = "IAM_ROLE_ARN"
              + value = "arn"
            }
        }
      + option {
          + db_security_group_memberships  = []
          + option_name                    = "TDE"
          + vpc_security_group_memberships = []
        }
      + option {
          + db_security_group_memberships  = []
          + option_name                    = "Timezone"
          + vpc_security_group_memberships = []

          + option_settings {
              + name  = "TIME_ZONE"
              + value = "UTC"
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error
│ message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_db_option_group.rds_mssql: Creating...
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command to
│ verify that no other changes are pending:
│     terraform plan
│ 	
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as
│ part of an error message.
╵
╷
│ Error: modifying DB Option Group: InvalidParameterValue: At least one option must be added, modified, or removed.
│ 	status code: 400, request id: K010...
│ 
│   with aws_db_option_group.rds_mssql,
│   on main.tf line 747, in resource "aws_db_option_group" "rds_mssql":
│  747: resource "aws_db_option_group" "rds_mssql" {
│ 
╵
```

Option group is created but no actual options and options settings are added to it.

### Expected Behaviour

Option group is created with all options and options settings.

### How are you starting LocalStack?

Custom (please describe below)

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

    Using official k8s helm chart

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

    tflocal apply -target aws_db_option_group.rds_mssql

### Environment

```markdown
- OS: MacOS Ventura Version 13.3.1
- LocalStack: localstack-pro:latest
```

**Comment by zilch-piotrniebylski** [comment]
Any news about fixing this?

**Comment by steffyP** [comment]
Hi @jathael, hi @zilch-piotrniebylski,

we identified the issue and are working on a fix. 
You will be notified once the fix is available 🙏

**Comment by steffyP** [comment]
Hey @jathael, hi @zilch-piotrniebylski,

the issue was fixed in the latest image. Please pull `localstack/localstack-pro:latest` 🙏 

Let us know if you still encounter any issues!

**Comment by zilch-piotrniebylski** [comment]
Unfortunately the issue persist in localstack-pro:latest image, I have just tried again and have the exact same result:

` tflocal apply -target aws_db_option_group.rds_mssql
aws_db_option_group.rds_mssql: Refreshing state... [id=option-group-test-terraform]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_db_option_group.rds_mssql is tainted, so must be replaced
-/+ resource "aws_db_option_group" "rds_mssql" {
      ~ arn                      = "arn:aws:rds:eu-west-1:000000000000:og:option-group-test-terraform" -> (known after apply)
      ~ id                       = "option-group-test-terraform" -> (known after apply)
        name                     = "option-group-test-terraform"
      + name_prefix              = (known after apply)
      - tags                     = {} -> null
      ~ tags_all                 = {} -> (known after apply)
        # (3 unchanged attributes hidden)

      + option {
          + db_security_group_memberships  = []
          + option_name                    = "SQLSERVER_BACKUP_RESTORE"
          + vpc_security_group_memberships = []

          + option_settings {
              + name  = "IAM_ROLE_ARN"
              + value = "arn"
            }
        }
      + option {
          + db_security_group_memberships  = []
          + option_name                    = "TDE"
          + vpc_security_group_memberships = []
        }
      + option {
          + db_security_group_memberships  = []
          + option_name                    = "Timezone"
          + vpc_security_group_memberships = []

          + option_settings {
              + name  = "TIME_ZONE"
              + value = "UTC"
            }
        }
    }

Plan: 1 to add, 0 to change, 1 to destroy.
╷
│ Warning: Resource targeting is in effect
│ 
│ You are creating a plan with the -target option, which means that the result of this plan may not represent all of the changes requested by the current configuration.
│ 
│ The -target option is not for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as part of an error
│ message.
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_db_option_group.rds_mssql: Destroying... [id=option-group-test-terraform]
aws_db_option_group.rds_mssql: Destruction complete after 0s
aws_db_option_group.rds_mssql: Creating...
╷
│ Warning: Applied changes may be incomplete
│ 
│ The plan was created with the -target option in effect, so some changes requested in the configuration may have been ignored and the output values may not be fully updated. Run the following command to verify
│ that no other changes are pending:
│     terraform plan
│ 	
│ Note that the -target option is not suitable for routine use, and is provided only for exceptional situations such as recovering from errors or mistakes, or when Terraform specifically suggests to use it as
│ part of an error message.
╵
╷
│ Error: modifying DB Option Group: InvalidParameterValue: At least one option must be added, modified, or removed.
│ 	status code: 400, request id: 9V1...
│ 
│   with aws_db_option_group.rds_mssql,
│   on main.tf line 747, in resource "aws_db_option_group" "rds_mssql":
│  747: resource "aws_db_option_group" "rds_mssql" {
│ 
╵`

**Comment by steffyP** [comment]
Hey @jathael, hi @zilch-piotrniebylski,

could you please verify that the fix is working for you?

**Comment by zilch-piotrniebylski** [comment]
Hey, sorry for the delay.

Yes, above issue disappeared. Thank you for lighting fast fix! :D
