### ISSUE TITLE
No SubscriptionConfirmation message for HTTP(S) endpoints

### ISSUE THREAD

**Issue by kcajmagic** [localstack/localstack#881]
When you subscribe to a SNS topic a confirmation message should be sent.

For example (taken from amazon docs):
```
{
  "Type" : "SubscriptionConfirmation",
  "MessageId" : "165545c9-2a5c-472c-8df2-7ff2be2b3b1b",
  "Token" : "2336412f37fb687f5d51e6e241d09c805a5a57b30d712f794cc5f6a988666d92768dd60a747ba6f3beb71854e285d6ad02428b09ceece29417f1f02d609c582afbacc99c583a916b9981dd2728f4ae6fdb82efd087cc3b7849e05798d2d2785c03b0879594eeac82c01f235d0e717736",
  "TopicArn" : "arn:aws:sns:us-west-2:123456789012:MyTopic",
  "Message" : "You have chosen to subscribe to the topic arn:aws:sns:us-west-2:123456789012:MyTopic.\nTo confirm the subscription, visit the SubscribeURL included in this message.",
  "SubscribeURL" : "https://sns.us-west-2.amazonaws.com/?Action=ConfirmSubscription&TopicArn=arn:aws:sns:us-west-2:123456789012:MyTopic&Token=2336412f37fb687f5d51e6e241d09c805a5a57b30d712f794cc5f6a988666d92768dd60a747ba6f3beb71854e285d6ad02428b09ceece29417f1f02d609c582afbacc99c583a916b9981dd2728f4ae6fdb82efd087cc3b7849e05798d2d2785c03b0879594eeac82c01f235d0e717736",
  "Timestamp" : "2012-04-26T20:45:04.751Z",
  "SignatureVersion" : "1",
  "Signature" : "EXAMPLEpH+DcEwjAPg8O9mY8dReBSwksfg2S7WKQcikcNKWLQjwu6A4VbeS0QHVCkhRS7fUQvi2egU3N858fiTDN6bkkOxYDVrY0Ad8L10Hs3zH81mtnPk5uvvolIC1CXGu43obcgFxeL3khZl8IKvO61GWB6jI9b5+gLPoBc1Q=",
  "SigningCertURL" : "https://sns.us-west-2.amazonaws.com/SimpleNotificationService-f3ecfb7224c7233fe7bb5f59f96de52f.pem"
}
```

Unfortunately, this message currently does not happen. Thus breaking the AWS SNS contract.

http://docs.aws.amazon.com/sns/latest/dg/SendMessageToHttp.html 
https://docs.aws.amazon.com/sns/latest/dg/json-formats.html#http-subscription-confirmation-json

**Comment by nursultanturdaliev** [comment]
👍

**Comment by sowee15** [comment]
I appear to be running into the same issue. Is this supposed to be fixed? My endpoint is not called when subscribing but it is called when publishing.

**Comment by whummer** [comment]
Thanks for reporting - this should be fixed in #1669 . Closing this issue - please re-open if the problem persists. @sowee15 @nursultanturdaliev @kcajmagic

**Comment by ericfreese** [comment]
Hey @whummer, thanks for adding this functionality! It looks like we're not setting the headers quite right though. For a confirmation message, the `x-amz-sns-message-type` header should be set to `SubscriptionConfirmation` instead of `Notification`. I'm seeing the latter come through using the latest docker image.

See https://docs.aws.amazon.com/sns/latest/dg/sns-message-and-json-formats.html#http-header

**Comment by whummer** [comment]
Thanks for the pointer @ericfreese - should be fixed in #1671

**Comment by sowee15** [comment]
Hi, I'm using the latest docker image, but my endpoint still doesn't get called with subscription confirmation. I'm using `http://host.docker.internal` as endpoint's hostname. However, it does get called when publishing. I did a `docker pull localstack/localstack` to get the latest version and restarted localstack. Anything I'm missing? Thanks!
