### ISSUE TITLE
Failure to bring up aws transcribe service on localstack 2.3.1 

### ISSUE THREAD

**Issue by aenbacka** [localstack/localstack#9281]
Hello,

I have an issue with starting a transcribe job using aws transcribe on localstack 2.3.1. When trying to initiate a transcribe job (StartTranscriptionJob) I receive an error that "installation of Vosk has failed". This worked on images prior to 2.3 (I have tried with version 2.3.0 as well, and same issue).  I am using the linux/amd64 image on Mac M1.

**Comment by aenbacka** [comment]
This still seems to be broken in latest official 2.3.2 image as well as in latest. On my Mac M1 (both using linux/amd64 and linux/arm64) the installation of Vosk dependency fails (pip install vosk). I wonder if it could be related to this https://github.com/localstack/localstack/pull/8685 (as it seems to work fine prior to this change)?

**Comment by sannya-singal** [comment]
Hi @aenbacka, thanks for reporting the issue. 

Can you please pull the `latest` linux/amd64 docker image on Mac M1 and try `start-transcription-job`, the issue should be resolved. Thanks!

**Comment by aenbacka** [comment]
> Hi @aenbacka, thanks for reporting the issue.
> 
> Can you please pull the `latest` linux/amd64 docker image on Mac M1 and try `start-transcription-job`, the issue should be resolved. Thanks!

Hello @sannya-singal, thanks for the reply. I tested with the latest linux/amd64 image on M1, but I still get an error message when trying to start a transcription job. The error message is as follows: 

```
2024-01-02T12:08:01.094  INFO --- [   asgi_gw_0] localstack.request.aws     : AWS transcribe.StartTranscriptionJob => 200
2024-01-02T12:08:40.210 ERROR --- [functhread17] l.s.transcribe.provider    : Transcription job example failed: cannot load library '/var/lib/localstack/lib/python-packages/lib/python3.11/site-packages/vosk/libvosk.so': /var/lib/localstack/lib/python-packages/lib/python3.11/site-packages/vosk/libvosk.so: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/transcribe/provider.py", line 319, in _run_transcription_job
    self._setup_vosk()
  File "/opt/code/localstack/localstack/services/transcribe/provider.py", line 115, in _setup_vosk
    from vosk import SetLogLevel  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/lib/localstack/lib/python-packages/lib/python3.11/site-packages/vosk/__init__.py", line 32, in <module>
    _c = open_dll()
         ^^^^^^^^^^
  File "/var/lib/localstack/lib/python-packages/lib/python3.11/site-packages/vosk/__init__.py", line 26, in open_dll
    return _ffi.dlopen(os.path.join(dlldir, "libvosk.so"))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: cannot load library '/var/lib/localstack/lib/python-packages/lib/python3.11/site-packages/vosk/libvosk.so': /var/lib/localstack/lib/python-packages/lib/python3.11/site-packages/vosk/libvosk.so: cannot open shared object file: No such file or directory
```

**Comment by sannya-singal** [comment]
@aenbacka can you please confirm the following: 

- the localstack docker image that you pulled is of `amd64` 
- after creating an s3 bucket and copying a sample file you run a similar command as following: 

```
awslocal transcribe start-transcription-job \
    --transcription-job-name example \
    --media MediaFileUri=s3://foo/example.wav \
    --language-code en-IN
```

**Comment by aenbacka** [comment]
Hello,

When running the above command with the latest image, it now works fine
(yesterday it did not work when I tried the same
of some reason).

However, when using my own docker-compose.yml file to bring up localstack,
and trying the same command it does not work,
and I get the same error message that installation of vosk has failed.

I am using the following docker-compose.yml,with this one the awslocal
transcribe start-transcription-job fails. Should it work correctly with the
below
docker-compose.yml?

localstack-aws:
image: localstack/localstack:latest
platform: linux/amd64 # Transcribe service is only supported on amd64 image
ports:
- "4566:4566" # LocalStack Gateway
environment:
- MAIN_CONTAINER_NAME=localstack-aws
- DOCKER_HOST=unix:///var/run/docker.sock
- EAGER_SERVICE_LOADING=1
- SERVICES=s3,lambda,transcribe,dynamodb
volumes:
- "${LOCALSTACK_VOLUME_DIR:-./.localstack-volume}:/var/lib/localstack"
- "/var/run/docker.sock:/var/run/docker.sock"
- "./lambda/:/opt/code/lambda"
- "./localstack-aws/:/etc/localstack/init/ready.d"

**Comment by aenbacka** [comment]
@sannya-singal Seems that using docker-compose the issue still persists.

**Comment by sannya-singal** [comment]
Hi @aenbacka, can you try re-running the docker-compose.yml after clearing the mounted `localstack-volume` directory?

**Comment by aenbacka** [comment]
@sannya-singal Thanks for the suggestion, now it works also with docker-compose, clearing the localstack-volume helped! :)

**Comment by sannya-singal** [comment]
Great @aenbacka! 🎉
