### ISSUE TITLE
bug: Kinesis mock server consumes all possible CPI resources and eventually fails on out of memory

### ISSUE THREAD

**Issue by stekycz** [localstack/localstack#9755]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When Kinesis is under high load with large records (e.g. 100 of records with ~256kB each) it slows down and eventually fail on out of memory.

### Expected Behavior

The server should not be taken down by such a high traffic.

### How are you starting LocalStack?

With a docker-compose file

#### How are you starting localstack (e.g., `bin/localstack` command, arguments, or `docker-compose.yml`)

```sh
docker run localstack/localstack:3.0.1
```

#### Client commands (e.g., AWS SDK code snippet, or sequence of "awslocal" commands)

```ts
const kinesis = new AWS.Kinesis(...);
await Promise.all(new Array(100).fill(null).map(async () => {
  await kinesis.putRecords({ streamName: '...', records: [...] });
}));
```

### Environment

```markdown
- OS: macOS 14.1.1
- LocalStack: 3.0.1
```

### Anything else?

I was able to overcome the issue (temporarily) by setting `KINESIS_MOCK_PERSIST_INTERVAL` to 1 year to effectively turn off the data persistence.

I did not find any other way to disable the persistence as it is [forced for Kinesis Mock Server by LocalStack](https://github.com/localstack/localstack/blob/v3.0.1/localstack/services/kinesis/kinesis_mock_server.py#L88-L93). [Default persistence interval is 5s](https://github.com/localstack/localstack/blob/v3.0.1/localstack/config.py#L782).

I admit higher volume on simple LocalStack container (especially in environment with low resources) is sort of an edge case. The solution may not have to be performance improvement itself (even though saving all streams for an account into a single JSON file seems naive). I would welcome even standard way how to turn off Kinesis persistence through LocalStack configuration.

**Comment by rof20004** [comment]
@stekycz can you share where I can put KINESIS_MOCK_PERSIST_INTERVAL conf?

**Comment by stekycz** [comment]
@rof20004 Absolutely! Minimal example
```yaml
services:
  localstack:
    image: localstack/localstack:3.0.1
    environment:
      KINESIS_MOCK_PERSIST_INTERVAL: 365d
```

**Comment by rof20004** [comment]
Thank you @stekycz 

If I send at same time (5 times or more) this command, the cpu goes to 100% again, even with 1 year interval. Seems kinesis mock has a bug.

`
aws kinesis put-record \
    --stream-name captures-stream \
    --partition-key 1 \
    --data "Hi, how are you?" \
    --cli-binary-format raw-in-base64-out \
    --endpoint-url http://localhost:4566 \
    --region sa-east-1
`

**Comment by stekycz** [comment]
I agree! The performance and CPU utilization is still high. This just allowed me to reduce it so it falls down eventually and does not take down the mock server.

**Comment by rof20004** [comment]
I opened a bug on kinesis mock server project: https://github.com/etspaceman/kinesis-mock/issues/669

**Comment by alexrashed** [comment]
Seems like the related issue (https://github.com/etspaceman/kinesis-mock/issues/669) has been closed.
Does this mean your issue has been resolved and we can also close this one?
Thanks!

**Comment by stekycz** [comment]
I am still experiencing the issue. The [issue in kinesis-mock](https://github.com/etspaceman/kinesis-mock/issues/669) seems to be closed because of Apple M1 usage with Rosetta. I am using Intel based Mac and I still have performance issue (even though the CPU usage falls down eventually).

The forced kinesis persistence makes the performance even worse and I have to hack it using `KINESIS_MOCK_PERSIST_INTERVAL=365d` instead of something like `KINESIS_ SHOULD_PERSIST_DATA=false`.

Even then it takes some time to get to low CPU usage which has an impact on performance in CI with limited resources.

**Comment by stekycz** [comment]
I am using **Docker Desktop 4.25.2** on **macOS 14.1.2**

I have used the following script to replicate the issue

```bash
#!/usr/bin/env bash
set -euo pipefail

docker container run \
  --detach \
  --name localstack \
  --rm \
  --publish 4566:4566 \
  --env SERVICES=kinesis \
  --env KINESIS_MOCK_PERSIST_INTERVAL=5s \
  localstack/localstack:3.0.1

aws kinesis create-stream \
  --stream-name foobar-stream \
  --shard-count 1 \
  --endpoint-url http://localhost:4566 \
  --region us-east-1

sleep 10

data=$(printf 'X%.0s' {1..262144})

for i in {1..100}; do
  echo -n "."
  aws kinesis put-record \
    --stream-name foobar-stream \
    --partition-key 1 \
    --data "$data" \
    --cli-binary-format raw-in-base64-out \
    --endpoint-url http://localhost:4566 \
    --region us-east-1 &
done
echo ""
```

Notice the env `KINESIS_MOCK_PERSIST_INTERVAL` being set to `5s` (which is the default value). I am getting the following container stats

<img width="1198" alt="Snímek obrazovky 2023-12-01 v 11 46 38" src="https://github.com/localstack/localstack/assets/865447/3a7ef042-a1a1-4bd0-9f9a-5736a3f33363">

When I set `KINESIS_MOCK_PERSIST_INTERVAL` to `365s`, I get the following, way better performance stats

<img width="1197" alt="Snímek obrazovky 2023-12-01 v 11 49 07" src="https://github.com/localstack/localstack/assets/865447/2f52b046-f400-49a7-8192-c985abcaef63">

I would prefer to just say `KINESIS_SHOULD_PERSIST_DATA=false` instead of `KINESIS_MOCK_PERSIST_INTERVAL=365d` because [the persistence is currently always on](https://github.com/localstack/localstack/blob/v3.0.1/localstack/services/kinesis/kinesis_mock_server.py#L88).

However, it still seems there is a performance issue with persistence in the Kinesis Mock server.

**Comment by sobotklp** [comment]
I'm also experiencing this issue, though I'm running Localstack within an EKS cluster on Intel-based underlying instances.

**Comment by dfangl** [comment]
#9871 will introduce a flag to disable the persistence mechanism in kinesis-mock completely.

We will continue to look into improving persistence performance in kinesis-mock, however. There seem to be extensive memory issues, especially with bigger payloads >= 512KB.

Thank you for reporting this!

**Comment by stekycz** [comment]
Is this being handled already, should it be kept around in backlog or should it be left for closing?

**Comment by stekycz** [comment]
I can still see the symptoms of the issue. I have changed from Docker Desktop to Podman Desktop and from Intel Mac to M3 Pro Mac since the time I have reported the issue. Notice the CPU usage on the screenshot below. I amusing the same setup as before for the VM under the hood of Podman Desktop.

<img width="1047" alt="Snímek obrazovky 2024-10-14 v 9 59 08" src="https://github.com/user-attachments/assets/0c29b152-f86e-48c7-a3b4-4d7544deb1f7">

**Comment by alexrashed** [comment]
@stekycz Have you tried setting the environment variable @dfangl mentioned in his previous comment?
Since #9871 you can disable Kinesis persistence with `KINESIS_PERSISTENCE=0`.

**Comment by stekycz** [comment]
Yes, I do have it set for overcoming the issue temporarily but it won't work forever. I would like to leverage the persistency but I has quite a high cost.

**Comment by alexrashed** [comment]
Thanks, @stekycz!
@dfangl This basically boils down to the storage/persistence handling in `kinesis-mock`, but do you think there's something we can do on our side to fix this?

**Comment by dfangl** [comment]
As far as I am aware, there is nothing on our side (except increasing storage intervals), it seems persistence is quite inefficient on the kinesis-mock side.
We might want to get @etspaceman s input on this, maybe open up an issue to discuss it in kinesis-mock directly.

**Comment by etspaceman** [comment]
When I looked into this last time I was unable to actually reproduce the issue. And I just ran the same script without any issues on my end. No freezing or anything like that. So I'm not really sure how to proceed here. 

My environment:

Apple M1 Pro
16 GB RAM
Rancher Desktop for Docker

**Comment by dfangl** [comment]
Thanks for your fast response @etspaceman !
I started kinesis-mock with: `docker run --rm -p 4566:4566 --name kinesis-mock -d -e KINESIS_MOCK_PLAIN_PORT=4566 -e SHOULD_PERSIST_DATA=true -e PERSIST_PATH=/tmp -e PERSIST_FILE_NAME=persist -e PERSIST_INTERVAL=5s ghcr.io/etspaceman/kinesis-mock:0.4.7`.

After that, I just put 1024KB records into the container, looped 100times. After some time, you will see the crash due to a jvm out of memory error.
We can glady also take this to a kinesis-mock issue.

**Comment by HarshCasper** [comment]
Due to the forthcoming changes in our distribution and development model ([read more](https://blog.localstack.cloud/the-road-ahead-for-localstack/)), this issue tracker is no longer being maintained, and this issue is now being closed. If you'd like us to take a look or need further support, please reach out through one of our support channels:

-   💬 [GitHub Discussions](https://github.com/orgs/localstack/discussions)
-   📖 [Help & Support](https://docs.localstack.cloud/aws/getting-started/help-support/)
